const pages = await fetch('http://127.0.0.1:9229/json').then(r => r.json());
const page = pages.find(p => p.url.includes('fixture=tradecraft'));
if (!page) throw new Error('Tradecraft page not found');
const ws = new WebSocket(page.webSocketDebuggerUrl);
const pending = new Map(); let nextId = 1;
ws.onmessage = e => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } };
await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject; });
const cmd = (method, params={}) => new Promise(resolve => { const id = nextId++; pending.set(id, resolve); ws.send(JSON.stringify({id, method, params})); });
const evalJS = async expression => (await cmd('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.result.value;
await cmd('Runtime.enable');
await new Promise(r => setTimeout(r, 1200));
const inspect = `(() => { const b=document.querySelector('.unified-layer-toggle'); const p=document.querySelector('.pdf-pane'); const c=document.querySelector('.context-pane'); return {label:b?.textContent?.trim(), pdfZ:getComputedStyle(p).zIndex, contextZ:getComputedStyle(c).zIndex, pdfPointer:getComputedStyle(p).pointerEvents, contextPointer:getComputedStyle(c).pointerEvents}; })()`;
console.log('BEFORE', JSON.stringify(await evalJS(inspect)));
console.log('CLICK', await evalJS(`document.querySelector('.unified-layer-toggle')?.click(); true`));
await new Promise(r => setTimeout(r, 250));
console.log('AFTER_CLICK', JSON.stringify(await evalJS(inspect)));
console.log('KEY_F6', await evalJS(`window.dispatchEvent(new KeyboardEvent('keydown',{key:'F6',bubbles:true,cancelable:true})); true`));
await new Promise(r => setTimeout(r, 250));
console.log('AFTER_SYNTH_F6', JSON.stringify(await evalJS(inspect)));
ws.close();
