import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";
const s=(id:string,title:string,prompt:string,responseKind:TechniqueResponseKind="long-text"):TechniqueStepDefinition=>({id,title,prompt,responseKind}); const w=(...steps:TechniqueStepDefinition[])=>steps;
export const LEGAL_SPECIFIC_WORKFLOWS:Record<string,TechniqueStepDefinition[]>={
  "CREAC Analysis":w(s("conclusion","Conclusion preview","State the likely answer to the legal issue in bounded terms."),s("rule","Rule","State controlling authority, elements, standards, and exceptions."),s("explain","Rule explanation","Explain how relevant authorities interpret and apply the rule."),s("apply","Application","Apply the rule to material facts with analogies, distinctions, and counterarguments."),s("conclude","Conclusion","Restate the supported conclusion and unresolved factual or legal uncertainty.")),
  "Precedent Synthesis":w(s("issue","Legal issue","Define the precise issue and jurisdictional hierarchy."),s("cases","Relevant precedents","Collect controlling and persuasive cases with holdings, facts, and procedural posture."),s("dimensions","Comparison dimensions","Identify legally meaningful similarities, distinctions, exceptions, and doctrinal trends."),s("synthesize","Synthesize rule","Derive the best-supported rule or pattern without flattening conflicting cases."),s("apply","Current implication","Explain how the synthesized precedent bears on the present facts and where uncertainty remains.")),
  "Analogical Legal Reasoning":w(s("target","Target case","State the current facts and legal issue."),s("sources","Source cases","Select precedents with potentially relevant factual and doctrinal features."),s("similarities","Material similarities","Identify similarities that matter under the governing rule, not merely surface resemblance."),s("differences","Material distinctions","Identify differences that could justify a different result."),s("judgment","Analogical judgment","Assess which analogy is strongest and what competing analogy a reasonable opponent would use.")),
  "Rule Synthesis":w(s("authorities","Authority set","Identify statutes, regulations, cases, and other sources relevant to the issue."),s("propositions","Rule propositions","Extract explicit tests, elements, exceptions, standards, and burden rules."),s("reconcile","Reconcile authorities","Resolve hierarchy, chronology, jurisdiction, and apparent doctrinal conflicts."),s("rule","Synthesized rule","Write a coherent rule that captures controlling principles and recognized exceptions."),s("limits","Limits","Record unresolved splits, fact dependence, and authorities that resist synthesis.")),
  "Elements Analysis":w(s("claim","Claim or offense","Identify the cause of action, offense, defense, or legal test."),s("elements","Elements","List every required element, subelement, burden, and applicable definition."),s("facts","Facts by element","Map supporting, contradicting, and missing facts to each element."),s("strength","Element strength","Assess whether each element is satisfied, contested, or evidentially weak."),s("conclusion","Whole-claim conclusion","State whether failure or uncertainty on any required element changes the overall result.")),
  "Proportionality Analysis":w(s("measure","State action or restriction","Define the challenged measure, objective, affected right or interest, and legal framework."),s("suitability","Suitability","Assess whether the measure can rationally advance the legitimate objective."),s("necessity","Necessity","Assess whether a less restrictive but similarly effective alternative exists."),s("balance","Balancing","Compare the importance of the objective with the severity of rights or interest burdens."),s("judgment","Proportionality judgment","State the conclusion and factual assumptions that drive it.")),
  "Balancing Test Analysis":w(s("test","Balancing framework","Identify the governing factors, their legal source, and any threshold or presumptions."),s("facts","Facts by factor","Map record facts and uncertainty to each factor."),s("weight","Relative weight","Assess which factors carry more legal significance and why."),s("counter","Competing balance","Construct the strongest plausible balancing argument for the opposite result."),s("conclusion","Conclusion","State the likely balance and what factual change could alter it.")),
  "Legal Issue Spotting":w(s("facts","Fact pattern","Summarize legally material facts without prematurely choosing doctrines."),s("actors","Actors and relationships","Identify parties, duties, transactions, harms, authorities, and procedural posture."),s("issues","Potential issues","Generate plausible claims, defenses, jurisdictional, evidentiary, procedural, and remedy issues."),s("prioritize","Prioritize","Rank issues by legal significance, factual support, deadlines, and outcome leverage."),s("research","Research questions","Translate unresolved issues into precise authority and fact questions.")),
};
export const LEGAL_SPECIFIC_CATALOG_WORKFLOW_COUNT=Object.keys(LEGAL_SPECIFIC_WORKFLOWS).length;
export const hasLegalSpecificCatalogWorkflow=(name:string)=>Boolean(LEGAL_SPECIFIC_WORKFLOWS[name]);
export const legalSpecificCatalogWorkflow=(name:string)=>LEGAL_SPECIFIC_WORKFLOWS[name]?.map(x=>({...x}));