import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";

const s = (id: string, title: string, prompt: string, responseKind: TechniqueResponseKind = "long-text"): TechniqueStepDefinition => ({ id, title, prompt, responseKind });
const w = (...steps: TechniqueStepDefinition[]) => steps;

export const EXPERT_SPECIFIC_WORKFLOWS: Record<string, TechniqueStepDefinition[]> = {
  "Real-Time Delphi": w(s("question", "Forecast question", "Define the question, horizon, resolution criteria, and response format precisely."), s("panel", "Panel and independence", "Select relevant and diverse experts, disclose conflicts, and preserve independent initial judgments."), s("rounds", "Continuous rounds", "Collect anonymous estimates and reasons, expose controlled feedback in near real time, and allow experts to revise without waiting for fixed rounds."), s("dispersion", "Track convergence and dissent", "Monitor central tendency, dispersion, persistent disagreement, and argument changes rather than treating convergence as automatically correct."), s("close", "Closure and record", "Apply a stopping rule, preserve final distributions and dissent, and document the evidence or assumptions that drove revisions.")),
  "Nominal Group Technique": w(s("problem", "Problem or decision", "Define the question and the criterion by which ideas or priorities will be judged."), s("silent", "Silent generation", "Have participants generate ideas independently before discussion to reduce production blocking and status effects."), s("roundrobin", "Round-robin collection", "Collect one idea at a time from each participant until all ideas are recorded without debate."), s("clarify", "Clarification", "Discuss items for understanding, merge only true duplicates, and preserve minority ideas without advocacy pressure."), s("vote", "Independent ranking", "Have participants privately rank or score priorities, aggregate the results, and record residual disagreement.")),
  "Expert Elicitation": w(s("quantity", "Target judgment", "Define the uncertain quantity or proposition, units, conditioning information, time point, and resolution meaning."), s("experts", "Expert selection", "Select experts for relevant knowledge and diversity, manage conflicts, and document roles and selection rationale."), s("prepare", "Training and evidence", "Provide common evidence, definitions, uncertainty training, and practice questions while avoiding coaching toward consensus."), s("elicit", "Individual elicitation", "Elicit central estimates, bounds or distributions, reasons, and uncertainty independently using a structured protocol."), s("aggregate", "Aggregate and document", "Combine judgments using a declared behavioral or mathematical rule, preserve dissent, and document the full elicitation process.")),
  "Cooke's Classical Model": w(s("targets", "Target and seed questions", "Define target quantities and select calibration seed questions from the same expertise domain whose true values are known to the analyst but not the experts."), s("quantiles", "Expert quantiles", "Elicit the same predefined quantiles for seed and target variables from each expert using consistent framing."), s("scores", "Calibration and information", "Score each expert's statistical calibration on seeds and the informativeness of their distributions relative to the background range."), s("weights", "Performance weights", "Compute declared performance-based weights, including any calibration cutoff or optimization rule, and compare with equal weighting."), s("pool", "Combined distribution", "Pool target distributions using the selected weights and report sensitivity to seed choice, background range, and weighting rule.")),
  "Quantile Elicitation": w(s("quantity", "Quantity and range", "Define the uncertain quantity, units, conditioning assumptions, and physically or logically possible range."), s("median", "Median", "Elicit the 50th percentile first or at an appropriate stage, asking for the value equally likely to be above or below."), s("tails", "Lower and upper quantiles", "Elicit symmetric or protocol-specified tail quantiles and challenge whether the stated interval is unrealistically narrow."), s("coherence", "Coherence check", "Check ordering, bounds, interpretation of percentiles, and whether the implied distribution matches the expert's verbal beliefs."), s("revise", "Review and record", "Allow revision after feedback on inconsistencies and document final quantiles plus the reasoning behind tail judgments.")),
  "Superforecasting Tournament": w(s("questions", "Resolvable questions", "Create clear, time-bounded questions with unambiguous resolution criteria and base-rate relevance."), s("forecasts", "Independent probabilities", "Collect individual probabilistic forecasts with reasons and timestamps before discussion or aggregation."), s("update", "Frequent updating", "Encourage forecasters to update when evidence changes and preserve the full forecast trajectory rather than only final answers."), s("score", "Proper scoring", "Score resolved forecasts with a proper rule such as Brier score and compare calibration, discrimination, and update behavior."), s("learn", "Selection and learning", "Use repeated performance, decomposition, feedback, and team practices to improve forecasting skill without overfitting to a small question set.")),
  "Prediction Market Design": w(s("contract", "Market question", "Translate the forecast into a contract with clear payoff, resolution source, deadline, and treatment of cancellation or ambiguity."), s("participants", "Participation and incentives", "Define access, stake limits, incentives, information rules, and protections against manipulation or coercion."), s("mechanism", "Trading mechanism", "Choose market maker, order book, auction, or other mechanism and specify liquidity and price interpretation."), s("monitor", "Market quality", "Monitor participation concentration, liquidity, manipulation, information cascades, and whether prices reflect genuine independent information."), s("resolve", "Resolution and evaluation", "Resolve transparently, score market forecasts against outcomes, and analyze when market prices added value over simpler aggregation.")),
  "Wisdom-of-Crowds Aggregation": w(s("question", "Common question", "Ensure all participants answer the same well-specified question with the same information cutoff."), s("independence", "Preserve independence", "Collect judgments before group discussion and identify shared sources or coordination that reduce effective independence."), s("diversity", "Diversity and competence", "Assess whether the crowd contains relevant knowledge and genuinely different information rather than noise alone."), s("aggregate", "Aggregation rule", "Use a transparent statistic or model such as median, mean, trimmed mean, or weighted average appropriate to the judgment type."), s("audit", "Crowd audit", "Compare aggregate performance with individuals and benchmarks, checking correlation, herding, outliers, and domain-specific failure modes.")),
  "Independent Estimate Aggregation": w(s("task", "Estimate task", "Define the quantity, units, information set, and assumptions shared by all estimators."), s("independent", "Independent estimates", "Obtain estimates and uncertainty from each analyst before exposing others' answers or rationales."), s("dependencies", "Dependency check", "Identify common models, data, anchors, or organizational assumptions that make estimates less independent than they appear."), s("combine", "Combine estimates", "Apply a declared aggregation rule and compare mean, median, trimmed, or performance-weighted results where appropriate."), s("review", "Review dispersion", "Investigate extreme disagreement as information, not merely noise, and document whether reconciliation changes the aggregate.")),
  "Estimate-Talk-Estimate": w(s("first", "First estimate", "Have participants make and record independent estimates, uncertainty, and key assumptions before any discussion."), s("compare", "Reveal distribution", "Share the range and anonymized rationales so participants can see differences without status-driven advocacy."), s("talk", "Focused discussion", "Discuss the evidence and crux assumptions causing dispersion rather than negotiating toward a midpoint."), s("second", "Second independent estimate", "Have participants privately re-estimate after discussion so updates remain individually accountable."), s("aggregate", "Aggregate and learn", "Combine second-round estimates and record which arguments changed judgments and which disagreements persist.")),
  "Wideband Delphi": w(s("question", "Question and criteria", "Define the estimate or decision problem, units, assumptions, and acceptance criteria."), s("initial", "Anonymous initial estimates", "Collect independent estimates plus rationale before group interaction."), s("workshop", "Facilitated discussion", "Present the distribution and discuss major assumptions, evidence, and causes of divergence without forcing consensus."), s("reround", "Iterative re-estimation", "Repeat anonymous estimates and structured feedback for a bounded number of rounds or until a stopping rule is met."), s("result", "Result and dissent", "Aggregate the final round, retain the range and dissenting rationales, and document what changed across rounds.")),
  "Paired Comparison Elicitation": w(s("items", "Items", "Define the alternatives or attributes and the precise comparison criterion."), s("pairs", "Pairwise judgments", "Present pairs in a balanced order and ask which item better satisfies the criterion, optionally eliciting strength of preference."), s("coverage", "Comparison coverage", "Ensure enough pairs are judged to estimate an ordering while avoiding unnecessary respondent burden."), s("consistency", "Consistency and cycles", "Check transitivity, cycles, context effects, and inconsistent repeated pairs rather than silently forcing an order."), s("derive", "Derive priorities", "Convert comparisons into a ranking or scale with a stated method and report uncertainty or unresolved ties.")),
  "Rank-Order Elicitation": w(s("items", "Candidate items", "Define the items and the single criterion on which they must be ordered."), s("anchors", "Ordering anchors", "Clarify best, worst, ties, incomparability, and whether partial rankings are allowed before elicitation."), s("rank", "Independent rank order", "Have experts rank items without seeing peers' rankings and capture reasons for adjacent distinctions."), s("compare", "Aggregate rankings", "Use a transparent rank aggregation method and inspect disagreement, ties, and sensitivity to the chosen rule."), s("interpret", "Interpretation", "Separate ordinal priority from magnitude of difference and identify items needing richer scoring or additional evidence.")),
  "Confidence Interval Elicitation": w(s("quantity", "Quantity", "Define the uncertain quantity, units, reference class, and conditioning information."), s("center", "Central estimate", "Elicit a central or median estimate with reasoning before or between bound judgments according to the chosen protocol."), s("bounds", "Interval bounds", "Elicit bounds for a specified coverage probability and explicitly ask what outcomes would fall outside the interval."), s("challenge", "Overconfidence challenge", "Use counterexamples, base rates, decomposition, or equivalent-bin checks to test whether the interval is implausibly narrow."), s("record", "Final interval", "Record the final probability coverage, bounds, assumptions, and whether the interval is symmetric or skewed.")),
  "Consensus Mapping": w(s("question", "Question", "Define the proposition, forecast, or decision on which agreement and disagreement will be mapped."), s("positions", "Individual positions", "Collect independent judgments, confidence, key reasons, and definitions before discussing convergence."), s("clusters", "Position clusters", "Group genuinely similar positions and distinguish agreement on conclusion from agreement on evidence or reasoning."), s("cruxes", "Consensus and cruxes", "Map points of agreement, partial agreement, factual disputes, value differences, and unresolved causal or probabilistic cruxes."), s("report", "Report structure", "Present the consensus area alongside material minority views and the evidence that could move each cluster.")),
  "Disagreement Decomposition": w(s("disagreement", "Observed disagreement", "State the differing judgments precisely, including probabilities, scope, timing, or recommended actions."), s("components", "Decompose causes", "Test whether disagreement comes from different data, source trust, definitions, models, causal assumptions, priors, values, or thresholds."), s("counterfactual", "Swap assumptions", "Ask how each analyst's conclusion would change if they adopted the other's key inputs or assumptions."), s("residual", "Residual disagreement", "Separate disagreements that can be resolved with facts or clarification from deep model, value, or uncertainty differences."), s("next", "Resolution plan", "Identify the highest-value evidence, experiment, or decision rule for reducing disagreement while preserving unresolved dissent.")),
};

export const EXPERT_SPECIFIC_CATALOG_WORKFLOW_COUNT = Object.keys(EXPERT_SPECIFIC_WORKFLOWS).length;
export const hasExpertSpecificCatalogWorkflow = (name: string): boolean => Boolean(EXPERT_SPECIFIC_WORKFLOWS[name]);
export const expertSpecificCatalogWorkflow = (name: string): TechniqueStepDefinition[] | undefined => EXPERT_SPECIFIC_WORKFLOWS[name]?.map((item) => ({ ...item }));
