import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";
const s=(id:string,title:string,prompt:string,responseKind:TechniqueResponseKind="long-text"):TechniqueStepDefinition=>({id,title,prompt,responseKind}); const w=(...steps:TechniqueStepDefinition[])=>steps;
export const QUALITY_SPECIFIC_WORKFLOWS:Record<string,TechniqueStepDefinition[]>={
  "DMADV":w(s("define","Define need","Define the customer or mission need, scope, constraints, and success measures."),s("measure","Measure needs","Translate needs into measurable critical-to-quality characteristics and baseline capability."),s("analyze","Analyze concepts","Compare design concepts against requirements, risks, and tradeoffs."),s("design","Design solution","Develop the preferred design, interfaces, controls, and verification criteria."),s("verify","Verify","Test the design against requirements and document residual gaps.")),
  "Kaizen Event Analysis":w(s("scope","Improvement scope","Define the process, problem, team, and short event boundary."),s("current","Current state","Map work, delay, defects, handoffs, and waste using direct evidence."),s("causes","Causes","Identify root causes and constraints rather than only symptoms."),s("changes","Rapid countermeasures","Select and trial small changes with owners and expected effects."),s("follow","Sustainment","Check results, standardize gains, and assign follow-up actions.")),
  "Process Capability Analysis":w(s("ctq","Critical characteristic","Define the measurable characteristic, specification limits, and process conditions."),s("stability","Stability first","Check whether the process is statistically stable before interpreting capability."),s("indices","Capability indices","Estimate suitable capability/performance indices and inspect distribution assumptions."),s("causes","Sources of variation","Identify common and special causes that limit capability."),s("action","Capability judgment","State whether the process can meet requirements and what improvement is needed.")),
  "Control Chart Analysis":w(s("measure","Measure and subgroup","Define the metric, sampling cadence, subgroup logic, and chart type."),s("limits","Control limits","Establish limits from stable baseline data rather than specification limits."),s("signals","Signals","Identify points, runs, trends, shifts, or cycles that indicate special causes."),s("investigate","Investigate causes","Link signals to process conditions, changes, and plausible causes."),s("respond","Response plan","Define actions for special causes and rules for recalculating limits.")),
  "Measurement System Analysis":w(s("purpose","Measurement purpose","Define the characteristic, decision use, range, and required precision."),s("system","Measurement system","Map instruments, operators, methods, environment, software, and reference standards."),s("error","Error components","Assess bias, linearity, stability, repeatability, and reproducibility as relevant."),s("adequacy","Adequacy","Compare measurement variation with process and tolerance variation."),s("improve","Improvement","Correct dominant measurement errors and define revalidation.")),
  "Gage R&R":w(s("study","Study design","Choose parts, appraisers, trials, randomization, and crossed or nested design."),s("collect","Repeated measurements","Collect blinded repeated measurements across representative parts."),s("variance","Variation components","Separate repeatability, reproducibility, part-to-part, and interaction effects."),s("judge","Measurement adequacy","Compare gage variation with total and tolerance variation using context-appropriate thresholds."),s("improve","Correct and repeat","Identify instrument, method, fixture, or training changes and rerun the study.")),
  "Taguchi Method":w(s("objective","Quality objective","Define response variables, target behavior, factors, levels, and noise factors."),s("array","Experimental array","Select an orthogonal array or robust design covering the important factors efficiently."),s("run","Run experiment","Execute trials consistently and preserve noise conditions and replication logic."),s("sn","Robustness analysis","Use signal-to-noise and factor effects to identify settings resistant to noise."),s("confirm","Confirmation run","Verify the predicted robust setting and quantify improvement.")),
  "Poka-Yoke Analysis":w(s("failure","Error or defect","Define the human or process error and the defect or harm it can create."),s("mechanism","Error mechanism","Identify when, where, and why the error becomes possible."),s("concepts","Mistake-proofing concepts","Generate prevention, detection, constraint, sequencing, and forcing-function options."),s("evaluate","Evaluate","Prefer simple controls that act at the source and cannot be bypassed silently."),s("verify","Verify in use","Test the control under realistic variation and monitor unintended workarounds.")),
  "Standard Work Analysis":w(s("scope","Work scope","Define the process boundary, demand, takt, and quality/safety requirements."),s("observe","Observed work","Capture actual sequence, time, inventory, movement, and variation at the workplace."),s("standard","Standard sequence","Define the best current sequence, expected time, and standard work-in-process."),s("gaps","Gap analysis","Compare actual work with the standard and distinguish bad standards from noncompliance."),s("maintain","Maintain and improve","Assign ownership, visual controls, training, and a method for updating the standard.")),
  "Takt Time Analysis":w(s("demand","Demand basis","Define customer demand, period, product mix, and available production time."),s("takt","Calculate takt","Compute the required production rhythm using consistent units and realistic availability."),s("compare","Compare cycle times","Compare station cycle times, changeovers, uptime, and variability with takt."),s("balance","Balance work","Identify overload, underload, batching, and staffing or sequencing changes."),s("monitor","Monitor","Define triggers for demand changes, instability, or rebalance needs.")),
  "Bottleneck Analysis":w(s("flow","System flow","Define the process, demand, throughput unit, and major resources."),s("capacity","Capacity by step","Estimate effective capacity, utilization, queues, downtime, and variability at each constraint candidate."),s("constraint","Identify constraint","Determine which resource truly limits throughput under current conditions."),s("exploit","Exploit and subordinate","Protect the constraint and align upstream/downstream work to it."),s("elevate","Elevate and recheck","Increase constraint capacity if needed, then reassess because the bottleneck may move.")),
  "Current Reality Tree":w(s("effects","Undesirable effects","List observed problems and validate that they are real and meaningfully connected."),s("causality","Causal links","Build sufficiency-based if-then links and expose assumptions in each connection."),s("core","Core problem","Identify the small set of root conditions generating many undesirable effects."),s("challenge","Challenge logic","Test alternative explanations, missing causes, circularity, and necessary-condition claims."),s("focus","Improvement focus","Select root conditions whose change would remove the most downstream effects.")),
  "Future Reality Tree":w(s("change","Proposed change","State the intervention or injection intended to resolve a core problem."),s("effects","Desired effects","Map expected beneficial consequences using explicit causal links."),s("negatives","Negative branches","Search for harmful side effects, new constraints, and unintended reinforcing loops."),s("trim","Trim negatives","Add preventive or compensating actions for credible negative branches."),s("verify","Implementation logic","Define assumptions and indicators that would confirm or falsify the future-state logic.")),
  "Evaporating Cloud":w(s("conflict","Conflict","State the two incompatible actions or positions and the common objective they are meant to serve."),s("needs","Underlying needs","Identify the need each side believes its action satisfies."),s("assumptions","Assumptions","Expose assumptions linking each action to its need and creating the apparent incompatibility."),s("challenge","Challenge assumptions","Test which assumptions can be invalidated, reframed, or satisfied differently."),s("injection","Win-win injection","Design an action that protects both legitimate needs and define how to test it.")),
};
export const QUALITY_SPECIFIC_CATALOG_WORKFLOW_COUNT=Object.keys(QUALITY_SPECIFIC_WORKFLOWS).length;
export const hasQualitySpecificCatalogWorkflow=(name:string)=>Boolean(QUALITY_SPECIFIC_WORKFLOWS[name]);
export const qualitySpecificCatalogWorkflow=(name:string)=>QUALITY_SPECIFIC_WORKFLOWS[name]?.map(x=>({...x}));