import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";

const s = (id: string, title: string, prompt: string, responseKind: TechniqueResponseKind = "long-text"): TechniqueStepDefinition => ({ id, title, prompt, responseKind });
const w = (...steps: TechniqueStepDefinition[]) => steps;

export const CAUSAL_SPECIFIC_WORKFLOWS: Record<string, TechniqueStepDefinition[]> = {
  "Backdoor Criterion Review": w(s("effect", "Causal effect", "Define exposure, outcome, population, and causal contrast."), s("graph", "Candidate causal graph", "Map plausible common causes, mediators, colliders, and descendants before choosing controls."), s("paths", "Backdoor paths", "Identify noncausal paths entering the exposure through an incoming arrow and determine which remain open."), s("adjust", "Adjustment set", "Select a sufficient set that blocks relevant backdoor paths without conditioning on mediators or colliders."), s("assumptions", "Identification assumptions", "State unmeasured-confounding, measurement, positivity, and model assumptions that remain after adjustment.")),
  "Front-Door Criterion Review": w(s("structure", "Mediator structure", "Define exposure, mediator, outcome, and the mechanism that could support front-door identification."), s("conditions", "Criterion conditions", "Check whether the mediator intercepts the exposure effect, exposure-mediator confounding is controlled, and mediator-outcome backdoor paths are blocked."), s("evidence", "Evidence for assumptions", "Assess whether those structural assumptions are substantively defensible rather than merely statistically convenient."), s("estimate", "Identification plan", "Specify how exposure-to-mediator and mediator-to-outcome relationships would be estimated and combined."), s("limits", "Failure modes", "Identify direct effects, hidden confounding, measurement error, or selection that would invalidate the design.")),
  "Inverse Probability Weighting": w(s("target", "Target estimand", "Define treatment or exposure, outcome, population, and the causal estimand to be weighted."), s("propensity", "Assignment model", "Estimate treatment or censoring probabilities using pre-exposure covariates that address exchangeability."), s("weights", "Construct weights", "Calculate stabilized or unstabilized weights and inspect extreme values, overlap, and positivity."), s("balance", "Weighted balance", "Check whether weighting balances covariates and whether a small number of observations dominate the pseudo-population."), s("estimate", "Effect and robustness", "Estimate the weighted effect and report sensitivity to truncation, model specification, and residual confounding.")),
  "Instrumental Variables": w(s("instrument", "Candidate instrument", "Define the instrument, exposure, outcome, population, and causal effect of interest."), s("relevance", "Relevance", "Show that the instrument materially shifts the exposure in the target population."), s("independence", "Independence and exclusion", "Assess whether the instrument is independent of outcome causes and affects the outcome only through the exposure."), s("estimate", "IV estimand", "Specify the estimation strategy and the population whose effect is identified, including monotonicity assumptions when relevant."), s("threats", "Validity threats", "Test weak-instrument risk, direct pathways, selection, heterogeneous effects, and alternative explanations for the instrument-outcome association.")),
  "Matching Analysis": w(s("question", "Causal comparison", "Define treated and comparison conditions, outcome, target population, and estimand."), s("covariates", "Pre-treatment covariates", "Select confounders measured before treatment and avoid matching on post-treatment variables or colliders."), s("match", "Matching design", "Choose distance, propensity, caliper, exact, or other matching rules and define replacement and ratio choices."), s("diagnostics", "Balance and overlap", "Evaluate covariate balance, common support, discarded cases, and sensitivity to alternate matching specifications."), s("effect", "Matched effect", "Estimate the effect in the matched sample and state limits from residual confounding, representativeness, and matching uncertainty.")),
  "Natural Experiment Analysis": w(s("shock", "Exogenous variation", "Identify the event, rule, boundary, timing, or process that creates plausibly exogenous exposure variation."), s("assignment", "Assignment mechanism", "Explain why units on different sides of the variation should be comparable apart from exposure."), s("threats", "Alternative pathways", "Test anticipation, sorting, concurrent shocks, spillovers, differential measurement, and selective attrition."), s("design", "Identification design", "Choose the comparison strategy appropriate to the natural experiment and specify falsification or placebo tests."), s("inference", "Causal inference", "State the effect, population to which it applies, and the assumptions required to interpret the result causally.")),
  "Randomized Controlled Trial Design": w(s("question", "Trial question", "Define population, intervention, comparator, outcomes, estimand, and follow-up horizon."), s("randomize", "Randomization", "Specify assignment unit, allocation method, concealment, stratification or blocking, and contamination risks."), s("measure", "Outcomes and protocol", "Predefine primary and secondary outcomes, measurement schedule, adherence, missing-data handling, and analysis population."), s("power", "Sample size and power", "Set effect size assumptions, variance, attrition, clustering, and error rates needed for a defensible sample size."), s("analysis", "Analysis and integrity", "Specify intention-to-treat or other estimands, protocol deviations, stopping rules, multiplicity, and transparent reporting.")),
  "A/B Test Design": w(s("decision", "Decision and metric", "Define the product or policy decision, treatment contrast, primary metric, guardrails, and decision threshold."), s("unit", "Randomization unit", "Choose user, session, cluster, or other assignment unit and address interference, repeated exposure, and contamination."), s("sample", "Sample and duration", "Estimate required sample size and runtime from baseline rates, minimum detectable effect, variance, traffic, and novelty or seasonality concerns."), s("analysis", "Analysis plan", "Predefine exclusions, metric transformations, multiplicity handling, sequential looks, and segment analyses before inspecting outcomes."), s("decisionrule", "Decision rule", "Interpret statistical and practical significance together and record rollout, rollback, or further-test conditions.")),
  "Factorial Experiment Design": w(s("factors", "Factors and levels", "Define experimental factors, levels, outcomes, constraints, and interactions that matter."), s("design", "Factorial structure", "Choose full or fractional factorial structure and document aliasing, blocking, randomization, and replication."), s("conduct", "Execution controls", "Standardize treatment delivery, measurement, and assignment while tracking deviations and missing runs."), s("effects", "Main and interaction effects", "Estimate main effects and interactions without interpreting a main effect in isolation when strong interactions exist."), s("optimize", "Design insight", "Use effect patterns to identify promising combinations, nonlinearities requiring follow-up, and settings robust to noise.")),
  "Quasi-Experimental Design": w(s("question", "Causal question", "Define the intervention or exposure, outcome, target population, and counterfactual of interest."), s("design", "Identification strategy", "Choose a credible nonrandom design such as interrupted time series, regression discontinuity, matched comparison, synthetic control, or difference-in-differences."), s("assumptions", "Design assumptions", "State the assumptions that create comparability and identify observable implications that can be tested."), s("threats", "Validity threats", "Assess selection, history, maturation, regression to the mean, spillovers, measurement changes, and model dependence."), s("robust", "Robustness and inference", "Apply placebo, falsification, sensitivity, or alternate-specification checks and bound the causal conclusion accordingly.")),
  "Mediation Analysis": w(s("model", "Mediation model", "Define exposure, proposed mediator, outcome, timing, and the causal mechanism being tested."), s("paths", "Path assumptions", "Identify exposure-mediator, mediator-outcome, and direct pathways plus confounders of each relationship."), s("effects", "Effect decomposition", "Estimate total, direct, and indirect effects using an approach appropriate to scale and interaction structure."), s("sensitivity", "Mediator assumptions", "Assess mediator-outcome confounding, post-treatment confounding, measurement error, and sensitivity to alternate mediator definitions."), s("interpret", "Mechanism inference", "State what the mediation results do and do not establish about mechanism, especially when temporal or causal assumptions are weak.")),
  "Moderation Analysis": w(s("effect", "Effect of interest", "Define the relationship or treatment effect and the variable hypothesized to modify it."), s("interaction", "Interaction specification", "Specify the interaction on a meaningful scale and distinguish effect modification from confounding or subgroup description."), s("support", "Data support", "Check sample size, overlap, distribution of the moderator, functional form, and whether categories were chosen post hoc."), s("estimate", "Conditional effects", "Estimate and visualize effects across substantively meaningful moderator values with uncertainty."), s("interpret", "Heterogeneity judgment", "Assess robustness, multiplicity, plausibility, and whether observed heterogeneity warrants different decisions or further study.")),
  "Mechanism Mapping": w(s("claim", "Causal claim", "State the cause, outcome, context, and proposed mechanism that connects them."), s("steps", "Mechanism sequence", "Decompose the mechanism into entities, activities, state changes, and intermediate links in temporal or logical order."), s("evidence", "Evidence by link", "Attach supporting, contradicting, and missing evidence to each mechanism link and record provenance."), s("rivals", "Rival mechanisms", "Identify alternate pathways, shortcuts, feedbacks, and common causes that could produce similar observations."), s("tests", "Mechanism tests", "Define observations or interventions that would discriminate among mechanisms and identify the weakest link in the current chain.")),
  "Contribution Analysis": w(s("theory", "Theory of change", "Define the intervention, expected causal pathway, contextual conditions, and outcomes."), s("evidence", "Contribution evidence", "Assemble evidence for implementation, intermediate results, final outcomes, and each causal link in the theory."), s("alternatives", "Alternative explanations", "Identify other programs, external events, selection effects, secular trends, and contextual factors that could explain the results."), s("story", "Contribution story", "Assess whether the observed pattern is consistent with the theory and stronger than plausible alternative explanations without claiming attribution beyond the design."), s("strengthen", "Strengthen the inference", "Identify additional evidence, comparisons, process observations, or tests that would most improve the contribution claim.")),
};

export const CAUSAL_SPECIFIC_CATALOG_WORKFLOW_COUNT = Object.keys(CAUSAL_SPECIFIC_WORKFLOWS).length;
export const hasCausalSpecificCatalogWorkflow = (name: string): boolean => Boolean(CAUSAL_SPECIFIC_WORKFLOWS[name]);
export const causalSpecificCatalogWorkflow = (name: string): TechniqueStepDefinition[] | undefined => CAUSAL_SPECIFIC_WORKFLOWS[name]?.map((item) => ({ ...item }));
