import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";

const s = (id: string, title: string, prompt: string, responseKind: TechniqueResponseKind = "long-text"): TechniqueStepDefinition => ({ id, title, prompt, responseKind });
const w = (...steps: TechniqueStepDefinition[]) => steps;

export const FRAMING_SPECIFIC_WORKFLOWS: Record<string, TechniqueStepDefinition[]> = {
  "Customer Checklist": w(s("customer", "Customer and decision", "Identify the customer, decision, deadline, authorities, and consequences of being wrong."), s("need", "Need versus request", "Separate the customer's stated request from the underlying decision need, uncertainties, and constraints."), s("scope", "Scope and terms", "Clarify actors, geography, time horizon, definitions, assumptions, and exclusions that bound the analysis."), s("product", "Product requirements", "Specify required depth, confidence language, sourcing, format, coordination, and delivery timing."), s("confirm", "Confirm understanding", "Restate the analytic task in decision-relevant terms and record unresolved questions or scope risks.")),
  "Decomposition Tree": w(s("root", "Root problem", "State the top-level problem or question as a single bounded node."), s("branches", "Primary branches", "Break the root into collectively useful subproblems using one clear decomposition logic.", "list"), s("subbranches", "Subdivide", "Continue decomposing until leaf questions are answerable with evidence or a defined analytic method."), s("coverage", "Coverage and overlap", "Check for missing branches, double counting, mixed levels, and dependencies that violate the tree structure."), s("prioritize", "Prioritize leaves", "Identify which leaf questions are decision-critical, uncertain, time-sensitive, or prerequisite to other branches.")),
  "Logic Tree": w(s("question", "Question", "Define the decision or explanatory question the tree must resolve."), s("logic", "Branching rule", "Choose a consistent logical split such as causes, options, conditions, or necessary components."), s("tree", "Build the tree", "Decompose each branch into mutually intelligible subquestions while preserving the chosen logic."), s("test", "Logic test", "Check whether branches are exhaustive enough for the purpose, avoid hidden overlap, and expose assumptions at branch points."), s("use", "Analytic use", "Assign evidence, methods, owners, or judgments to terminal branches and identify where unresolved logic blocks the conclusion.")),
  "Issue Tree": w(s("issue", "Central issue", "Frame the central issue as a question whose answer would materially advance the decision."), s("drivers", "Issue branches", "Break it into the few major issues that jointly determine the answer.", "list"), s("questions", "Subquestions", "Convert each branch into specific answerable questions and separate factual, causal, and evaluative questions."), s("evidence", "Evidence mapping", "Map available evidence and gaps to each terminal question so unsupported branches are visible."), s("synthesis", "Synthesis path", "Define how answers to the branches will recombine into the top-level judgment and where dependencies or tradeoffs remain.")),
  "MECE Decomposition": w(s("problem", "Problem", "State the problem and the purpose of decomposing it."), s("dimensions", "Candidate dimensions", "Generate plausible ways to partition the problem by actor, stage, cause, geography, function, time, or another coherent dimension.", "list"), s("partition", "MECE partition", "Choose a partition whose categories minimize overlap while covering the decision-relevant space."), s("exceptions", "Exceptions and edge cases", "Test ambiguous cases, interactions, and omitted categories rather than forcing reality into a falsely clean partition."), s("apply", "Apply the partition", "Use the categories to organize evidence or workstreams and record where non-MECE interactions must be handled explicitly.")),
  "Question Decomposition": w(s("question", "Original question", "State the question exactly and identify the decision or judgment it is intended to support."), s("terms", "Clarify terms", "Define ambiguous terms, actors, units, time horizon, comparison class, and implied thresholds."), s("subquestions", "Subquestions", "Break the question into factual, causal, comparative, forecasting, and evaluative subquestions as needed.", "list"), s("dependencies", "Dependencies", "Identify which subquestions must be answered first and which can be analyzed independently or in parallel."), s("coverage", "Coverage check", "Confirm that answering the subquestions would actually resolve the original question and identify residual uncertainty.")),
  "Scope Boundary Matrix": w(s("problem", "Problem and purpose", "Define the analytic problem and why boundary choices matter to the result."), s("dimensions", "Boundary dimensions", "List scope dimensions such as actors, geography, time, systems, populations, evidence types, and levels of analysis.", "list"), s("matrix", "In / out / uncertain", "For each dimension, record what is included, excluded, and intentionally left uncertain, with rationale."), s("effects", "Boundary effects", "Test how plausible alternative boundaries would change evidence, causal explanations, stakeholders, or conclusions."), s("record", "Working boundary", "Adopt the narrowest defensible boundary for the task while documenting exclusions that could materially change the judgment.")),
  "Stakeholder Question Matrix": w(s("stakeholders", "Stakeholders", "List the actors who decide, influence, implement, experience, or possess critical information about the issue.", "list"), s("needs", "Questions by stakeholder", "For each stakeholder, identify the questions they need answered and the questions analysts need answered about them."), s("differences", "Differences in perspective", "Compare incentives, information, definitions of success, and risk tolerances that make the questions diverge."), s("gaps", "Question gaps", "Identify decision-relevant questions with no clear owner, source, or analytic path and flag conflicting requirements."), s("prioritize", "Priority question set", "Select the smallest cross-stakeholder question set that covers the decision without collapsing important disagreements.")),
  "Problem Statement Canvas": w(s("situation", "Situation", "Describe the observed situation and the decision context without embedding a preferred cause or solution."), s("gap", "Problem gap", "State the difference between the current condition and the desired or acceptable condition, including scale and timing."), s("affected", "Affected actors and consequences", "Identify who is affected, how, and what material consequences follow if the gap persists."), s("unknowns", "Knowns, assumptions, unknowns", "Separate established facts from assumptions and the uncertainties that prevent a confident diagnosis."), s("statement", "Working problem statement", "Write a concise, testable problem statement with scope, evidence basis, and explicit exclusions.")),
  "Frame Analysis": w(s("artifact", "Frame source", "Identify the statement, product, narrative, policy, or analytic formulation whose frame is being examined."), s("elements", "Frame elements", "Identify problem definition, causal attribution, moral or evaluative language, actors, boundaries, metaphors, and implied remedies."), s("foreground", "Foreground and background", "What does the frame emphasize, normalize, exclude, or render difficult to see?"), s("alternatives", "Alternative frames", "Construct materially different frames from other actors, disciplines, scales, or causal assumptions.", "list"), s("impact", "Analytic impact", "Assess how the chosen frame changes evidence selection, hypotheses, confidence, and policy or decision implications.")),
  "Frame Shifting": w(s("current", "Current frame", "State the current formulation and the assumptions or habitual categories it privileges."), s("axes", "Shift dimensions", "Choose deliberate shifts in actor, scale, time horizon, geography, system boundary, causal direction, or objective.", "list"), s("reframes", "Generate shifted frames", "Reframe the issue along several selected dimensions without judging them immediately.", "list"), s("discoveries", "Newly visible evidence and options", "For each shifted frame, identify explanations, stakeholders, evidence, risks, or actions that become visible."), s("selection", "Frame portfolio", "Retain the frames that add distinct analytic value and note which conclusions depend heavily on one framing choice.")),
  "Actor-Interest Matrix": w(s("actors", "Actors", "Identify relevant actors at the appropriate level of aggregation and distinguish formal entities from internal factions where necessary.", "list"), s("interests", "Interests and objectives", "For each actor, record desired outcomes, protected interests, fears, red lines, and time horizons."), s("means", "Influence and constraints", "Assess resources, authorities, dependencies, alliances, vulnerabilities, and constraints that shape each actor's choices."), s("conflicts", "Alignment and conflict", "Compare where interests align, conflict, or are conditionally compatible and identify bargaining or escalation points."), s("implications", "Analytic implications", "Use the matrix to derive likely coalitions, incentives, leverage points, and indicators that actor priorities are changing.")),
  "Concept Mapping": w(s("focus", "Focus question", "Define the bounded question or domain the concept map is intended to clarify."), s("concepts", "Key concepts", "List the important entities, ideas, variables, categories, and processes without prematurely arranging them.", "list"), s("relations", "Labeled relationships", "Connect concepts with explicit relationship labels so the map captures propositions rather than mere proximity."), s("structure", "Hierarchy and cross-links", "Identify higher-order concepts, subordinate concepts, cross-links, feedbacks, and concepts that bridge otherwise separate clusters."), s("review", "Map review", "Check for missing concepts, ambiguous labels, circular definitions, and relationships that are asserted without evidence.")),
  "Process Mapping": w(s("scope", "Process scope", "Define the process start, end, customer or mission outcome, and level of detail."), s("steps", "Process steps", "Map major activities, decisions, handoffs, inputs, outputs, and responsible actors in sequence."), s("flows", "Information and material flows", "Record what information, data, authority, or material moves between steps and where queues or feedback occur."), s("exceptions", "Exceptions and failure paths", "Identify rework, alternate paths, informal workarounds, bottlenecks, and conditions that cause the process to diverge from the nominal flow."), s("insight", "Analytic insight", "Identify dependencies, control points, delays, vulnerabilities, and collection opportunities revealed by the mapped process.")),
};

export const FRAMING_SPECIFIC_CATALOG_WORKFLOW_COUNT = Object.keys(FRAMING_SPECIFIC_WORKFLOWS).length;
export const hasFramingSpecificCatalogWorkflow = (name: string): boolean => Boolean(FRAMING_SPECIFIC_WORKFLOWS[name]);
export const framingSpecificCatalogWorkflow = (name: string): TechniqueStepDefinition[] | undefined => FRAMING_SPECIFIC_WORKFLOWS[name]?.map((item) => ({ ...item }));
