import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";
const s=(id:string,title:string,prompt:string,responseKind:TechniqueResponseKind="long-text"):TechniqueStepDefinition=>({id,title,prompt,responseKind}); const w=(...steps:TechniqueStepDefinition[])=>steps;
export const GEOSPATIAL_SPECIFIC_WORKFLOWS:Record<string,TechniqueStepDefinition[]>={
  "Kernel Density Estimation":w(s("events","Events and extent","Define event type, study area, time window, coordinate quality, and population-at-risk context."),s("bandwidth","Kernel and bandwidth","Choose kernel, bandwidth, cell size, and edge treatment with substantive justification."),s("surface","Density surface","Generate the density estimate and inspect sensitivity to bandwidth and resolution."),s("baseline","Baseline comparison","Compare density with exposure or opportunity where raw event concentration could mislead."),s("interpret","Interpretation","Identify robust concentration patterns without treating smoothed density as causal risk.")),
  "Spatial Autocorrelation Analysis":w(s("variable","Variable and units","Define the measured variable, spatial units, time period, and data quality."),s("weights","Spatial weights","Specify contiguity, distance, k-nearest-neighbor, or other neighborhood logic."),s("global","Global pattern","Assess whether similar or dissimilar values cluster overall."),s("local","Local structure","Inspect local clusters and spatial outliers where relevant, accounting for multiple testing."),s("limits","Interpretation","Test sensitivity to scale, boundaries, weights, and spatial nonstationarity.")),
  "Moran's I Analysis":w(s("variable","Variable and geography","Define the variable, areal units, transformations, and study extent."),s("weights","Weight matrix","Construct and justify spatial weights and row standardization."),s("statistic","Moran's I","Calculate the statistic and compare it with an appropriate randomization or analytical expectation."),s("significance","Significance and diagnostics","Assess permutation significance and inspect influential units or nonstationarity."),s("interpret","Interpretation","Explain whether the pattern indicates positive, negative, or negligible autocorrelation and its limits.")),
  "Getis-Ord Gi* Analysis":w(s("measure","Measure and units","Define the attribute, spatial units, time window, and any rate standardization."),s("neighbors","Neighborhood definition","Choose distance or contiguity parameters that reflect the process being studied."),s("gi","Local Gi*","Calculate local hot- and cold-spot statistics for each unit."),s("significance","Statistical control","Assess z-scores or permutation results and control for multiple comparisons where appropriate."),s("interpret","Hot-spot interpretation","Identify stable clusters and test sensitivity to scale and neighborhood choices.")),
  "Viewshed Analysis":w(s("observer","Observer and target","Define observer locations/heights, targets, terrain model, and visibility question."),s("terrain","Surface assumptions","Check DEM resolution, curvature, vegetation/buildings, and vertical accuracy."),s("compute","Line-of-sight computation","Calculate visible and hidden areas under stated parameters."),s("sensitivity","Sensitivity","Vary heights, surface assumptions, and terrain resolution to identify fragile results."),s("implications","Operational implications","Translate visibility into observation, concealment, communications, or siting implications without overstating certainty.")),
  "Least-Cost Path Analysis":w(s("origin","Origins and destinations","Define start/end points, movement mode, and what 'cost' represents."),s("surface","Cost surface","Construct traversability or friction values from terrain, infrastructure, risk, rules, and barriers."),s("path","Least-cost paths","Compute candidate routes and cumulative costs."),s("alternatives","Alternative paths","Inspect near-optimal routes and sensitivity to weights, resolution, and barriers."),s("interpret","Interpretation","Use paths as constrained hypotheses about movement rather than predictions of actual behavior.")),
  "Spatial Network Analysis":w(s("network","Network definition","Define nodes, links, direction, impedance, restrictions, and geographic accuracy."),s("measures","Network measures","Select shortest path, accessibility, centrality, service area, flow, or resilience measures appropriate to the question."),s("calculate","Calculate structure","Analyze routes, connectivity, bottlenecks, and reachability."),s("scenarios","Disruption scenarios","Test closures, capacity loss, alternative origins, or demand shifts."),s("interpret","Operational meaning","Explain what network structure implies while distinguishing topology from real-world capacity and behavior.")),
  "Site Suitability Analysis":w(s("objective","Siting objective","Define the facility/activity, constraints, stakeholders, and success criteria."),s("criteria","Criteria layers","Select exclusion and suitability factors with defensible units, thresholds, and provenance."),s("standardize","Standardize and weight","Transform criteria to comparable scales and justify weights or dominance rules."),s("combine","Suitability model","Combine layers, identify feasible areas, and preserve hard constraints."),s("sensitivity","Sensitivity and validation","Test alternative weights/thresholds and compare candidate sites with ground truth or expert review.")),
  "Spatial Change Detection":w(s("datasets","Comparable datasets","Define dates, sensors/sources, coordinate systems, resolution, and classification schemes."),s("align","Alignment and normalization","Correct registration, scale, illumination, classification, and seasonal differences that could mimic change."),s("detect","Detect change","Apply a suitable pixel-, object-, feature-, or classification-based comparison."),s("validate","Validate","Estimate false change and missed change using reference data or manual review."),s("interpret","Interpretation","Separate genuine spatial change from measurement artifacts and identify causal hypotheses requiring further evidence.")),
};
export const GEOSPATIAL_SPECIFIC_CATALOG_WORKFLOW_COUNT=Object.keys(GEOSPATIAL_SPECIFIC_WORKFLOWS).length;
export const hasGeospatialSpecificCatalogWorkflow=(name:string)=>Boolean(GEOSPATIAL_SPECIFIC_WORKFLOWS[name]);
export const geospatialSpecificCatalogWorkflow=(name:string)=>GEOSPATIAL_SPECIFIC_WORKFLOWS[name]?.map(x=>({...x}));