import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";
const s=(id:string,title:string,prompt:string,responseKind:TechniqueResponseKind="long-text"):TechniqueStepDefinition=>({id,title,prompt,responseKind}); const w=(...steps:TechniqueStepDefinition[])=>steps;
export const QUALITATIVE_SPECIFIC_WORKFLOWS: Record<string, TechniqueStepDefinition[]> = {
"Qualitative Content Analysis":w(s("question","Analytic question","Define the corpus, unit of analysis, and whether categories are inductive or deductive."),s("codebook","Coding frame","Develop categories with definitions, inclusion rules, and examples."),s("code","Systematic coding","Apply the frame consistently while preserving context and ambiguous cases."),s("compare","Pattern comparison","Compare frequencies and meanings across cases or groups without reducing interpretation to counts."),s("interpret","Interpretation","Explain dominant and deviant patterns with traceable examples and limits.")),
"Grounded Theory Coding":w(s("focus","Phenomenon","Define the substantive area without imposing a finished theory."),s("initial","Initial coding","Code actions and processes closely from the data."),s("constant","Constant comparison","Compare incidents, codes, and cases continuously to refine categories."),s("theoretical","Theoretical coding","Relate mature categories into an explanatory process or model."),s("saturation","Saturation and memoing","Document theoretical memos, negative cases, and where additional data stop adding conceptual value.")),
"Open Coding":w(s("data","Data segment","Define the corpus and coding unit."),s("fracture","Open coding","Break data into discrete concepts using close, descriptive or process-oriented labels."),s("compare","Constant comparison","Compare incidents for similarities and differences."),s("categories","Category formation","Group related codes while preserving variation."),s("memo","Analytic memos","Record emerging questions, relationships, and sampling needs.")),
"Axial Coding":w(s("categories","Core categories","Select categories developed from earlier coding."),s("conditions","Conditions","Identify causal, contextual, and intervening conditions around each category."),s("actions","Actions and interactions","Map strategies or responses associated with the category."),s("consequences","Consequences","Trace outcomes and feedback from those actions."),s("integrate","Relational model","Integrate categories into a coherent explanatory structure and test it against cases.")),
"Selective Coding":w(s("core","Core category","Identify the category with greatest explanatory reach and analytic relevance."),s("relate","Relate categories","Connect major categories systematically to the core category."),s("validate","Validate relationships","Test proposed links against data, including negative cases."),s("fill","Fill category gaps","Target underdeveloped relationships with additional coding or sampling."),s("theory","Integrate theory","Produce a parsimonious theoretical account while retaining boundary conditions.")),
"Constant Comparative Method":w(s("units","Comparison units","Define incidents, cases, groups, or periods to compare."),s("compare","Within-category comparison","Compare each new incident with prior coded incidents."),s("differentiate","Differentiate categories","Split, merge, and refine categories based on meaningful variation."),s("relations","Compare relations","Examine how categories co-vary across contexts and cases."),s("saturation","Theoretical saturation","State which categories are stable and where additional comparison is still needed.")),
"Narrative Analysis":w(s("stories","Narrative corpus","Define narrators, audience, setting, and the stories or episodes under study."),s("structure","Narrative structure","Analyze sequence, turning points, plot, temporality, and positioning."),s("voice","Voice and perspective","Examine identity, agency, omissions, and audience-oriented presentation."),s("compare","Cross-narrative comparison","Compare recurring plots, contradictions, and contextual differences."),s("interpret","Narrative interpretation","Explain what the narratives accomplish socially or analytically without treating them as transparent fact reports.")),
"Conversation Analysis":w(s("interaction","Interaction corpus","Define naturally occurring interaction and transcription conventions."),s("sequence","Sequential organization","Examine turn-taking, adjacency pairs, preference organization, and repair."),s("detail","Interactional detail","Analyze timing, overlap, pauses, formulation, and embodied cues where available."),s("cases","Case comparison","Compare deviant and recurrent interactional patterns."),s("claim","Interactional claim","State how participants jointly produce meaning or action, grounded in sequence evidence.")),
"Interpretative Phenomenological Analysis":w(s("experience","Lived experience question","Define the experience and relatively homogeneous participant group."),s("case","Idiographic reading","Analyze each case deeply before cross-case abstraction."),s("themes","Experiential themes","Develop themes linking description with interpretation."),s("double","Double hermeneutic","Reflect on how participants make sense of experience and how the analyst interprets that sense-making."),s("cross","Cross-case synthesis","Identify convergence and divergence without erasing individual cases.")),
"Phenomenological Reduction":w(s("phenomenon","Phenomenon","Define the lived phenomenon to be described."),s("bracket","Bracketing","Identify and hold prior theoretical assumptions in suspension as far as practicable."),s("meaning","Meaning units","Describe experiential meaning units closely from accounts."),s("essence","Invariant structure","Distinguish essential from incidental features through imaginative variation."),s("description","Phenomenological description","Synthesize the structure of experience and document interpretive limits.")),
"Ethnographic Analysis":w(s("field","Field setting","Define community, site, access, roles, and observation period."),s("records","Field records","Integrate observations, interviews, artifacts, and reflexive notes."),s("patterns","Cultural patterns","Identify routines, meanings, norms, roles, and contradictions across contexts."),s("situate","Situate behavior","Explain patterns within local history, institutions, and power relations."),s("account","Ethnographic account","Develop a thick, evidence-grounded interpretation with positionality and limits.")),
"Domain Analysis":w(s("domain","Cultural domain","Define the semantic or cultural domain being investigated."),s("terms","Included terms","Identify items participants treat as members of the domain."),s("relations","Semantic relations","Specify relationships such as kinds-of, parts-of, causes, uses, or locations."),s("structure","Domain structure","Organize cover terms, included terms, and semantic links."),s("test","Cultural validation","Check the structure against participant usage, exceptions, and contrasting cases.")),
"Taxonomic Analysis":w(s("domain","Selected domain","Choose a domain with sufficiently developed included terms."),s("dimensions","Contrast dimensions","Identify dimensions participants use to distinguish terms."),s("taxonomy","Taxonomic structure","Arrange terms hierarchically or relationally by those distinctions."),s("cases","Test cases","Check ambiguous and boundary cases against the taxonomy."),s("meaning","Interpretive meaning","Explain what the taxonomy reveals about cultural organization and practice.")),
"Componential Analysis":w(s("set","Contrast set","Select related terms or categories within a cultural domain."),s("attributes","Attributes","Identify dimensions of contrast participants use."),s("matrix","Feature matrix","Map presence, absence, or values of attributes across terms."),s("patterns","Contrast patterns","Identify minimal contrasts, clusters, and exceptions."),s("interpret","Cultural interpretation","Explain what the contrast system reveals about meaning and decision rules.")),
"Template Analysis":w(s("question","Analytic question","Define the corpus and initial thematic focus."),s("initial","Initial template","Create a provisional hierarchy of codes from theory and early data."),s("apply","Apply and revise","Code cases and iteratively add, remove, merge, or reorder themes."),s("hierarchy","Theme hierarchy","Stabilize the template while preserving case-specific nuance."),s("interpret","Cross-case interpretation","Use the final template to compare patterns and exceptions transparently.")),
"Directed Content Analysis":w(s("theory","Guiding theory","Define the existing theory or prior framework that supplies initial categories."),s("codebook","Directed codebook","Operationalize categories and specify how uncodable material will be handled."),s("code","Apply coding","Code data systematically while marking evidence that does not fit the framework."),s("extend","Extend or challenge","Use novel or contradictory material to refine, extend, or reject parts of the framework."),s("conclusion","Theory-informed conclusion","State what was supported, modified, or newly discovered.")),
};
export const QUALITATIVE_SPECIFIC_CATALOG_WORKFLOW_COUNT=Object.keys(QUALITATIVE_SPECIFIC_WORKFLOWS).length; export const hasQualitativeSpecificCatalogWorkflow=(name:string)=>Boolean(QUALITATIVE_SPECIFIC_WORKFLOWS[name]); export const qualitativeSpecificCatalogWorkflow=(name:string)=>QUALITATIVE_SPECIFIC_WORKFLOWS[name]?.map(x=>({...x}));