import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";
import { ADVANCED_SPECIFIC_CATALOG_WORKFLOW_COUNT, advancedSpecificCatalogWorkflow, hasAdvancedSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsAdvanced";
import { INTELLIGENCE_SPECIFIC_CATALOG_WORKFLOW_COUNT, hasIntelligenceSpecificCatalogWorkflow, intelligenceSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsIntelligence";
import { INTELLIGENCE_CORE_SPECIFIC_CATALOG_WORKFLOW_COUNT, hasIntelligenceCoreSpecificCatalogWorkflow, intelligenceCoreSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsIntelligenceCore";
import { FRAMING_SPECIFIC_CATALOG_WORKFLOW_COUNT, framingSpecificCatalogWorkflow, hasFramingSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsFraming";
import { CHALLENGE_SPECIFIC_CATALOG_WORKFLOW_COUNT, challengeSpecificCatalogWorkflow, hasChallengeSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsChallenge";
import { FORECASTING_SPECIFIC_CATALOG_WORKFLOW_COUNT, forecastingSpecificCatalogWorkflow, hasForecastingSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsForecasting";
import { EXPERT_SPECIFIC_CATALOG_WORKFLOW_COUNT, expertSpecificCatalogWorkflow, hasExpertSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsExpert";
import { MCDA_SPECIFIC_CATALOG_WORKFLOW_COUNT, hasMCDASpecificCatalogWorkflow, mcdaSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsMCDA";
import { DECISION_UNCERTAINTY_SPECIFIC_CATALOG_WORKFLOW_COUNT, decisionUncertaintySpecificCatalogWorkflow, hasDecisionUncertaintySpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsDecisionUncertainty";
import { CAUSAL_SPECIFIC_CATALOG_WORKFLOW_COUNT, causalSpecificCatalogWorkflow, hasCausalSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsCausal";
import { SECURITY_SPECIFIC_CATALOG_WORKFLOW_COUNT, securitySpecificCatalogWorkflow, hasSecuritySpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsSecurity";
import { SAFETY_SPECIFIC_CATALOG_WORKFLOW_COUNT, safetySpecificCatalogWorkflow, hasSafetySpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsSafety";
import { SYSTEMS_DYNAMICS_SPECIFIC_CATALOG_WORKFLOW_COUNT, systemsDynamicsSpecificCatalogWorkflow, hasSystemsDynamicsSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsSystemsDynamics";
import { NETWORKS_SPECIFIC_CATALOG_WORKFLOW_COUNT, networksSpecificCatalogWorkflow, hasNetworksSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsNetworks";
import { RESEARCH_SYNTHESIS_SPECIFIC_CATALOG_WORKFLOW_COUNT, researchSynthesisSpecificCatalogWorkflow, hasResearchSynthesisSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsResearchSynthesis";
import { QUALITATIVE_SPECIFIC_CATALOG_WORKFLOW_COUNT, qualitativeSpecificCatalogWorkflow, hasQualitativeSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsQualitative";
import { QUANTITATIVE_SPECIFIC_CATALOG_WORKFLOW_COUNT, quantitativeSpecificCatalogWorkflow, hasQuantitativeSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsQuantitative";
import { QUALITY_SPECIFIC_CATALOG_WORKFLOW_COUNT, qualitySpecificCatalogWorkflow, hasQualitySpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsQuality";
import { POLICY_SPECIFIC_CATALOG_WORKFLOW_COUNT, policySpecificCatalogWorkflow, hasPolicySpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsPolicy";
import { ECONOMICS_SPECIFIC_CATALOG_WORKFLOW_COUNT, economicsSpecificCatalogWorkflow, hasEconomicsSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsEconomics";
import { GEOSPATIAL_SPECIFIC_CATALOG_WORKFLOW_COUNT, geospatialSpecificCatalogWorkflow, hasGeospatialSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsGeospatial";
import { LEGAL_SPECIFIC_CATALOG_WORKFLOW_COUNT, legalSpecificCatalogWorkflow, hasLegalSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsLegal";
import { OPERATIONS_RESEARCH_SPECIFIC_CATALOG_WORKFLOW_COUNT, operationsResearchSpecificCatalogWorkflow, hasOperationsResearchSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsOperationsResearch";
import { DESIGN_SPECIFIC_CATALOG_WORKFLOW_COUNT, designSpecificCatalogWorkflow, hasDesignSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsDesign";
import { LANGUAGE_MEDIA_SPECIFIC_CATALOG_WORKFLOW_COUNT, languageMediaSpecificCatalogWorkflow, hasLanguageMediaSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsLanguageMedia";
import { HISTORICAL_SPECIFIC_CATALOG_WORKFLOW_COUNT, historicalSpecificCatalogWorkflow, hasHistoricalSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsHistorical";
import { THEORY_DERIVED_SPECIFIC_CATALOG_WORKFLOW_COUNT, hasTheoryDerivedSpecificCatalogWorkflow, theoryDerivedSpecificCatalogWorkflow } from "./techniquesCatalogWorkflowsTheoryDerived";

const s = (id: string, title: string, prompt: string, responseKind: TechniqueResponseKind = "long-text"): TechniqueStepDefinition => ({ id, title, prompt, responseKind });
const w = (...steps: TechniqueStepDefinition[]) => steps;

const SPECIFIC_WORKFLOWS: Record<string, TechniqueStepDefinition[]> = {
  "Key Intelligence Questions": w(s("decision", "Decision context", "What decision, warning problem, or uncertainty must the analysis support?"), s("questions", "Key intelligence questions", "Write the smallest set of answerable questions that would materially improve the decision.", "list"), s("priority", "Priority and dependency", "Which questions are prerequisite, time-critical, or highest impact, and how do they depend on one another?"), s("requirements", "Information requirements", "For each priority question, specify what information or observation would answer it.", "list"), s("review", "Coverage check", "What important decision uncertainty remains outside the question set?")),
  "Collection Gap Analysis": w(s("judgment", "Judgment or requirement", "State the judgment or intelligence requirement whose information base is being assessed."), s("known", "Known and supported", "List what is known, its source basis, and how directly it bears on the requirement.", "list"), s("gaps", "Material gaps", "List missing facts, inaccessible observations, stale reporting, and unresolved contradictions.", "list"), s("impact", "Gap impact", "Which gaps could most change the judgment or confidence if resolved?"), s("collection", "Collection priorities", "Translate the highest-impact gaps into observable, feasible collection requirements.", "list")),
  "Source Reliability Assessment": w(s("source", "Source and access", "Identify the source, its claimed access, reporting chain, and relevant track record."), s("reliability", "Reliability", "Assess whether the source has historically reported accurately and whether current access is direct, indirect, or uncertain."), s("motives", "Motives and vulnerabilities", "What incentives, pressures, biases, deception risks, or misunderstandings could distort the reporting?"), s("corroboration", "Independent corroboration", "What genuinely independent evidence supports or contradicts the source?", "list"), s("rating", "Assessment", "State a bounded reliability judgment and the caveats that matter most.")),
  "Corroboration Matrix": w(s("claims", "Claims", "List the material claims that require corroboration.", "list"), s("sources", "Source set", "List the sources or evidence streams and note likely dependencies among them.", "list"), s("matrix", "Claim-source matrix", "For each claim, record which independent sources support, contradict, or do not address it."), s("independence", "Independence test", "Which apparent corroboration is actually circular, derivative, or based on a common origin?"), s("result", "Corroboration result", "Which claims are robustly supported, singly sourced, disputed, or unsupported?")),
  "Missing Evidence Analysis": w(s("hypothesis", "Hypothesis or judgment", "State the proposition whose expected evidence is being examined."), s("expected", "Expected evidence", "If the proposition were true, what observable evidence should normally exist?", "list"), s("absence", "Observed absences", "Which expected observations are missing, delayed, inaccessible, or ambiguous?", "list"), s("explanations", "Alternative explanations for absence", "Could denial, concealment, collection gaps, timing, low base rates, or a wrong hypothesis explain the absence?"), s("update", "Update", "How should the missing evidence change confidence, and what observation would be most diagnostic next?")),
  "Discriminating Evidence Matrix": w(s("hypotheses", "Hypotheses", "List the serious competing hypotheses.", "list"), s("evidence", "Evidence", "List evidence items that could differ in expectedness across the hypotheses.", "list"), s("matrix", "Diagnostic comparison", "For each evidence item, compare how expected it would be under each hypothesis; avoid counting merely compatible evidence as strongly diagnostic."), s("weights", "High-value evidence", "Which items most sharply distinguish the hypotheses, and which are redundant or non-discriminating?", "list"), s("update", "Relative update", "Revise the relative standing of the hypotheses and identify the next most valuable discriminating evidence.")),
  "Cognitive Bias Audit": w(s("judgment", "Judgment under review", "State the assessment, decision, forecast, or interpretation and document how it was produced."), s("biases", "Bias exposure", "Check systematically for anchoring, confirmation, availability, recency, status quo, sunk-cost, framing, mirror imaging, overconfidence, attribution, motivated reasoning, and group effects.", "list"), s("signatures", "Observable signatures", "For each plausible bias, identify concrete features of the reasoning process, evidence selection, estimates, framing, or discussion that indicate exposure rather than merely naming the bias."), s("countermeasures", "Targeted countermeasures", "Apply an appropriate corrective such as independent estimation, base-rate review, reframing, contrary-evidence search, outside view, assumption reversal, or dissent capture.", "list"), s("revision", "Reassess", "Record what changed after the countermeasures and which residual bias risks remain material enough to affect confidence or process design.")),
  "Murder Board": w(s("product", "Product or argument", "State the analytic product, recommendation, or briefing being challenged."), s("claims", "Critical claims", "List the claims whose failure would most damage the product.", "list"), s("attack", "Adversarial questioning", "Generate the hardest plausible questions about evidence, logic, assumptions, alternatives, precision, sourcing, and implications.", "list"), s("defense", "Defend or concede", "Answer each challenge with evidence; distinguish claims that can be defended from those that require revision."), s("repair", "Repair plan", "Revise weak claims, caveats, confidence, or sourcing before finalization.")),
  "Horizon Scanning": w(s("domain", "Scan domain and horizon", "Define the topic, geographic scope, stakeholders, and time horizon."), s("signals", "Signals", "Collect weak signals, emerging issues, anomalies, innovations, policy changes, and peripheral developments.", "list"), s("clusters", "Cluster and mature", "Group related signals and distinguish isolated noise from reinforcing patterns."), s("impact", "Potential impact", "Assess plausible direction, scale, timing, uncertainty, and affected actors for each important cluster."), s("watch", "Watch list", "Select signals and indicators for continued monitoring, with explicit review triggers.", "list")),
  "Backcasting": w(s("future", "Desired or assumed future", "Define the future state clearly, including horizon and success conditions."), s("milestones", "Necessary milestones", "Work backward to identify conditions and milestones that would have to exist before the future state is reached.", "list"), s("pathways", "Pathways", "Connect milestones into plausible sequences and identify dependencies, bottlenecks, and branch points."), s("present", "Present requirements", "What would need to begin, stop, or change now for each pathway to remain feasible?", "list"), s("indicators", "Progress indicators", "Identify observable markers that would show movement toward or away from the pathway.", "list")),
  "Cone of Plausibility": w(s("baseline", "Baseline", "State the current trajectory and time horizon without assuming it will continue unchanged."), s("drivers", "Drivers and constraints", "Identify forces that could widen, narrow, accelerate, or redirect the range of plausible futures.", "list"), s("bounds", "Plausibility bounds", "Define reasonable upper, lower, and discontinuous departures from the baseline; explain why they remain plausible."), s("branches", "Branching developments", "Identify events or decisions that would move the system toward different portions of the cone.", "list"), s("monitor", "Monitor the cone", "What indicators would show the plausible range widening, narrowing, or shifting?", "list")),
  "Futures Wheel": w(s("change", "Central change", "State the event, trend, decision, innovation, or scenario change whose consequences are being explored."), s("first", "First-order effects", "List direct consequences across relevant domains without evaluating them too early.", "list"), s("second", "Second-order effects", "For each direct consequence, identify important follow-on effects, interactions, adaptations, and feedbacks.", "list"), s("higher", "Higher-order cascades and interactions", "Trace selected branches to tertiary effects and identify where consequence chains reinforce, offset, intersect, or create shared bottlenecks."), s("priorities", "Priority implications", "Prioritize consequence chains by plausibility, impact, timing, reversibility, risk or opportunity, and monitoring value.", "list")),
  "Structured Expert Judgment": w(s("questions", "Elicitation questions", "Define quantities or judgments precisely enough that experts are answering the same question.", "list"), s("experts", "Expert selection and independence", "Document relevant expertise, diversity, conflicts, and steps taken to preserve independent judgment."), s("elicitation", "Individual elicitation", "Collect estimates, uncertainty ranges, and reasoning independently before discussion."), s("aggregation", "Aggregation", "Compare distributions, reasons, and calibration evidence; aggregate transparently rather than forcing consensus."), s("disagreement", "Disagreement and update", "Record unresolved disagreement, its causes, and what new evidence would move the panel.")),
  "Brier Score Review": w(s("forecasts", "Forecast set", "List resolved probabilistic forecasts and their stated probabilities."), s("scores", "Score outcomes", "Calculate squared probability errors for each forecast and the mean Brier score."), s("calibration", "Calibration", "Group forecasts by probability band and compare stated probabilities with observed frequencies."), s("resolution", "Resolution and discrimination", "Did forecasts meaningfully distinguish events that occurred from those that did not?"), s("learning", "Forecasting lessons", "Identify systematic overconfidence, underconfidence, base-rate neglect, or category-specific weaknesses to correct.")),
  "Analytic Hierarchy Process": w(s("goal", "Goal and hierarchy", "Define the decision goal, criteria, subcriteria if needed, and alternatives."), s("criteria", "Pairwise criteria comparisons", "Compare criteria two at a time using a consistent preference scale and record the rationale."), s("alternatives", "Alternative comparisons", "Compare alternatives pairwise under each criterion."), s("consistency", "Consistency check", "Review comparison consistency and revisit judgments that create strong contradictions."), s("priority", "Priority synthesis", "Combine weights and alternative scores, then test whether modest judgment changes alter the ranking.")),
  "Sensitivity Analysis": w(s("result", "Result under review", "State the model result, ranking, estimate, or decision being tested."), s("inputs", "Uncertain inputs", "Identify assumptions and input values that could reasonably vary.", "list"), s("ranges", "Plausible ranges", "Set defensible alternative values or ranges rather than arbitrary extremes."), s("vary", "Vary systematically", "Change one or more inputs and record how the result responds, including thresholds or reversals."), s("conclusion", "Robustness conclusion", "Identify the inputs that dominate the result and the range over which the conclusion remains stable.")),
  "Influence Diagramming": w(s("decision", "Decision node", "Define the decision or sequence of decisions to be supported."), s("uncertainties", "Chance variables", "List uncertain events or states that affect outcomes.", "list"), s("values", "Value outcomes", "Define the outcomes or objectives whose value matters."), s("arcs", "Influence structure", "Map informational, causal, and decision dependencies without implying causation where only information flow exists."), s("insight", "Decision insight", "Identify pivotal uncertainties, information needs, and decisions whose timing or sequencing matters most.")),
  "Stock-and-Flow Mapping": w(s("boundary", "System boundary", "Define the system and time horizon."), s("stocks", "Stocks", "Identify accumulations that persist over time, such as people, inventory, trust, capacity, or capital.", "list"), s("flows", "Flows", "Identify rates that increase or decrease each stock and their governing conditions.", "list"), s("feedback", "Feedback and delays", "Connect stocks and flows through feedback loops and note important delays."), s("behavior", "Behavior implications", "What growth, depletion, overshoot, oscillation, or bottleneck behavior could the structure generate?")),
  "Leverage Points Analysis": w(s("system", "System structure", "Describe the system, its goals, feedbacks, rules, information flows, and major parameters."), s("interventions", "Candidate interventions", "List possible interventions at different depths, from parameter changes to rules, goals, or paradigms.", "list"), s("leverage", "Leverage assessment", "For each intervention, estimate how strongly it could change system behavior and how difficult it would be to implement."), s("resistance", "System resistance", "How might feedback, adaptation, incentives, or delays neutralize or reverse the intervention?"), s("priority", "Priority leverage points", "Select interventions with high leverage and acceptable side effects, and specify what should be monitored.")),
  "Social Network Analysis": w(s("question", "Network question", "Define the behavior, influence, flow, cohesion, or vulnerability to explain."), s("nodes", "Nodes and ties", "Define node types, tie meaning, direction, weight, and time window before collecting relationships."), s("structure", "Structural measures", "Assess relevant centrality, density, clustering, components, brokerage, or community structure."), s("interpret", "Substantive interpretation", "Explain what the network pattern means in the real system; do not equate high centrality automatically with importance."), s("limits", "Boundary and data limits", "Identify missing nodes, uncertain ties, sampling effects, temporal changes, and alternative network definitions.")),
  "Preliminary Hazard Analysis": w(s("scope", "System and phase", "Define the system, mission, lifecycle phase, operating environment, and boundaries."), s("hazards", "Hazards", "Identify hazardous states, energies, materials, interactions, or conditions before detailed design.", "list"), s("causes", "Causes and initiating conditions", "List credible causes and enabling conditions for each hazard."), s("risk", "Initial risk", "Assess severity and likelihood or exposure using the project's chosen risk criteria."), s("controls", "Controls and follow-up", "Identify prevention, detection, mitigation, and analyses needed for the highest-priority hazards.", "list")),
  "Systems-Theoretic Process Analysis": w(s("losses", "Losses and hazards", "Define unacceptable losses and system-level hazardous states."), s("control", "Control structure", "Model controllers, controlled processes, sensors, actuators, feedback, and responsibilities."), s("uca", "Unsafe control actions", "For each control action, ask whether not providing, providing, mistiming, or sustaining it could create a hazard.", "list"), s("scenarios", "Loss scenarios", "Explain how flawed process models, feedback, coordination, component behavior, or environment could produce each unsafe control action."), s("constraints", "Safety constraints", "Translate the scenarios into enforceable safety constraints and monitoring needs.", "list")),
  "DMAIC": w(s("define", "Define", "Define the customer or mission problem, scope, goal, stakeholders, and process boundary."), s("measure", "Measure", "Establish operational definitions, baseline performance, and measurement reliability."), s("analyze", "Analyze", "Identify and verify root causes using data rather than selecting causes by intuition."), s("improve", "Improve", "Design and test changes that address verified causes and assess side effects."), s("control", "Control", "Define controls, ownership, metrics, and response plans that sustain the improvement.")),
  "A3 Problem Solving": w(s("background", "Background and current condition", "State why the problem matters and depict the current condition with concrete evidence."), s("target", "Target condition", "Define the desired condition and measurable gap."), s("cause", "Root-cause analysis", "Explain why the gap exists and distinguish verified causes from assumptions."), s("countermeasures", "Countermeasures and plan", "Select countermeasures linked to causes, owners, timing, and expected effects."), s("followup", "Follow-up", "Compare actual results with expected results and capture remaining gaps and learning.")),
  "Thematic Analysis": w(s("corpus", "Corpus and question", "Define the dataset, analytic question, sampling logic, and unit of analysis."), s("coding", "Initial coding", "Code meaningfully relevant features across the corpus while preserving context."), s("themes", "Candidate themes", "Group codes into patterns of shared meaning organized around a central concept."), s("review", "Review and refine", "Test themes against coded extracts and the full dataset; split, merge, or discard weak themes."), s("interpret", "Interpretation", "Define and name each theme, show supporting and disconfirming evidence, and connect themes back to the analytic question.")),
  "Causal Diagramming with DAGs": w(s("question", "Causal question", "Specify the exposure, outcome, population, and causal contrast of interest."), s("variables", "Variables", "List plausible causes of the exposure, outcome, and relevant common causes using substantive knowledge."), s("dag", "Directed acyclic graph", "Draw causal arrows without conditioning on the observed data pattern; include unmeasured variables when conceptually important."), s("adjustment", "Adjustment logic", "Identify backdoor paths, confounders to adjust for, mediators to avoid adjusting away, and colliders that should not be conditioned on."), s("tests", "Identification and sensitivity", "State whether the effect is identifiable under the graph and which assumptions require sensitivity analysis or additional evidence.")),
  "Difference-in-Differences": w(s("groups", "Groups and intervention", "Define treated and comparison groups, intervention timing, and outcome."), s("pretrends", "Pre-treatment trends", "Examine whether groups followed sufficiently parallel trends before treatment and identify anticipatory effects."), s("estimate", "Difference in differences", "Compare outcome changes over time between groups using an appropriate specification."), s("threats", "Validity threats", "Check concurrent shocks, compositional changes, spillovers, staggered treatment issues, and differential measurement."), s("interpret", "Causal interpretation", "State the estimated effect together with the assumptions and robustness checks required for a causal reading.")),
  "Process Tracing": w(s("claim", "Causal claim", "State the proposed mechanism linking cause to outcome in this case."), s("mechanism", "Mechanism steps", "Break the mechanism into a sequence of actors, actions, states, and observable implications."), s("evidence", "Within-case evidence", "Collect evidence for each mechanism step and assess its provenance and independence."), s("tests", "Evidence tests", "Classify important observations by how necessary or sufficient they are for the hypothesis and compare rival mechanisms."), s("inference", "Causal inference", "State which mechanism steps are supported, where the chain remains weak, and which rival explanations survive.")),
  "Systematic Review": w(s("question", "Review question", "Define the review question, population or domain, concepts, outcomes, and eligibility criteria."), s("search", "Search strategy", "Specify databases or sources, search terms, dates, languages, grey literature, and supplementary searching."), s("screen", "Screen and select", "Apply inclusion and exclusion criteria consistently and record reasons for exclusion."), s("appraise", "Critical appraisal and extraction", "Assess risk of bias or study quality and extract results using a predefined structure."), s("synthesize", "Synthesis", "Integrate findings using an appropriate qualitative or quantitative synthesis and report heterogeneity, uncertainty, and evidence gaps.")),
  "Meta-Analysis": w(s("question", "Effect question", "Define the effect or association, eligibility criteria, and compatible outcome metric."), s("effects", "Study effects", "Extract or compute comparable effect estimates and uncertainties from eligible studies."), s("model", "Pooling model", "Choose and justify fixed- or random-effects assumptions and estimate the pooled effect."), s("heterogeneity", "Heterogeneity and bias", "Assess between-study heterogeneity, influential studies, reporting bias, and meaningful moderators."), s("interpret", "Interpretation", "Report pooled magnitude, uncertainty, heterogeneity, evidence quality, and limits on generalization.")),
  "Jobs-to-be-Done Analysis": w(s("situation", "Situation and progress", "Describe the circumstance in which a person seeks progress rather than starting from a product feature."), s("job", "Core job", "State what the person is trying to accomplish, including functional, emotional, and social dimensions."), s("forces", "Forces of change", "Identify push from the current situation, pull of a new solution, habits of the present, and anxieties about change."), s("outcomes", "Desired outcomes", "Translate the job into observable outcomes customers use to judge success.", "list"), s("opportunity", "Opportunity", "Identify underserved outcomes or moments where current solutions force costly workarounds.")),
  "TRIZ": w(s("problem", "Problem and contradiction", "State the engineering or system problem as a contradiction: improving one property worsens another, or a property must have opposing states."), s("ideal", "Ideal final result", "Describe the desired function with minimal cost, harm, complexity, or added resources."), s("resources", "Available resources", "List existing materials, fields, time, space, information, and system functions that could be reused."), s("principles", "Inventive principles", "Use relevant contradiction patterns or inventive principles to generate solution concepts rather than compromise immediately."), s("evaluate", "Evaluate concepts", "Compare concepts against the contradiction, ideality, secondary effects, and implementation constraints.")),
  "PASTA Threat Modeling": w(s("objectives", "Business and security objectives", "Define assets, business impact, security objectives, and scope."), s("scope", "Technical scope and decomposition", "Map application components, data flows, trust boundaries, dependencies, and attack surface."), s("threats", "Threat and attack analysis", "Identify credible threat actors, objectives, attack paths, and relevant weaknesses."), s("risk", "Risk analysis", "Estimate attack likelihood or feasibility and impact using explicit criteria rather than threat count alone."), s("controls", "Controls and residual risk", "Map preventive, detective, and recovery controls to priority attack paths and record residual risk.")),
  "Diamond Model Analysis": w(s("event", "Intrusion event", "Define the bounded malicious event or activity being analyzed."), s("vertices", "Four vertices", "Identify adversary, capability, infrastructure, and victim evidence, preserving uncertainty and source provenance."), s("relationships", "Relationships", "Analyze how the vertices interact and what additional relationships, direction, or dependencies are implied."), s("pivot", "Analytic pivots", "Pivot from known vertices to discover related events, infrastructure, capabilities, victims, or adversary behavior."), s("activity", "Activity thread", "Connect related events cautiously into activity threads and distinguish observation from attribution.")),
  "MITRE ATT&CK Mapping": w(s("scope", "Observed activity", "Define the incident, campaign, or actor behavior and the evidence window."), s("behaviors", "Observed behaviors", "Extract concrete adversary actions before assigning ATT&CK labels.", "list"), s("mapping", "Technique mapping", "Map each supported behavior to the most specific applicable ATT&CK technique or sub-technique and preserve evidence links."), s("gaps", "Coverage gaps", "Distinguish unobserved behavior from behavior that was not detectable with available telemetry."), s("defense", "Detection and mitigation implications", "Use the mapping to identify detection coverage, control gaps, collection priorities, and likely adjacent behaviors.")),
  "Incident Reconstruction": w(s("scope", "Incident boundary", "Define the systems, identities, assets, and time window under investigation."), s("timeline", "Normalized timeline", "Order events from independent logs and artifacts using normalized time and record clock uncertainty."), s("causal", "Causal sequence", "Distinguish temporal adjacency from causal dependency and connect events only when evidence supports the link."), s("alternatives", "Alternative reconstructions", "Identify gaps, ambiguous artifacts, anti-forensics, and plausible alternative sequences."), s("findings", "Findings", "State the best-supported reconstruction, confidence by segment, unresolved gaps, and evidence needed next.")),
  "Pattern-of-Life Analysis": w(s("subject", "Subject and baseline", "Define the actor, system, place, or activity and the observation period used to establish normal behavior."), s("patterns", "Recurring patterns", "Identify repeated timing, locations, associations, sequences, volumes, or routines without treating correlation as intent."), s("deviations", "Deviations", "Identify material departures from baseline and assess whether they exceed normal variability."), s("contexts", "Context and alternatives", "Test benign, operational, seasonal, data-quality, and adversarial explanations for each deviation."), s("indicators", "Indicators and limits", "State what the pattern can support, what it cannot establish, and which future observations would be most informative.")),
  "Rhetorical Criticism": w(s("artifact", "Rhetorical artifact", "Define the speech, text, image, performance, or communication event and its context."), s("situation", "Rhetorical situation", "Identify rhetor, audiences, exigence, constraints, genre, and relevant historical conditions."), s("strategies", "Rhetorical strategies", "Analyze appeals, framing, arrangement, style, tropes, identification, omissions, and audience positioning."), s("effects", "Functions and effects", "Explain what the rhetoric invites audiences to believe, feel, value, or do and how form supports that work."), s("judgment", "Interpretive claim", "State an evidence-grounded claim about how the artifact functions rhetorically, including plausible alternative readings.")),
  "Canonical Criticism": w(s("canon", "Canonical context", "Identify the canon, community, ordering, and final-form context in which the text is being interpreted."), s("placement", "Placement and neighbors", "Examine how position, grouping, superscriptions, framing, and neighboring texts shape interpretation."), s("reuse", "Intra-canonical relationships", "Trace quotation, echo, reinterpretation, thematic development, and tensions across the canon."), s("community", "Canonical function", "Ask how the received form functions for the interpreting community without erasing historical layers or diversity."), s("limits", "Limits", "Distinguish canonical interpretation from claims about original composition, historical events, or universal meaning.")),
  "Regulatory Impact Assessment": w(s("problem", "Policy problem", "Define the problem, baseline, affected groups, and why government action is being considered."), s("options", "Options", "Specify realistic regulatory and non-regulatory options, including a do-nothing baseline.", "list"), s("impacts", "Impacts", "Identify economic, social, environmental, rights, administrative, and distributional effects for each option."), s("compare", "Compare options", "Compare benefits, costs, risks, uncertainty, implementation burden, and coherence using explicit criteria."), s("monitor", "Implementation and review", "Specify preferred option, residual uncertainty, monitoring indicators, and conditions for ex-post review.")),
  "Cost-Benefit Analysis": w(s("scope", "Scope and perspective", "Define the decision, affected population, time horizon, counterfactual, and whose costs and benefits count."), s("effects", "Identify effects", "List material benefits, costs, transfers, externalities, and distributional effects without double counting.", "list"), s("valuation", "Value and timing", "Monetize effects where defensible, discount future values consistently, and preserve non-monetized effects explicitly."), s("uncertainty", "Uncertainty and sensitivity", "Test key assumptions, ranges, discounting, and scenarios that could change net benefits."), s("decision", "Net assessment", "Report net present value or benefit-cost ratio together with distributional effects, unquantified impacts, and limitations.")),
  "IRAC Analysis": w(s("issue", "Issue", "Frame the precise legal issue as a question tied to material facts."), s("rule", "Rule", "State the governing rule, elements, exceptions, standards, and controlling authority."), s("application", "Application", "Apply each relevant rule element to the facts using analogies, distinctions, counterarguments, and evidentiary limits."), s("counter", "Counterarguments", "Present the strongest competing interpretation or application and explain what facts or authorities support it."), s("conclusion", "Conclusion", "Give a bounded conclusion proportionate to the authority and factual uncertainty.")),
  "Hot Spot Analysis": w(s("events", "Events and geography", "Define the event type, study area, observation period, coordinate quality, and spatial unit or distance assumptions."), s("baseline", "Expected spatial pattern", "Establish the appropriate population-at-risk or background distribution so density is not mistaken for excess risk."), s("method", "Hot-spot method", "Apply a suitable local clustering or intensity method and state neighborhood, bandwidth, or spatial-weight choices."), s("significance", "Significance and stability", "Assess statistical significance or robustness and test sensitivity to scale, edge effects, and multiple comparisons."), s("interpret", "Spatial interpretation", "Explain what clusters may indicate while separating spatial association from causal explanation.")),
  "Linear Programming": w(s("objective", "Objective function", "Define the quantity to maximize or minimize and its coefficients."), s("variables", "Decision variables", "Define controllable variables, units, bounds, and non-negativity assumptions."), s("constraints", "Constraints", "Translate resource, capacity, balance, policy, or demand limits into linear constraints.", "list"), s("solve", "Solve and inspect", "Find the optimal feasible solution and inspect binding constraints, slack, and shadow values where available."), s("sensitivity", "Sensitivity", "Test how coefficient or resource changes alter the solution and identify assumptions that make the optimum fragile.")),
};

export const SPECIFIC_CATALOG_WORKFLOW_COUNT = Object.keys(SPECIFIC_WORKFLOWS).length + ADVANCED_SPECIFIC_CATALOG_WORKFLOW_COUNT + INTELLIGENCE_SPECIFIC_CATALOG_WORKFLOW_COUNT + INTELLIGENCE_CORE_SPECIFIC_CATALOG_WORKFLOW_COUNT + FRAMING_SPECIFIC_CATALOG_WORKFLOW_COUNT + CHALLENGE_SPECIFIC_CATALOG_WORKFLOW_COUNT + FORECASTING_SPECIFIC_CATALOG_WORKFLOW_COUNT + EXPERT_SPECIFIC_CATALOG_WORKFLOW_COUNT + MCDA_SPECIFIC_CATALOG_WORKFLOW_COUNT + DECISION_UNCERTAINTY_SPECIFIC_CATALOG_WORKFLOW_COUNT + CAUSAL_SPECIFIC_CATALOG_WORKFLOW_COUNT + SECURITY_SPECIFIC_CATALOG_WORKFLOW_COUNT + SAFETY_SPECIFIC_CATALOG_WORKFLOW_COUNT + SYSTEMS_DYNAMICS_SPECIFIC_CATALOG_WORKFLOW_COUNT + NETWORKS_SPECIFIC_CATALOG_WORKFLOW_COUNT + RESEARCH_SYNTHESIS_SPECIFIC_CATALOG_WORKFLOW_COUNT + QUALITATIVE_SPECIFIC_CATALOG_WORKFLOW_COUNT + QUANTITATIVE_SPECIFIC_CATALOG_WORKFLOW_COUNT + QUALITY_SPECIFIC_CATALOG_WORKFLOW_COUNT + POLICY_SPECIFIC_CATALOG_WORKFLOW_COUNT + ECONOMICS_SPECIFIC_CATALOG_WORKFLOW_COUNT + GEOSPATIAL_SPECIFIC_CATALOG_WORKFLOW_COUNT + LEGAL_SPECIFIC_CATALOG_WORKFLOW_COUNT + OPERATIONS_RESEARCH_SPECIFIC_CATALOG_WORKFLOW_COUNT + DESIGN_SPECIFIC_CATALOG_WORKFLOW_COUNT + LANGUAGE_MEDIA_SPECIFIC_CATALOG_WORKFLOW_COUNT + HISTORICAL_SPECIFIC_CATALOG_WORKFLOW_COUNT + THEORY_DERIVED_SPECIFIC_CATALOG_WORKFLOW_COUNT;
export function specificCatalogWorkflow(name: string): TechniqueStepDefinition[] | undefined {
  return SPECIFIC_WORKFLOWS[name]?.map((item) => ({ ...item })) ?? intelligenceCoreSpecificCatalogWorkflow(name) ?? intelligenceSpecificCatalogWorkflow(name) ?? challengeSpecificCatalogWorkflow(name) ?? framingSpecificCatalogWorkflow(name) ?? forecastingSpecificCatalogWorkflow(name) ?? expertSpecificCatalogWorkflow(name) ?? mcdaSpecificCatalogWorkflow(name) ?? decisionUncertaintySpecificCatalogWorkflow(name) ?? causalSpecificCatalogWorkflow(name) ?? securitySpecificCatalogWorkflow(name) ?? safetySpecificCatalogWorkflow(name) ?? systemsDynamicsSpecificCatalogWorkflow(name) ?? networksSpecificCatalogWorkflow(name) ?? researchSynthesisSpecificCatalogWorkflow(name) ?? qualitativeSpecificCatalogWorkflow(name) ?? quantitativeSpecificCatalogWorkflow(name) ?? qualitySpecificCatalogWorkflow(name) ?? policySpecificCatalogWorkflow(name) ?? economicsSpecificCatalogWorkflow(name) ?? geospatialSpecificCatalogWorkflow(name) ?? legalSpecificCatalogWorkflow(name) ?? operationsResearchSpecificCatalogWorkflow(name) ?? designSpecificCatalogWorkflow(name) ?? languageMediaSpecificCatalogWorkflow(name) ?? historicalSpecificCatalogWorkflow(name) ?? theoryDerivedSpecificCatalogWorkflow(name) ?? advancedSpecificCatalogWorkflow(name);
}

export function hasSpecificCatalogWorkflow(name: string): boolean {
  return Boolean(SPECIFIC_WORKFLOWS[name]) || hasIntelligenceCoreSpecificCatalogWorkflow(name) || hasIntelligenceSpecificCatalogWorkflow(name) || hasChallengeSpecificCatalogWorkflow(name) || hasFramingSpecificCatalogWorkflow(name) || hasForecastingSpecificCatalogWorkflow(name) || hasExpertSpecificCatalogWorkflow(name) || hasMCDASpecificCatalogWorkflow(name) || hasDecisionUncertaintySpecificCatalogWorkflow(name) || hasCausalSpecificCatalogWorkflow(name) || hasSecuritySpecificCatalogWorkflow(name) || hasSafetySpecificCatalogWorkflow(name) || hasSystemsDynamicsSpecificCatalogWorkflow(name) || hasNetworksSpecificCatalogWorkflow(name) || hasResearchSynthesisSpecificCatalogWorkflow(name) || hasQualitativeSpecificCatalogWorkflow(name) || hasQuantitativeSpecificCatalogWorkflow(name) || hasQualitySpecificCatalogWorkflow(name) || hasPolicySpecificCatalogWorkflow(name) || hasEconomicsSpecificCatalogWorkflow(name) || hasGeospatialSpecificCatalogWorkflow(name) || hasLegalSpecificCatalogWorkflow(name) || hasOperationsResearchSpecificCatalogWorkflow(name) || hasDesignSpecificCatalogWorkflow(name) || hasLanguageMediaSpecificCatalogWorkflow(name) || hasHistoricalSpecificCatalogWorkflow(name) || hasTheoryDerivedSpecificCatalogWorkflow(name) || hasAdvancedSpecificCatalogWorkflow(name);
}
