import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";
const s=(id:string,title:string,prompt:string,responseKind:TechniqueResponseKind="long-text"):TechniqueStepDefinition=>({id,title,prompt,responseKind}); const w=(...steps:TechniqueStepDefinition[])=>steps;
export const POLICY_SPECIFIC_WORKFLOWS:Record<string,TechniqueStepDefinition[]>={
  "Cost-Effectiveness Analysis":w(s("goal","Outcome and comparator","Define the policy objective, target population, comparator, and outcome metric."),s("costs","Costs","Estimate incremental resource costs consistently across options."),s("effects","Effects","Estimate outcome changes using a common effectiveness unit and uncertainty ranges."),s("ratio","Incremental comparison","Compare incremental cost-effectiveness and identify dominated options."),s("decision","Decision and uncertainty","State the preferred option, thresholds, sensitivity, and non-quantified effects.")),
  "Distributional Impact Analysis":w(s("groups","Affected groups","Define relevant income, geography, demographic, sectoral, or vulnerability groups."),s("channels","Impact channels","Trace how costs, benefits, risks, and access changes reach each group."),s("magnitude","Distribution of effects","Estimate direction, scale, timing, and uncertainty by group."),s("equity","Equity interpretation","Identify regressivity, concentration, protected interests, and tradeoffs."),s("mitigate","Mitigation","Assess design changes or compensations that reduce unjustified burdens.")),
  "Policy Options Appraisal":w(s("problem","Policy problem","Define the problem, baseline, objectives, constraints, and decision criteria."),s("options","Genuine options","Develop materially different interventions including a credible status quo."),s("evidence","Evidence and assumptions","Assess effectiveness, cost, risk, implementation, and behavioral assumptions for each option."),s("compare","Structured comparison","Compare options consistently and test sensitivity to contested judgments."),s("recommend","Recommendation","Recommend, reject, or sequence options with caveats and monitoring needs.")),
  "Logic Model":w(s("context","Context and need","Define the problem, population, resources, and external conditions."),s("activities","Inputs and activities","Specify resources and actions within program control."),s("outputs","Outputs","Define direct products or services delivered."),s("outcomes","Outcome chain","Link short-, medium-, and long-term outcomes with explicit causal assumptions."),s("test","Indicators and assumptions","Define indicators, external factors, and evidence needed to test the model.")),
  "Theory of Change":w(s("outcome","Long-term outcome","Define the desired change and target population or system."),s("preconditions","Preconditions","Work backward to identify necessary intermediate outcomes and actor changes."),s("mechanisms","Mechanisms and assumptions","Explain why activities should produce each transition and what assumptions must hold."),s("context","Context and alternatives","Identify enabling conditions, competing explanations, and unintended pathways."),s("evidence","Evidence and learning","Attach indicators and evidence to causal links and specify how the theory will be revised.")),
  "Stakeholder Consultation Analysis":w(s("purpose","Consultation purpose","Define the decision, questions, and whose knowledge or interests are relevant."),s("coverage","Stakeholder coverage","Assess who participated, who was absent, and how recruitment shaped the evidence."),s("positions","Views and evidence","Code positions, reasons, experience, factual claims, and proposed alternatives."),s("weight","Interpretation","Distinguish frequency from representativeness or evidentiary strength and preserve minority views."),s("response","Policy response","Record which inputs changed the analysis, which did not, and why.")),
  "Implementation Feasibility Analysis":w(s("option","Policy or program","Define the proposed intervention and required outcomes."),s("capacity","Delivery capacity","Assess legal authority, staffing, funding, technology, supply chains, and administrative capability."),s("actors","Actor feasibility","Assess incentives, compliance, coordination, political support, and likely resistance."),s("risks","Implementation risks","Identify sequencing, timing, dependencies, failure modes, and transition costs."),s("plan","Feasibility judgment","State conditions for successful implementation, adaptations, pilots, and go/no-go triggers.")),
  "Policy Coherence Analysis":w(s("policies","Policy set","Define the policies, objectives, jurisdictions, and time horizons to compare."),s("links","Interactions","Map reinforcing, neutral, duplicative, and conflicting policy mechanisms."),s("levels","Vertical and horizontal coherence","Check alignment across sectors, agencies, government levels, and international commitments."),s("tradeoffs","Tradeoffs","Identify incompatible objectives, displaced harms, and sequencing problems."),s("resolve","Resolution","Recommend alignment, governance, or monitoring changes while preserving legitimate policy differences.")),
};
export const POLICY_SPECIFIC_CATALOG_WORKFLOW_COUNT=Object.keys(POLICY_SPECIFIC_WORKFLOWS).length;
export const hasPolicySpecificCatalogWorkflow=(name:string)=>Boolean(POLICY_SPECIFIC_WORKFLOWS[name]);
export const policySpecificCatalogWorkflow=(name:string)=>POLICY_SPECIFIC_WORKFLOWS[name]?.map(x=>({...x}));