import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";

const s = (id: string, title: string, prompt: string, responseKind: TechniqueResponseKind = "long-text"): TechniqueStepDefinition => ({ id, title, prompt, responseKind });
const w = (...steps: TechniqueStepDefinition[]) => steps;

export const SYSTEMS_DYNAMICS_SPECIFIC_WORKFLOWS: Record<string, TechniqueStepDefinition[]> = {
  "Reinforcing Loop Analysis": w(s("behavior", "Amplifying behavior", "Define the growth, decline, escalation, contagion, or compounding pattern being examined."), s("loop", "Reinforcing loop", "Map the circular chain in which changes feed back to amplify further change."), s("gains", "Gain and accelerants", "Identify coefficients, thresholds, network effects, expectations, or resource flows that strengthen the reinforcing process."), s("limits", "Constraints and counterforces", "Identify balancing loops, resource limits, saturation, delays, and external shocks that can slow or reverse amplification."), s("intervene", "Intervention implications", "Identify leverage points that damp harmful amplification or sustain beneficial reinforcement without triggering stronger counterforces.")),
  "Balancing Loop Analysis": w(s("target", "Target or equilibrium", "Define the desired, expected, or constrained state around which the system appears to regulate."), s("gap", "Gap signal", "Identify how the system senses deviation between current and target conditions."), s("response", "Corrective response", "Map actions or processes triggered by the gap and how they feed back to reduce deviation."), s("delays", "Delays and overshoot", "Identify sensing, decision, implementation, and physical delays that can produce oscillation or instability."), s("limits", "Limits and failure modes", "Assess capacity constraints, distorted signals, changing targets, and reinforcing loops that can defeat the balancing process.")),
  "Delay Analysis": w(s("process", "Process and outcome", "Define the system process where effects arrive materially after causes."), s("delays", "Delay inventory", "Identify information, perception, decision, implementation, transport, accumulation, and biological or technical delays.", "list"), s("behavior", "Behavioral effects", "Analyze how delays can create overshoot, oscillation, overreaction, underreaction, or false confidence."), s("measurement", "Observability", "Identify which state variables are observed late or indirectly and where decision-makers rely on stale indicators."), s("redesign", "Delay-aware action", "Adjust thresholds, buffers, pacing, or monitoring so interventions account for the lag between action and consequence.")),
  "Limits to Growth Analysis": w(s("growth", "Growth engine", "Identify the reinforcing process initially driving expansion or improvement."), s("limit", "Limiting condition", "Identify the resource, capacity, demand, legitimacy, attention, infrastructure, or other constraint that becomes binding as growth proceeds."), s("balance", "Balancing response", "Map how the limiting condition slows growth, increases costs, lowers quality, or creates compensating behavior."), s("signals", "Approaching-limit indicators", "Identify observable signs that the constraint is tightening before growth visibly stalls."), s("strategy", "Constraint strategy", "Decide whether to expand the limiting capacity, reduce demand on it, change the growth mechanism, or accept a stable ceiling.")),
  "Shifting the Burden Analysis": w(s("symptom", "Problem symptom", "Define the recurring symptom and why immediate relief is attractive."), s("quickfix", "Symptomatic solution", "Identify the fast intervention that reduces the visible symptom without addressing its underlying cause."), s("fundamental", "Fundamental solution", "Identify the slower capability, structural change, or root-cause intervention that would reduce dependence on the symptomatic response."), s("dependency", "Dependency loop", "Map how repeated use of the quick fix weakens incentives, resources, skills, or conditions needed for the fundamental solution."), s("rebalance", "Rebalance action", "Protect short-term safety while investing in the fundamental solution and monitoring indicators of growing dependency.")),
  "Fixes That Fail Analysis": w(s("problem", "Problem and fix", "Define the problem, chosen intervention, and intended near-term effect."), s("benefit", "Immediate benefit", "Map the mechanism through which the fix initially improves the visible condition."), s("sideeffect", "Delayed side effect", "Identify secondary consequences that later worsen the original problem or create a new one."), s("feedback", "Failure loop", "Connect the worsening condition back to pressure for more of the same fix or stronger versions of it."), s("redesign", "Redesign", "Replace or constrain the failing fix, address the underlying structure, and define early indicators of the delayed adverse effect.")),
  "Success to the Successful Analysis": w(s("competitors", "Competing activities", "Identify teams, products, strategies, regions, or programs competing for a shared limited resource."), s("allocation", "Allocation rule", "Describe how current performance influences future access to money, people, attention, data, or opportunity."), s("loops", "Self-reinforcing advantage", "Map how resource gains improve performance and how resource losses reduce the rival's ability to recover."), s("fairness", "Structural distortion", "Assess whether observed performance reflects intrinsic merit, path dependence, measurement bias, or cumulative advantage."), s("intervene", "Allocation redesign", "Consider floors, experimentation budgets, rotation, normalization, or other mechanisms that preserve learning and prevent premature lock-in.")),
  "Tragedy of the Commons Analysis": w(s("resource", "Shared resource", "Define the common resource, its regenerative or capacity limits, and the population drawing on it."), s("incentives", "Individual incentives", "Identify benefits to users from additional extraction or use and why costs are partly externalized."), s("depletion", "Depletion feedback", "Map how aggregate use degrades resource quality, capacity, access, or future returns."), s("governance", "Governance conditions", "Assess visibility, boundaries, rules, monitoring, sanctions, trust, and collective-action capacity that affect restraint."), s("strategy", "Sustainable governance", "Identify rules, quotas, rights, pricing, monitoring, or cooperative arrangements that align individual incentives with resource sustainability.")),
  "Escalation Archetype Analysis": w(s("actors", "Competing actors", "Identify the parties whose actions are evaluated relative to one another."), s("measure", "Relative-performance signal", "Define what each side interprets as advantage, inferiority, threat, or unacceptable gap."), s("responses", "Escalating responses", "Map how one side's action increases pressure on the other to respond and how that response feeds back."), s("thresholds", "Escalation thresholds", "Identify red lines, misperception, lags, status incentives, or commitment mechanisms that make de-escalation harder."), s("deescalate", "De-escalation options", "Identify rule changes, common metrics, confidence-building measures, ceilings, or reframing that can break the comparative feedback loop.")),
  "Growth and Underinvestment Analysis": w(s("growth", "Demand or growth process", "Define the reinforcing growth mechanism and the performance standard expected as demand increases."), s("capacity", "Capacity requirement", "Identify the infrastructure, staffing, skills, maintenance, or institutional capacity needed to sustain performance."), s("erosion", "Performance erosion", "Map how insufficient capacity creates delay, lower quality, congestion, or reliability loss."), s("expectations", "Expectation adjustment", "Identify whether deteriorating performance lowers demand, ambitions, service standards, or willingness to invest, concealing the need for capacity."), s("invest", "Investment strategy", "Set leading capacity indicators and investment triggers that act before performance deterioration becomes self-confirming.")),
  "System Dynamics Simulation Design": w(s("question", "Dynamic question", "Define the behavior over time the simulation must explain or explore and the decision it should support."), s("structure", "Model structure", "Specify stocks, flows, auxiliary variables, feedback loops, delays, boundaries, and units consistent with the causal hypothesis."), s("parameters", "Parameters and data", "Estimate parameters from data, literature, or explicit assumptions and record uncertainty and dimensional consistency."), s("validate", "Behavior and structure validation", "Test extreme conditions, historical reproduction, sensitivity, dimensional consistency, and whether structure—not curve fitting—explains the behavior."), s("experiments", "Policy experiments", "Compare interventions and scenarios, identify robust conclusions, and report where results are sensitive to uncertain structure or parameters.")),
  "Agent-Based Model Framing": w(s("question", "Emergent question", "Define the macro pattern or policy question that may arise from heterogeneous interacting agents."), s("agents", "Agents and state", "Define agent types, attributes, objectives, information, memory, and heterogeneity relevant to behavior."), s("rules", "Behavior and interaction rules", "Specify decision rules, adaptation, network or spatial interactions, environment, and institutional constraints."), s("emergence", "Emergent outcomes", "Identify aggregate patterns to observe and explain how they could arise from local interaction rather than imposed equations."), s("validate", "Validation and experiments", "Use stylized facts, micro-level evidence, sensitivity, multiple seeds, and alternative rules to assess whether conclusions are robust.")),
  "Emergent Behavior Analysis": w(s("pattern", "Emergent pattern", "Define the macro-level pattern that is not trivially reducible to any single component's behavior."), s("micro", "Local rules and interactions", "Identify component behaviors, information, constraints, and interaction mechanisms that could generate the pattern."), s("conditions", "Enabling conditions", "Identify density, connectivity, thresholds, heterogeneity, resource conditions, and feedback required for emergence."), s("alternatives", "Alternative mechanisms", "Generate different micro-level mechanisms capable of producing similar aggregate patterns and identify discriminating observations."), s("intervene", "Intervention implications", "Assess whether acting on individual components, interaction rules, network structure, or boundary conditions is most likely to change the macro outcome.")),
  "Path Dependence Analysis": w(s("outcome", "Current state", "Define the institutional, technological, strategic, or behavioral state whose history appears to constrain present options."), s("junctures", "Critical junctures", "Identify early choices, shocks, accidents, standards, or commitments that created diverging possible paths."), s("returns", "Increasing returns and lock-in", "Map learning, coordination, sunk costs, network effects, expectations, legal commitments, and complementary investments that reinforce the chosen path."), s("alternatives", "Foreclosed alternatives", "Identify plausible alternatives that became more expensive, illegitimate, incompatible, or forgotten as the path matured."), s("escape", "Path change", "Identify shocks, bridging technologies, compensation, coordinated switching, or policy interventions capable of overcoming lock-in.")),
};

export const SYSTEMS_DYNAMICS_SPECIFIC_CATALOG_WORKFLOW_COUNT = Object.keys(SYSTEMS_DYNAMICS_SPECIFIC_WORKFLOWS).length;
export const hasSystemsDynamicsSpecificCatalogWorkflow = (name: string): boolean => Boolean(SYSTEMS_DYNAMICS_SPECIFIC_WORKFLOWS[name]);
export const systemsDynamicsSpecificCatalogWorkflow = (name: string): TechniqueStepDefinition[] | undefined => SYSTEMS_DYNAMICS_SPECIFIC_WORKFLOWS[name]?.map((item) => ({ ...item }));