import type { TechniqueCategory, TechniqueDefinition, TechniqueFamily, TechniqueResponseKind, TechniqueStepDefinition } from "./types";
import { specificCatalogWorkflow } from "./techniquesCatalogWorkflows";

export type CatalogCluster = {
  family: TechniqueFamily;
  cluster: string;
  category: TechniqueCategory;
  purpose: string;
  focusAreas?: string[];
  names: string;
};

const step = (id: string, title: string, prompt: string, responseKind: TechniqueResponseKind = "long-text"): TechniqueStepDefinition => ({ id, title, prompt, responseKind });
const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const summaryFor = (name: string, purpose: string, steps: TechniqueStepDefinition[]): string => {
  const workflowPath = steps.slice(0, 4).map((item) => item.title).join(" → ");
  return `${name} uses a ${workflowPath} workflow to ${purpose}.`;
};

function workflow(category: TechniqueCategory, cluster: string): TechniqueStepDefinition[] {
  if (category === "contrarian") return [
    step("target", "Target judgment", "State the judgment, plan, assumption, or interpretation being challenged."),
    step("challenge", "Structured challenge", `Apply the method using the ${cluster} lens. Record the strongest challenge rather than an easy counterexample.`),
    step("counterevidence", "Counterevidence", "List evidence, mechanisms, or cases that support the challenge.", "list"),
    step("tests", "Discriminating tests", "What observations would distinguish the challenged view from the alternative?", "list"),
    step("revision", "Revision", "What should change in the judgment, confidence, caveats, or monitoring plan?"),
  ];
  if (category === "imaginative") return [
    step("focus", "Focus", "Define the question, system, actor, or future space to explore."),
    step("drivers", "Inputs and drivers", `Identify the important drivers, constraints, uncertainties, or dimensions relevant to ${cluster}.`, "list"),
    step("generate", "Generate alternatives", "Use the method to create distinct possibilities without collapsing them too early.", "list"),
    step("compare", "Compare", "Which alternatives are most plausible, consequential, surprising, or informative, and why?"),
    step("signposts", "Signposts and implications", "What indicators, implications, or next analytic moves follow?", "list"),
  ];
  if (category === "diagnostic") return [
    step("question", "Question or claim", "State exactly what is being examined, explained, estimated, or tested."),
    step("inputs", "Evidence and inputs", `Gather the evidence, observations, variables, cases, or source material required for ${cluster}.`, "list"),
    step("analysis", "Apply the method", "Work through the method explicitly. Record intermediate comparisons, classifications, patterns, or calculations rather than only the conclusion."),
    step("alternatives", "Alternatives and limitations", "What rival explanations, missing data, measurement problems, boundary choices, or method limitations could change the result?", "list"),
    step("judgment", "Judgment and confidence", "State the result, confidence, key reasons, and the next information that would most improve the assessment."),
  ];
  return [
    step("objective", "Objective", "State the decision, problem, process, or product this method will support."),
    step("criteria", "Inputs and criteria", `List the inputs, criteria, stakeholders, constraints, or alternatives relevant to ${cluster}.`, "list"),
    step("apply", "Apply the method", "Work through the method consistently and preserve the reasoning behind scores, rankings, choices, or observations."),
    step("sensitivity", "Sensitivity and tradeoffs", "Which assumptions, criteria, uncertainties, or tradeoffs most affect the result?"),
    step("decision", "Result and next action", "Record the result, rationale, residual uncertainty, and next action."),
  ];
}

export const CATALOG_CLUSTERS: ReadonlyArray<CatalogCluster> = [
  { family: "intelligence", cluster: "Framing & decomposition", category: "diagnostic", purpose: "decompose ambiguous problems, expose scope choices, and turn broad questions into analyzable parts", names: `Problem Restatement|Customer Checklist|Decomposition Tree|Logic Tree|Issue Tree|MECE Decomposition|Question Decomposition|Assumption Surfacing|Scope Boundary Matrix|Stakeholder Question Matrix|Key Intelligence Questions|Intelligence Requirements Mapping|Collection Gap Analysis|Problem Statement Canvas|Frame Analysis|Frame Shifting|Levels-of-Analysis Decomposition|Actor-Interest Matrix|Concept Mapping|Process Mapping` },
  { family: "intelligence", cluster: "Evidence & source evaluation", category: "diagnostic", purpose: "assess evidence quality, provenance, corroboration, independence, gaps, and collection effects", names: `Source Reliability Assessment|Information Credibility Assessment|Admiralty Code Evaluation|Source Validation Matrix|Corroboration Matrix|Evidence Grading|Evidence Provenance Mapping|Chain-of-Custody Analysis|Source Independence Check|Circular Reporting Check|Missing Evidence Analysis|Negative Evidence Analysis|Competing Source Reconciliation|Translation Ambiguity Review|Data Lineage Analysis|Collection Bias Audit|Sampling Bias Check|Recency and Relevance Audit|Confidence Calibration Worksheet|Evidence Triangulation` },
  { family: "intelligence", cluster: "Hypotheses & arguments", category: "diagnostic", purpose: "generate, map, compare, and stress-test explanations and the arguments that support them", names: `Hypothesis Mapping|Simple Hypothesis Testing|Quadrant Hypothesis Generation|Deductive Test Matrix|Inductive Pattern Assessment|Inference to the Best Explanation|Argument Structure Analysis|Toulmin Argument Model|Claim-Evidence-Reasoning Matrix|Counterevidence Matrix|Discriminating Evidence Matrix|Necessary and Sufficient Conditions Analysis|Consistency Testing|Coherence Testing|Rival Explanation Matrix|Evidence Diagnosticity Ranking|Hypothesis Sensitivity Analysis|Null Hypothesis Challenge|Anomaly Resolution Matrix` },
  { family: "intelligence", cluster: "Adversarial & cognitive challenge", category: "contrarian", purpose: "challenge prevailing judgments, cognitive habits, consensus pressure, influence environments, and unexamined assumptions", names: `Blue Team Review|Black Hat Review|Murder Board|Red Cell Exercise|Alternative Interpretation Challenge|Cognitive Bias Audit|Anchoring Challenge|Confirmation Bias Challenge|Availability Bias Challenge|Mirror-Imaging Check|Groupthink Check|Consensus Challenge|Dissent Capture|Devil's Proof|Steelmanning|Reversal Test|Precommitment Review|Assumption Reversal|Surprise Analysis|Propaganda Environment Analysis|Agitation–Integration Propaganda Analysis` },
  { family: "forecasting", cluster: "Scanning & trends", category: "diagnostic", purpose: "detect emerging change, characterize trends, and distinguish durable signals from transient noise", names: `Environmental Scanning|Horizon Scanning|STEEP Analysis|PESTLE Analysis|Trend Analysis|Trend Extrapolation|Trend Break Analysis|Emerging Issue Analysis|Weak Signal Analysis|Wild Card Analysis|Drivers of Change Analysis|Megatrend Analysis|Technology Scanning|Patent Landscaping|Bibliometric Trend Analysis|Signal-to-Noise Review|Leading Indicator Analysis|Lagging Indicator Analysis|Early Warning Dashboard Design` },
  { family: "forecasting", cluster: "Scenarios & futures", category: "imaginative", purpose: "construct and compare plausible futures, pathways, signposts, and robust responses under uncertainty", names: `Backcasting|Cone of Plausibility|Futures Wheel|Three Horizons|Causal Layered Analysis|2x2 Scenario Matrix|Branching Scenario Tree|Scenario Wind Tunneling|Scenario Stress Testing|Scenario Discovery|Scenario Archetypes|Normative Scenario Planning|Transformative Scenario Planning|Future History|Day-in-the-Life Scenario|Robust Strategy Across Scenarios|Signpost-to-Scenario Mapping` },
  { family: "forecasting", cluster: "Expert judgment & calibration", category: "other", purpose: "elicit, aggregate, calibrate, and diagnose expert forecasts and uncertain judgments", names: `Real-Time Delphi|Nominal Group Technique|Expert Elicitation|Structured Expert Judgment|Cooke's Classical Model|Probability Elicitation|Quantile Elicitation|Calibration Training|Brier Score Review|Superforecasting Tournament|Prediction Market Design|Wisdom-of-Crowds Aggregation|Independent Estimate Aggregation|Estimate-Talk-Estimate|Wideband Delphi|Paired Comparison Elicitation|Rank-Order Elicitation|Confidence Interval Elicitation|Consensus Mapping|Disagreement Decomposition` },
  { family: "decision", cluster: "Multi-criteria decision analysis", category: "other", purpose: "compare alternatives against explicit criteria, weights, priorities, and tradeoffs", names: `Analytic Hierarchy Process|Analytic Network Process|Weighted Sum Model|Weighted Product Model|TOPSIS|ELECTRE|PROMETHEE|VIKOR|SMART Decision Analysis|SMARTER|Swing Weighting|Multi-Attribute Utility Theory|Multi-Attribute Value Theory|Kepner-Tregoe Decision Analysis|Pugh Matrix|QFD House of Quality|MoSCoW Prioritization|RICE Scoring|WSJF Prioritization|Pairwise Comparison Matrix` },
  { family: "decision", cluster: "Uncertainty, utility & options", category: "other", purpose: "make choices explicit under uncertainty using utility, probability, robustness, sensitivity, optionality, bounded rationality, adaptive decision cycles, and asymmetric exposure", focusAreas: ["Utility & formal decision rules", "Sensitivity, robustness & simulation", "Optionality, exposure & rapid judgment"], names: `Expected Value Analysis|Expected Utility Analysis|Minimax Decision Rule|Maximin Decision Rule|Minimax Regret|Laplace Criterion|Hurwicz Criterion|Dominance Analysis|Stochastic Dominance|Sensitivity Analysis|Tornado Diagram Analysis|Threshold Analysis|Break-Even Analysis|Monte Carlo Simulation Review|Probability Tree Analysis|Influence Diagramming|Real Options Analysis|Robust Decision Making|Info-Gap Decision Theory|Portfolio Decision Analysis|Via Negativa Intervention Review|Serial Optionality Review|Barbell Exposure Analysis|OODA Decision-Cycle Analysis|Bounded Rationality / Satisficing Audit|Recognition-Primed Decision Audit` },
  { family: "systems", cluster: "System dynamics & complexity", category: "diagnostic", purpose: "analyze feedback, accumulation, delays, nonlinear behavior, emergence, technical autonomy, regulation, and leverage in complex systems", focusAreas: ["Feedback, accumulation & archetypes", "Simulation, emergence & path dependence", "Control, autonomy & system governance"], names: `Stock-and-Flow Mapping|System Archetype Analysis|Iceberg Model|Leverage Points Analysis|Reinforcing Loop Analysis|Balancing Loop Analysis|Delay Analysis|Limits to Growth Analysis|Shifting the Burden Analysis|Fixes That Fail Analysis|Success to the Successful Analysis|Tragedy of the Commons Analysis|Escalation Archetype Analysis|Growth and Underinvestment Analysis|System Dynamics Simulation Design|Agent-Based Model Framing|Emergent Behavior Analysis|Path Dependence Analysis|Tipping Point Analysis|Efficiency Imperative Audit|Technological System Autonomy Analysis|Requisite Variety Analysis|Viable System Model Diagnosis` },
  { family: "systems", cluster: "Networks & relationships", category: "diagnostic", purpose: "analyze relational structure, influence, brokerage, clustering, diffusion, dependency, and network resilience", names: `Social Network Analysis|Link Analysis|Ego Network Analysis|Centrality Analysis|Betweenness Centrality Review|Community Detection|Clique Analysis|Broker and Gatekeeper Analysis|Two-Mode Network Analysis|Multiplex Network Analysis|Temporal Network Analysis|Diffusion Network Analysis|Influence Network Mapping|Dependency Mapping|Supply Network Mapping|Value Network Analysis|Stakeholder Network Mapping|Relationship Strength Matrix|Structural Hole Analysis|Network Resilience Analysis` },
  { family: "safety", cluster: "Risk, hazard & resilience", category: "contrarian", purpose: "identify failure pathways, hazards, tail exposure, barrier weaknesses, accident mechanisms, interactive complexity, fragility, and resilience requirements", focusAreas: ["Hazards, barriers & tolerability", "Accident mechanisms & organizational causes", "Resilience, fragility & complex-system failure"], names: `Preliminary Hazard Analysis|Hazard Identification Study|Hazard and Operability Study|What-If Hazard Review|What-If/Checklist Analysis|Layers of Protection Analysis|Safety Integrity Level Review|Event Sequence Analysis|Cause-Consequence Analysis|Barrier Analysis|Swiss Cheese Analysis|Risk Matrix Analysis|ALARP Assessment|Resilience Engineering Review|Systems-Theoretic Process Analysis|AcciMap|Functional Resonance Analysis Method|Management Oversight and Risk Tree Analysis|Tripod Beta|Business Impact Analysis|Fragility / Antifragility Stress Test|Fat-Tail Exposure Audit|Interactive Complexity / Tight-Coupling Audit` },
  { family: "quality", cluster: "Process, root cause & improvement", category: "diagnostic", purpose: "find process causes, measure variation, detect metric distortion, improve flow, and design durable corrective action", names: `DMAIC|DMADV|A3 Problem Solving|Kaizen Event Analysis|Value Stream Mapping|Process Capability Analysis|Control Chart Analysis|Statistical Process Control|Measurement System Analysis|Gage R&R|Design of Experiments|Taguchi Method|Poka-Yoke Analysis|Standard Work Analysis|Takt Time Analysis|Bottleneck Analysis|Theory of Constraints|Current Reality Tree|Future Reality Tree|Evaporating Cloud|Goodhart–Campbell Metric Gaming Audit` },
  { family: "research", cluster: "Qualitative analysis", category: "diagnostic", purpose: "code, compare, interpret, and explain patterned meaning in interviews, documents, observations, and cases", names: `Thematic Analysis|Reflexive Thematic Analysis|Framework Analysis|Qualitative Content Analysis|Grounded Theory Coding|Open Coding|Axial Coding|Selective Coding|Constant Comparative Method|Narrative Analysis|Conversation Analysis|Critical Discourse Analysis|Interpretative Phenomenological Analysis|Phenomenological Reduction|Ethnographic Analysis|Domain Analysis|Taxonomic Analysis|Componential Analysis|Template Analysis|Directed Content Analysis` },
  { family: "research", cluster: "Quantitative & statistical analysis", category: "diagnostic", purpose: "characterize data, estimate relationships, identify structure, detect change, and quantify uncertainty", names: `Descriptive Statistics Review|Exploratory Data Analysis|Distribution Analysis|Outlier Analysis|Correlation Analysis|Partial Correlation|Regression Analysis|Logistic Regression|Multilevel Modeling|Time-Series Analysis|Interrupted Time-Series Analysis|Survival Analysis|Cluster Analysis|Principal Component Analysis|Factor Analysis|Discriminant Analysis|Correspondence Analysis|Latent Class Analysis|Change-Point Detection|Statistical Power Analysis` },
  { family: "research", cluster: "Causal inference & experiments", category: "diagnostic", purpose: "distinguish causal effects and mechanisms from association, confounding, selection, and rival explanations", names: `Causal Diagramming with DAGs|Backdoor Criterion Review|Front-Door Criterion Review|Propensity Score Matching|Inverse Probability Weighting|Difference-in-Differences|Regression Discontinuity|Instrumental Variables|Synthetic Control|Matching Analysis|Natural Experiment Analysis|Randomized Controlled Trial Design|A/B Test Design|Factorial Experiment Design|Quasi-Experimental Design|Mediation Analysis|Moderation Analysis|Mechanism Mapping|Process Tracing|Contribution Analysis` },
  { family: "research", cluster: "Evidence synthesis & literature", category: "diagnostic", purpose: "systematically locate, compare, synthesize, map, and evaluate bodies of research and evidence", names: `Systematic Review|Scoping Review|Rapid Review|Umbrella Review|Meta-Analysis|Network Meta-Analysis|Meta-Regression|Evidence Mapping|Evidence Gap Map|Best Evidence Synthesis|Realist Review|Meta-Ethnography|Qualitative Evidence Synthesis|Critical Interpretive Synthesis|Narrative Synthesis|Bibliometric Analysis|Co-Citation Analysis|Co-Word Analysis|Citation Network Analysis|Snowball Search Strategy` },
  { family: "design", cluster: "Human-centered design & innovation", category: "imaginative", purpose: "understand user needs, reframe opportunities, generate concepts, and compare design alternatives", names: `Empathy Mapping|Persona Analysis|Jobs-to-be-Done Analysis|Contextual Inquiry|Diary Study Analysis|Critical Incident Technique|Service Blueprinting|Customer Journey Mapping|Experience Mapping|Story Mapping|Opportunity Solution Tree|How-Might-We Framing|SCAMPER|TRIZ|Six Thinking Hats|Design Studio|Crazy Eights|Concept Screening|Concept Scoring|Kano Analysis` },
  { family: "security", cluster: "Threat, cyber & investigative analysis", category: "contrarian", purpose: "structure adversary, incident, evidence, timeline, behavior, and defensive analysis without assuming a single threat pathway", names: `PASTA Threat Modeling|LINDDUN Privacy Threat Modeling|Attack Surface Analysis|Abuse Case Analysis|Misuse Case Analysis|Threat Actor Profiling|TTP Mapping|Kill Chain Analysis|Diamond Model Analysis|MITRE ATT&CK Mapping|Cyber Kill Chain Mapping|Indicator of Compromise Analysis|Timeline Forensics|Artifact Correlation|Event Correlation|Root Cause Security Analysis|Incident Reconstruction|Hypothesis-Driven Investigation|Link Charting|Pattern-of-Life Analysis` },
  { family: "policy", cluster: "Policy appraisal & implementation", category: "other", purpose: "compare policy options, impacts, implementation constraints, incentive alignment, governance structure, administrative simplification, institutional feedback, distributional effects, and theories of change", names: `Regulatory Impact Assessment|Cost-Benefit Analysis|Cost-Effectiveness Analysis|Distributional Impact Analysis|Policy Options Appraisal|Logic Model|Theory of Change|Stakeholder Consultation Analysis|Implementation Feasibility Analysis|Policy Coherence Analysis|Skin-in-the-Game Incentive Audit|Commons Governance Design Audit|Polycentric Governance Analysis|Legibility / Local-Knowledge Audit|Exit–Voice–Loyalty Analysis` },
  { family: "economics", cluster: "Economic reasoning & markets", category: "diagnostic", purpose: "analyze incentives, strategic interaction, coordination, tradeoffs, market structure, responses to change, and economy-wide relationships", names: `Supply-Demand Analysis|Elasticity Analysis|Marginal Analysis|Opportunity Cost Analysis|Welfare Analysis|Market Structure Analysis|Game-Theoretic Payoff Matrix|Input-Output Analysis|Comparative Statics|Economic Scenario Analysis|Strategic Commitment Analysis|Focal-Point Coordination Analysis` },
  { family: "geospatial", cluster: "Spatial patterns & terrain", category: "diagnostic", purpose: "analyze spatial concentration, proximity, accessibility, terrain, network structure, and change across geography", names: `Hot Spot Analysis|Kernel Density Estimation|Spatial Autocorrelation Analysis|Moran's I Analysis|Getis-Ord Gi* Analysis|Viewshed Analysis|Least-Cost Path Analysis|Spatial Network Analysis|Site Suitability Analysis|Spatial Change Detection` },
  { family: "legal", cluster: "Legal reasoning & interpretation", category: "diagnostic", purpose: "structure legal issues, synthesize authority, interpret rules, compare precedent, and test application to facts", names: `IRAC Analysis|CREAC Analysis|Statutory Interpretation Analysis|Precedent Synthesis|Analogical Legal Reasoning|Rule Synthesis|Elements Analysis|Proportionality Analysis|Balancing Test Analysis|Legal Issue Spotting` },
  { family: "operations-research", cluster: "Optimization, simulation & operations", category: "other", purpose: "optimize constrained choices, model queues and stochastic systems, and compare operational policies", names: `Linear Programming|Integer Programming|Goal Programming|Queueing Analysis|Discrete-Event Simulation|Markov Chain Analysis|Dynamic Programming|Transportation Model|Assignment Model|Inventory Model` },
  { family: "literary", cluster: "Language, discourse & media", category: "diagnostic", purpose: "analyze language, rhetoric, discourse, symbols, genre, media form, and patterned textual choices", names: `Rhetorical Criticism|Genre Criticism|Stylistic Analysis|Corpus Linguistics Analysis|Concordance Analysis|Collocation Analysis|Keyword Analysis|Semantic Field Analysis|Metaphor Analysis|Conceptual Metaphor Analysis|Speech Act Analysis|Pragmatic Analysis|Conversation Repair Analysis|Narrative Positioning Analysis|Framing Analysis|Critical Media Analysis|Visual Rhetoric Analysis|Multimodal Discourse Analysis|Semiotic Analysis|Interdiscursivity Analysis` },
  { family: "religious-studies", cluster: "Historical, comparative & interpretive methods", category: "diagnostic", purpose: "analyze traditions, texts, practices, historical development, comparison, and interpretation with explicit evidentiary controls", names: `Historical Method|Source Criticism|Internal Criticism|External Criticism|Contextualization|Comparative Historical Analysis|Prosopography|Genealogical Analysis|Microhistory|Oral History Analysis|Tradition-Historical Analysis|Canonical Criticism|Sociological Criticism|Anthropological Criticism|Feminist Hermeneutics|Postcolonial Hermeneutics|Liberationist Interpretation|Comparative Theology|Phenomenology of Religion|Cognitive Science of Religion Analysis` },
];

export const CATALOG_BUILT_IN_TECHNIQUES: TechniqueDefinition[] = CATALOG_CLUSTERS.flatMap((group) =>
  group.names.split("|").map((name) => {
    const steps = specificCatalogWorkflow(name) ?? workflow(group.category, group.cluster);
    return {
      id: `builtin:catalog-${group.family}-${slugify(name)}`,
      name,
      summary: summaryFor(name, group.purpose, steps),
      category: group.category,
      family: group.family,
      cluster: group.cluster,
      builtIn: true,
      version: 1,
      steps,
      createdAt: null,
      updatedAt: null,
    };
  }),
);
