import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";
const s=(id:string,title:string,prompt:string,responseKind:TechniqueResponseKind="long-text"):TechniqueStepDefinition=>({id,title,prompt,responseKind}); const w=(...steps:TechniqueStepDefinition[])=>steps;
export const OPERATIONS_RESEARCH_SPECIFIC_WORKFLOWS:Record<string,TechniqueStepDefinition[]>={
  "Integer Programming":w(s("objective","Objective","Define the quantity to optimize and the decision horizon."),s("variables","Integer decisions","Define binary or integer variables and what each represents."),s("constraints","Constraints","Encode logical, capacity, resource, sequencing, and policy constraints."),s("solve","Solve and inspect","Find feasible and optimal or near-optimal solutions and inspect binding constraints."),s("sensitivity","Sensitivity","Test coefficient, bound, and integrality assumptions and identify fragile decisions.")),
  "Goal Programming":w(s("goals","Goals","Define multiple goals, target levels, and units."),s("priorities","Priority structure","Assign lexicographic priorities or defensible weights and define acceptable deviations."),s("model","Deviation model","Create decision variables, constraints, and positive/negative deviation variables."),s("solve","Solve compromise","Minimize prioritized deviations and inspect which goals remain unmet."),s("review","Tradeoff review","Test alternative priorities or targets and explain the resulting tradeoffs.")),
  "Discrete-Event Simulation":w(s("system","System boundary","Define entities, resources, queues, events, routing, and performance measures."),s("inputs","Input distributions","Estimate arrival, service, failure, and routing distributions with data-quality caveats."),s("logic","Event logic","Specify state transitions, priorities, schedules, and resource rules."),s("experiment","Simulation experiments","Run replications, warm-up, scenarios, and sensitivity tests with uncertainty intervals."),s("validate","Validation","Compare simulated behavior with real or expected system behavior before drawing conclusions.")),
  "Markov Chain Analysis":w(s("states","States","Define mutually interpretable system states and time step."),s("transitions","Transition probabilities","Estimate or elicit transition probabilities and check row consistency and stationarity assumptions."),s("evolve","State evolution","Compute multi-step distributions, absorbing behavior, or steady state as relevant."),s("sensitivity","Sensitivity","Test alternate transition matrices and structural breaks."),s("interpret","Interpretation","Translate probabilities into operational implications without implying memoryless dynamics where unsupported.")),
  "Dynamic Programming":w(s("state","State definition","Define the state variables that summarize all information needed for future decisions."),s("actions","Actions and transitions","Define feasible actions, state transitions, rewards/costs, and horizon."),s("recursion","Bellman recursion","Formulate the stagewise value relation and terminal conditions."),s("solve","Solve policy","Compute an optimal policy by backward induction or suitable approximation."),s("robust","Robustness","Test horizon, transition, reward, and state-space assumptions.")),
  "Transportation Model":w(s("network","Origins and destinations","Define supply nodes, demand nodes, shipment units, and route costs."),s("balance","Supply-demand balance","Check totals, add dummy nodes if appropriate, and preserve prohibited routes."),s("model","Transportation model","Formulate shipment variables, conservation constraints, and objective."),s("solve","Solve allocation","Find a minimum-cost feasible shipping plan and inspect capacity or route bottlenecks."),s("sensitivity","Sensitivity","Test cost, supply, demand, and route-disruption changes.")),
  "Assignment Model":w(s("agents","Agents and tasks","Define the entities to assign, tasks, eligibility, and performance/cost metric."),s("matrix","Assignment matrix","Construct one-to-one or capacity-adjusted costs/benefits and prohibited matches."),s("solve","Optimal assignment","Solve for the best feasible matching under assignment constraints."),s("interpret","Interpretation","Inspect high-cost pairings, unused capacity, and ties rather than treating the optimum as self-explanatory."),s("sensitivity","Sensitivity","Test score uncertainty, new constraints, and reassignments.")),
  "Inventory Model":w(s("item","Inventory system","Define item, demand process, replenishment lead time, review policy, and service objective."),s("costs","Cost structure","Estimate ordering/setup, holding, shortage, obsolescence, and stockout costs."),s("policy","Policy parameters","Calculate or simulate order quantity, reorder point, safety stock, or base-stock levels."),s("uncertainty","Demand and lead-time uncertainty","Test variability, seasonality, disruptions, and service-level tradeoffs."),s("monitor","Operating policy","Define replenishment rules, exception triggers, and recalibration cadence.")),
};
export const OPERATIONS_RESEARCH_SPECIFIC_CATALOG_WORKFLOW_COUNT=Object.keys(OPERATIONS_RESEARCH_SPECIFIC_WORKFLOWS).length;
export const hasOperationsResearchSpecificCatalogWorkflow=(name:string)=>Boolean(OPERATIONS_RESEARCH_SPECIFIC_WORKFLOWS[name]);
export const operationsResearchSpecificCatalogWorkflow=(name:string)=>OPERATIONS_RESEARCH_SPECIFIC_WORKFLOWS[name]?.map(x=>({...x}));