import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";

const s = (id: string, title: string, prompt: string, responseKind: TechniqueResponseKind = "long-text"): TechniqueStepDefinition => ({ id, title, prompt, responseKind });
const w = (...steps: TechniqueStepDefinition[]) => steps;

export const SECURITY_SPECIFIC_WORKFLOWS: Record<string, TechniqueStepDefinition[]> = {
  "LINDDUN Privacy Threat Modeling": w(s("scope", "System and privacy scope", "Define the system, personal-data processing, actors, trust boundaries, and privacy objectives."), s("dfd", "Data-flow model", "Model external entities, processes, data stores, data flows, and relevant trust boundaries before eliciting threats."), s("interactions", "Interaction-by-interaction threats", "For each sending, transfer, and receiving interaction, examine linking, identifying, non-repudiation, detecting, disclosure, unawareness/unintervenability, and non-compliance threats."), s("risk", "Risk and affected parties", "Assess impact, exploitability, scale, affected data subjects, and uncertainty for each material privacy threat."), s("mitigate", "Mitigations and traceability", "Link mitigations to specific threats and interactions, record residual privacy risk, and preserve traceability to the model.")),
  "Attack Surface Analysis": w(s("system", "System and assets", "Define assets, entry points, trust boundaries, identities, interfaces, data stores, and exposed dependencies."), s("exposure", "Exposed attack surface", "Inventory reachable services, APIs, protocols, user inputs, credentials, administrative paths, physical interfaces, and supply-chain dependencies."), s("paths", "Likely attack paths", "Connect exposures to assets through required access, privileges, weaknesses, and trust transitions."), s("change", "Change and drift", "Identify new exposure created by configuration changes, integrations, privileges, remote access, cloud resources, or abandoned components."), s("reduce", "Reduction priorities", "Prioritize removal, isolation, hardening, monitoring, and privilege reduction based on reachable impact and attacker effort.")),
  "Abuse Case Analysis": w(s("asset", "Asset and legitimate use", "State the system function, actor goal, and normal use that could be abused."), s("misuse", "Abuse goals", "Generate harmful goals that misuse intended features, permissions, workflows, or business logic rather than requiring software exploitation."), s("scenario", "Abuse scenarios", "Describe actor, preconditions, sequence, target, impact, and observable behavior for each high-value abuse case."), s("controls", "Current controls", "Identify preventive, detective, rate-limiting, authorization, policy, and recovery controls relevant to each scenario."), s("gaps", "Control gaps and tests", "Identify unmitigated abuse paths, monitoring gaps, and concrete tests or requirements to reduce them.")),
  "Misuse Case Analysis": w(s("usecases", "Use cases and actors", "Identify important legitimate use cases, actors, assets, and trust assumptions."), s("misusers", "Misuser goals", "Define malicious or inappropriate goals that oppose, subvert, or parasitize the legitimate use cases."), s("relations", "Misuse-use relationships", "Map which misuse cases threaten, include, or exploit which legitimate use cases and under what preconditions."), s("requirements", "Security requirements", "Derive prevention, detection, authorization, resilience, and audit requirements from the mapped misuse relationships."), s("validate", "Validation", "Test whether the derived requirements actually block or reveal the high-priority misuse cases without breaking essential use.")),
  "TTP Mapping": w(s("observations", "Observed behavior", "Extract concrete adversary behaviors, tools, access patterns, procedures, and artifacts from evidence before applying labels."), s("map", "Tactic-technique-procedure map", "Map observations to tactics, techniques, procedures, and sub-techniques at the most specific level justified by evidence."), s("provenance", "Evidence provenance", "Preserve source, timestamp, confidence, and ambiguity for every mapped behavior and avoid upgrading inference to observation."), s("patterns", "Behavioral pattern", "Identify recurring combinations, sequencing, preferences, and deviations that characterize the activity beyond single indicators."), s("use", "Analytic use", "Derive detection gaps, adjacent behaviors, collection priorities, and attribution-relevant similarities while preserving uncertainty.")),
  "Kill Chain Analysis": w(s("objective", "Adversary objective", "Define the campaign or intrusion objective and the defended environment."), s("stages", "Attack stages", "Map observed or hypothesized activity across reconnaissance, preparation, access, execution, persistence, command/control, and actions on objectives using the chosen kill-chain model."), s("dependencies", "Stage dependencies", "Identify prerequisites, transitions, and alternative paths; do not force every incident into a perfectly linear sequence."), s("controls", "Control coverage", "Map preventive, detective, and response controls to stages and identify where one missed stage leaves downstream opportunities."), s("break", "Disruption priorities", "Select the earliest and most reliable points to deny, detect, degrade, or contain the campaign and define evidence needed to confirm disruption.")),
  "Cyber Kill Chain Mapping": w(s("campaign", "Campaign scope", "Define the intrusion set, victims, time window, and evidence boundary."), s("phases", "Cyber kill-chain phases", "Map evidence to reconnaissance, weaponization, delivery, exploitation, installation, command and control, and actions on objectives, preserving gaps."), s("alternatives", "Alternative paths", "Record skipped, repeated, parallel, outsourced, or cloud-native paths that do not fit a strict linear progression."), s("defense", "Detection and prevention", "Map controls, telemetry, and opportunities to interrupt each phase and distinguish missing telemetry from absent behavior."), s("lessons", "Campaign lessons", "Identify recurring weak points, high-value choke points, and phase transitions that deserve future collection or hardening.")),
  "Indicator of Compromise Analysis": w(s("indicator", "Indicator and context", "Define the observable, its source, time window, system context, and why it was considered suspicious."), s("quality", "Indicator quality", "Assess specificity, stability, false-positive rate, adversary control, age, and whether the indicator is merely correlated with malicious activity."), s("correlate", "Corroboration", "Correlate the indicator with independent logs, behaviors, assets, identities, and timeline evidence rather than treating a match as proof."), s("scope", "Scope and prevalence", "Determine where else the indicator appears, whether occurrence is benign, and what related infrastructure or activity may be discoverable."), s("action", "Disposition", "Classify as high-confidence, contextual, weak, obsolete, or false positive and define detection, blocking, hunting, and expiration rules.")),
  "Timeline Forensics": w(s("scope", "Evidence scope", "Define systems, accounts, clocks, sources, and the incident window."), s("normalize", "Normalize time", "Convert timestamps to a common reference, record timezone and clock skew, and preserve original timestamps."), s("events", "Event timeline", "Order relevant events with source provenance and confidence, including gaps and contradictory timestamps."), s("sequence", "Sequence and causality", "Separate temporal adjacency from causal dependence and identify candidate chains, parallel activity, and impossible sequences."), s("findings", "Findings and gaps", "State supported sequences, uncertain intervals, and the evidence most likely to resolve remaining ambiguity.")),
  "Artifact Correlation": w(s("artifacts", "Artifact set", "List relevant files, hashes, logs, registry entries, memory artifacts, network data, identities, and metadata with provenance."), s("keys", "Correlation keys", "Identify stable join points such as timestamps, hosts, users, process IDs, paths, hashes, domains, IPs, session IDs, or transaction IDs."), s("relations", "Cross-artifact relationships", "Link artifacts only where keys and timing support the relationship, and record alternative explanations for ambiguous matches."), s("patterns", "Correlated pattern", "Identify sequences, repeated infrastructure, shared tooling, persistence, privilege transitions, or victim overlap emerging across artifact types."), s("confidence", "Confidence and next collection", "Assess which relationships are strong, circumstantial, or unresolved and identify the highest-value missing artifact.")),
  "Event Correlation": w(s("streams", "Event streams", "Define log sources, schemas, clocks, retention, and the analytic time window."), s("rules", "Correlation logic", "Define time, entity, sequence, threshold, or causal rules used to associate events and document why they should co-occur."), s("candidate", "Candidate incidents", "Group events into candidate incidents while preserving unmatched events and avoiding over-aggregation from noisy identifiers."), s("validate", "Validate correlations", "Check source independence, timestamp quality, duplicate reporting, benign workflows, and whether the correlated pattern has a plausible mechanism."), s("output", "Incident-level output", "Produce bounded incident hypotheses with confidence, supporting events, contradictory evidence, and collection needs.")),
  "Root Cause Security Analysis": w(s("incident", "Security failure", "Define the observed compromise, control failure, or exposure without embedding a preferred cause."), s("causes", "Contributing causes", "Separate triggering events, technical weaknesses, identity and access failures, process gaps, organizational conditions, and external dependencies."), s("verify", "Verify mechanisms", "For each candidate cause, identify evidence that demonstrates how it enabled or failed to prevent the incident."), s("systemic", "Systemic conditions", "Identify incentives, ownership gaps, monitoring limitations, architectural debt, or recurring conditions that make recurrence likely."), s("actions", "Corrective actions", "Link corrective actions to verified causes and define tests showing the fixes remove or contain the causal pathway.")),
  "Hypothesis-Driven Investigation": w(s("question", "Investigative question", "Define the bounded question and avoid embedding the suspected answer."), s("hypotheses", "Competing hypotheses", "Generate plausible malicious, benign, procedural, and data-quality explanations before collecting only confirmatory evidence.", "list"), s("predictions", "Observable implications", "State what should be observed under each hypothesis and which observations would discriminate among them."), s("collect", "Targeted collection", "Prioritize logs, artifacts, interviews, queries, or experiments with the highest expected diagnostic value."), s("update", "Update and closure", "Revise relative support as evidence arrives, preserve unresolved alternatives, and define closure criteria.")),
  "Link Charting": w(s("entities", "Entities", "Define people, accounts, devices, organizations, locations, infrastructure, or artifacts included in the chart.", "list"), s("links", "Relationships", "Add typed, directed relationships with source, time, confidence, and meaning rather than unlabeled lines."), s("structure", "Structural patterns", "Identify clusters, brokers, shared resources, temporal changes, isolated nodes, and suspiciously dense or sparse regions."), s("validate", "Validate important links", "Check whether central or surprising links reflect independent evidence, duplicated reporting, common infrastructure, or coincidental identifiers."), s("implications", "Investigative implications", "Generate bounded hypotheses, collection priorities, and candidate pivots without treating visual proximity as proof of association.")),
};

export const SECURITY_SPECIFIC_CATALOG_WORKFLOW_COUNT = Object.keys(SECURITY_SPECIFIC_WORKFLOWS).length;
export const hasSecuritySpecificCatalogWorkflow = (name: string): boolean => Boolean(SECURITY_SPECIFIC_WORKFLOWS[name]);
export const securitySpecificCatalogWorkflow = (name: string): TechniqueStepDefinition[] | undefined => SECURITY_SPECIFIC_WORKFLOWS[name]?.map((item) => ({ ...item }));