import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";
const s=(id:string,title:string,prompt:string,responseKind:TechniqueResponseKind="long-text"):TechniqueStepDefinition=>({id,title,prompt,responseKind});
const w=(...steps:TechniqueStepDefinition[])=>steps;
export const RESEARCH_SYNTHESIS_SPECIFIC_WORKFLOWS: Record<string, TechniqueStepDefinition[]> = {
  "Scoping Review": w(s("question","Review scope","Define the broad question, concepts, populations, contexts, and intended map of the field."),s("search","Search coverage","Design a transparent broad search across relevant databases, grey literature, and supplementary sources."),s("screen","Eligibility and charting","Apply inclusion criteria and chart study characteristics consistently."),s("map","Evidence map","Describe concepts, methods, populations, and concentrations or gaps without overstating effect strength."),s("report","Interpretation","State what the field contains, where uncertainty remains, and what synthesis or research should follow.")),
  "Rapid Review": w(s("decision","Decision need","Define the time-critical decision and the minimum evidence question needed."),s("streamline","Streamlining choices","Document deliberate shortcuts in searching, screening, appraisal, or synthesis and their likely bias."),s("search","Focused search","Search the highest-yield sources transparently within the time constraint."),s("synthesize","Rapid synthesis","Summarize findings and quality with clear separation of evidence from inference."),s("limits","Decision caveats","State what may have been missed and how the shortcuts constrain confidence.")),
  "Umbrella Review": w(s("scope","Review-of-reviews question","Define interventions, exposures, outcomes, populations, and eligible review types."),s("reviews","Review set","Identify relevant systematic reviews and assess overlap among their primary studies."),s("quality","Review quality","Appraise methodological quality, recency, and certainty of each review."),s("compare","Cross-review comparison","Compare conclusions, heterogeneity, discordance, and duplicate evidence."),s("synthesis","Overview conclusion","Summarize the strongest conclusions and unresolved conflicts without double counting evidence.")),
  "Network Meta-Analysis": w(s("network","Treatment network","Define interventions, comparators, outcomes, and the connected evidence network."),s("assumptions","Transitivity and consistency","Assess whether effect modifiers are sufficiently comparable and direct/indirect evidence can be combined."),s("model","Network model","Estimate relative effects across the network using an appropriate fixed or random effects model."),s("diagnostics","Inconsistency diagnostics","Check local and global inconsistency, heterogeneity, and influential studies."),s("rank","Interpretation and ranking","Report relative effects and ranking uncertainty without treating rank order as certainty.")),
  "Meta-Regression": w(s("question","Moderator question","Define the study-level effect and candidate moderators before analysis."),s("data","Effect and moderator data","Extract comparable effect estimates, uncertainty, and moderator variables."),s("model","Meta-regression model","Estimate moderator relationships with appropriate weighting and random-effects structure."),s("checks","Robustness checks","Assess leverage, collinearity, multiplicity, residual heterogeneity, and sparse categories."),s("interpret","Ecological limits","Interpret moderators cautiously and distinguish study-level association from individual-level causation.")),
  "Evidence Gap Map": w(s("scope","Evidence framework","Define intervention/exposure and outcome dimensions plus study-design eligibility."),s("search","Systematic search","Search and screen transparently enough to characterize the evidence landscape."),s("code","Structured coding","Code studies by framework cells, design, population, geography, and quality markers."),s("map","Gap map","Display evidence concentrations and sparse cells without equating study count with evidence strength."),s("prioritize","Gap interpretation","Identify decision-relevant gaps, redundant research areas, and priorities for synthesis or new studies.")),
  "Best Evidence Synthesis": w(s("question","Synthesis question","Define the substantive question and criteria for evidentiary relevance."),s("quality","Evidence hierarchy","Assess methodological quality and relevance rather than treating all studies equally."),s("pattern","Consistent findings","Identify patterns among the strongest studies and reasons lower-quality evidence diverges."),s("exceptions","Contradictions","Examine robust contrary findings and plausible methodological explanations."),s("conclusion","Weighted conclusion","State the conclusion driven by the best evidence and where uncertainty still matters.")),
  "Meta-Ethnography": w(s("focus","Interpretive focus","Define the phenomenon and qualitative studies to be synthesized."),s("concepts","First- and second-order concepts","Extract participant meanings and authors' interpretations from each study."),s("translate","Reciprocal and refutational translation","Compare how concepts translate across studies, including contradictions."),s("synthesis","Line-of-argument synthesis","Build a higher-order interpretation that explains relations among studies."),s("reflexivity","Reflexive limits","Document how selection and interpretation shaped the synthesis.")),
  "Qualitative Evidence Synthesis": w(s("question","Synthesis question","Define the experience, implementation, acceptability, or contextual question."),s("studies","Study selection and appraisal","Identify relevant qualitative studies and assess methodological limitations."),s("coding","Cross-study coding","Code findings across studies while preserving context and provenance."),s("themes","Synthesis themes","Develop descriptive and analytic themes, including disconfirming cases."),s("confidence","Confidence in findings","State confidence in each synthesized finding and the contexts in which it applies.")),
  "Critical Interpretive Synthesis": w(s("problem","Problematic literature","Define the contested concept or body of literature requiring critical reinterpretation."),s("sample","Theoretical sampling","Iteratively select literature for conceptual contribution rather than exhaustiveness alone."),s("critique","Critical reading","Interrogate assumptions, categories, methods, and contradictions across sources."),s("construct","Synthetic constructs","Develop new concepts that explain or reorganize the literature."),s("argument","Synthesizing argument","Present the higher-order argument and where alternative interpretations remain viable.")),
  "Narrative Synthesis": w(s("question","Review question","Define the intervention, phenomenon, outcomes, and study differences relevant to synthesis."),s("organize","Organize evidence","Group studies by design, intervention, population, mechanism, or another justified structure."),s("patterns","Explore relationships","Compare direction, magnitude, context, and study quality to explain patterns and heterogeneity."),s("robustness","Assess robustness","Test whether conclusions depend on weak studies, selective reporting, or arbitrary grouping."),s("story","Narrative conclusion","Produce a transparent narrative linking evidence to conclusions without vote counting.")),
  "Bibliometric Analysis": w(s("corpus","Bibliographic corpus","Define databases, query, period, fields, and deduplication rules."),s("metrics","Bibliometric measures","Analyze output, citations, authors, institutions, journals, and normalized impact where appropriate."),s("networks","Bibliometric networks","Construct coauthorship, citation, co-citation, or keyword networks suited to the question."),s("bias","Coverage bias","Assess database, language, field-age, and citation-lag biases."),s("interpret","Field structure","Interpret growth, influence, collaboration, and intellectual structure without equating citation with quality.")),
  "Co-Citation Analysis": w(s("corpus","Citation corpus","Define the source set and citation window."),s("pairs","Co-citation matrix","Count how often pairs of works, authors, or journals are cited together."),s("structure","Cluster structure","Identify communities and central references using explicit thresholds or normalization."),s("time","Temporal change","Compare how co-citation structure evolves as the field changes."),s("meaning","Intellectual interpretation","Interpret clusters substantively and check whether data coverage distorts apparent schools of thought.")),
  "Co-Word Analysis": w(s("corpus","Text and keyword corpus","Define documents, fields, preprocessing, and term normalization."),s("matrix","Co-occurrence matrix","Measure term co-occurrence using a consistent unit and normalization."),s("clusters","Concept clusters","Identify thematic clusters and bridges among concepts."),s("evolution","Theme evolution","Track emergence, decline, and recombination of themes over time."),s("validate","Semantic validation","Inspect source texts to verify that statistical proximity reflects meaningful conceptual association.")),
  "Citation Network Analysis": w(s("network","Citation network","Define nodes, directed citation edges, time window, and document types."),s("structure","Network structure","Assess components, paths, centrality, communities, and citation flows."),s("lineage","Intellectual lineage","Trace influential chains and branching schools while accounting for age and field effects."),s("anomalies","Citation anomalies","Inspect self-citation, review-article dominance, missing records, and retracted or disputed sources."),s("interpret","Network interpretation","State what the citation structure suggests and what it cannot establish about quality or truth.")),
  "Snowball Search Strategy": w(s("seeds","Seed set","Select high-relevance seed studies with transparent inclusion rationale."),s("backward","Backward chaining","Review reference lists to identify earlier relevant evidence."),s("forward","Forward chaining","Use citation indexes to identify later studies citing the seeds."),s("iterate","Iterative saturation","Repeat chaining from newly included high-value studies until marginal yield becomes low."),s("record","Audit trail","Record seed choices, databases, iterations, inclusions, and biases introduced by citation-network dependence.")),
};
export const RESEARCH_SYNTHESIS_SPECIFIC_CATALOG_WORKFLOW_COUNT=Object.keys(RESEARCH_SYNTHESIS_SPECIFIC_WORKFLOWS).length;
export const hasResearchSynthesisSpecificCatalogWorkflow=(name:string)=>Boolean(RESEARCH_SYNTHESIS_SPECIFIC_WORKFLOWS[name]);
export const researchSynthesisSpecificCatalogWorkflow=(name:string)=>RESEARCH_SYNTHESIS_SPECIFIC_WORKFLOWS[name]?.map(x=>({...x}));