import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";

const s = (id: string, title: string, prompt: string, responseKind: TechniqueResponseKind = "long-text"): TechniqueStepDefinition => ({ id, title, prompt, responseKind });
const w = (...steps: TechniqueStepDefinition[]) => steps;

export const DECISION_UNCERTAINTY_SPECIFIC_WORKFLOWS: Record<string, TechniqueStepDefinition[]> = {
  "Expected Utility Analysis": w(s("options", "Options and uncertain outcomes", "Define feasible options and the materially different outcomes that can follow from each."), s("probabilities", "Outcome probabilities", "Assign probabilities or distributions using explicit evidence and verify that mutually exclusive outcomes are exhaustive enough for the decision."), s("utilities", "Utility function", "Translate outcome consequences into utility that reflects the decision maker's preferences and risk attitude rather than using money or raw scores automatically."), s("calculate", "Expected utility", "Multiply each outcome utility by its probability and sum within each option."), s("sensitivity", "Preference and probability sensitivity", "Test whether the preferred option changes under plausible probability, utility, or risk-attitude assumptions.")),
  "Minimax Decision Rule": w(s("options", "Options", "List feasible actions and the future states or adversary responses relevant to the decision."), s("payoffs", "Payoff matrix", "Estimate the performance of each option in each state using a consistent objective."), s("worst", "Worst-case outcome", "Identify the minimum payoff or maximum loss for each option."), s("select", "Minimax choice", "Choose the option whose worst-case outcome is best under the chosen payoff orientation."), s("limits", "Applicability and sensitivity", "Assess whether extreme pessimism, payoff uncertainty, dominated options, or omitted states make the minimax rule misleading.")),
  "Maximin Decision Rule": w(s("options", "Options", "Define feasible options and the uncertain states of the world."), s("payoffs", "Payoff matrix", "Record payoff or utility for every option-state combination using one consistent orientation."), s("minima", "Minimum payoff", "Find the lowest payoff available to each option across all states."), s("select", "Maximin choice", "Select the option with the largest minimum payoff and record any ties."), s("challenge", "Conservatism check", "Test whether the rule is appropriate for the stakes and whether modest payoff changes or a broader state set change the recommendation.")),
  "Laplace Criterion": w(s("states", "States without reliable probabilities", "Define mutually exclusive states of the world when no defensible probability differences are available."), s("payoffs", "Payoff matrix", "Estimate option performance in each state on a consistent scale."), s("equal", "Equal-probability assumption", "Assign equal probability to each state explicitly and verify that the state partition itself does not distort the weighting."), s("average", "Average payoff", "Calculate the arithmetic mean payoff for each option and rank the options."), s("partition", "Partition sensitivity", "Test whether splitting or merging states, or obtaining even weak probability information, materially changes the result.")),
  "Hurwicz Criterion": w(s("options", "Options and states", "Define the payoff matrix for feasible options across uncertain future states."), s("extremes", "Best and worst outcomes", "Identify each option's maximum and minimum payoff."), s("alpha", "Optimism coefficient", "Choose and justify an optimism coefficient between 0 and 1 rather than selecting it to favor a preferred option."), s("score", "Hurwicz score", "Combine each option's best and worst payoff using the declared coefficient and rank the results."), s("sensitivity", "Optimism sensitivity", "Vary the coefficient across a reasonable range and identify where the preferred option switches.")),
  "Dominance Analysis": w(s("matrix", "Alternatives and outcomes", "Define alternatives and the criteria, states, or consequences on which dominance will be assessed."), s("direction", "Preference direction", "Specify what better means for each dimension and normalize only where necessary."), s("compare", "Pairwise dominance", "Identify alternatives that are at least as good on every relevant dimension and strictly better on at least one."), s("prune", "Remove dominated options", "Eliminate strictly dominated alternatives and note weak or conditional dominance separately."), s("residual", "Residual choice", "Analyze tradeoffs among nondominated options rather than forcing dominance where dimensions conflict.")),
  "Stochastic Dominance": w(s("distributions", "Outcome distributions", "Define the uncertain outcome distribution for each alternative on a common consequence scale."), s("cdf", "Cumulative distributions", "Compare cumulative distribution functions or equivalent integrals across the relevant outcome range."), s("order", "Dominance order", "Test first-order, second-order, or higher-order stochastic dominance according to the assumed class of utility functions."), s("crossings", "Crossings and violations", "Identify distribution crossings or regions where dominance fails instead of averaging away the conflict."), s("implications", "Decision implications", "State which alternatives can be rejected under the chosen dominance order and what preference assumptions remain necessary among survivors.")),
  "Threshold Analysis": w(s("decision", "Decision and threshold", "Define the decision rule and the uncertain variable or performance measure that could change the preferred action."), s("model", "Decision relationship", "Specify how the variable affects costs, benefits, utility, risk, or another decision metric."), s("solve", "Threshold value", "Solve for the value at which two options become equivalent or a requirement is just met."), s("plausibility", "Plausibility of crossing", "Compare the threshold with current estimates, uncertainty ranges, historical evidence, and feasible intervention levels."), s("monitor", "Monitoring and action", "Define evidence or indicators that should trigger a decision update as the variable approaches the threshold.")),
  "Break-Even Analysis": w(s("alternatives", "Alternatives and cost structure", "Define the alternatives, fixed costs, variable costs, revenues or benefits, and common unit of activity."), s("equations", "Cost and benefit equations", "Express total cost or net value as a function of volume, time, price, or another key driver."), s("breakeven", "Break-even point", "Solve for the activity level or variable value at which the alternatives have equal net outcome."), s("uncertainty", "Uncertainty and multiple drivers", "Test uncertain costs, capacity constraints, nonlinearities, and whether more than one variable moves together."), s("decision", "Decision range", "State which alternative is preferred below and above the break-even point and whether the relevant range is realistically reachable.")),
  "Monte Carlo Simulation Review": w(s("model", "Simulation model", "Define outputs, uncertain inputs, dependencies, equations, and decision questions before running simulations."), s("distributions", "Input distributions", "Choose and justify probability distributions from data, expert judgment, or bounded assumptions, including correlations."), s("run", "Simulation runs", "Run enough trials to stabilize the decision-relevant output distribution and verify implementation against simple test cases."), s("results", "Output distribution", "Examine percentiles, tail probabilities, threshold exceedance, expected values, and drivers rather than reporting only an average."), s("validate", "Sensitivity and validation", "Check convergence, distribution assumptions, correlation structure, model error, and whether simulation results change the decision.")),
  "Probability Tree Analysis": w(s("start", "Initial decision or event", "Define the starting choice or uncertain event and the horizon of the tree."), s("branches", "Conditional branches", "Add mutually exclusive branches for subsequent events and decisions, attaching conditional probabilities where defensible."), s("payoffs", "Terminal consequences", "Assign costs, benefits, utility, or other consequences to terminal paths."), s("rollback", "Rollback calculation", "Multiply conditional probabilities along paths and work backward to compute expected values or utilities at chance nodes and optimal choices at decision nodes."), s("sensitivity", "Tree sensitivity", "Test probability, payoff, dependency, and missing-branch assumptions, especially where small changes switch the preferred path.")),
  "Info-Gap Decision Theory": w(s("model", "System model and uncertainty", "Define the decision model and a nominal estimate for a deeply uncertain parameter or function without claiming a reliable probability distribution."), s("requirements", "Performance requirement", "Specify the minimum acceptable outcome or critical failure threshold."), s("uncertainty", "Nested uncertainty sets", "Define expanding horizons of departure from the nominal model that represent increasing uncertainty."), s("robustness", "Robustness function", "For each decision, find the greatest uncertainty horizon over which the performance requirement is guaranteed."), s("opportunity", "Robustness and windfall", "Compare robustness with opportunity for unusually good outcomes and state how results depend on the uncertainty model and aspiration level.")),
  "Portfolio Decision Analysis": w(s("candidates", "Candidate portfolio elements", "Define projects, assets, policies, or capabilities that compete for shared resources or jointly create value."), s("attributes", "Value, cost, and constraints", "Estimate each element's value contribution, resource demand, risk, timing, and mandatory or logical constraints."), s("interactions", "Interactions", "Identify synergies, cannibalization, dependencies, diversification effects, and correlated risks across elements."), s("optimize", "Portfolio construction", "Compare feasible combinations using the chosen optimization, efficient-frontier, or multicriteria approach rather than ranking items independently."), s("stress", "Portfolio stress test", "Test budget changes, uncertain values, common shocks, sequencing constraints, and concentration risk before selecting the portfolio.")),
};

export const DECISION_UNCERTAINTY_SPECIFIC_CATALOG_WORKFLOW_COUNT = Object.keys(DECISION_UNCERTAINTY_SPECIFIC_WORKFLOWS).length;
export const hasDecisionUncertaintySpecificCatalogWorkflow = (name: string): boolean => Boolean(DECISION_UNCERTAINTY_SPECIFIC_WORKFLOWS[name]);
export const decisionUncertaintySpecificCatalogWorkflow = (name: string): TechniqueStepDefinition[] | undefined => DECISION_UNCERTAINTY_SPECIFIC_WORKFLOWS[name]?.map((item) => ({ ...item }));
