import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";

const s = (id: string, title: string, prompt: string, responseKind: TechniqueResponseKind = "long-text"): TechniqueStepDefinition => ({ id, title, prompt, responseKind });
const w = (...steps: TechniqueStepDefinition[]) => steps;

export const MCDA_SPECIFIC_WORKFLOWS: Record<string, TechniqueStepDefinition[]> = {
  "Analytic Network Process": w(s("network", "Decision network", "Define the goal, criteria, subcriteria, alternatives, and feedback or dependence relationships that make a simple hierarchy inadequate."), s("comparisons", "Pairwise comparisons", "Make pairwise judgments within and across dependent clusters using a consistent ratio scale and document the rationale."), s("supermatrix", "Supermatrix", "Assemble local priority vectors into the unweighted supermatrix, apply cluster weights, and form the weighted supermatrix."), s("limit", "Limit priorities", "Raise or iterate the weighted supermatrix to convergence and extract limiting priorities for the alternatives."), s("sensitivity", "Consistency and sensitivity", "Check comparison consistency and test whether plausible changes in judgments or dependency structure alter the ranking.")),
  "Weighted Sum Model": w(s("matrix", "Decision matrix", "Define alternatives, criteria, direction of preference, and commensurate or normalized criterion scores."), s("weights", "Criterion weights", "Assign explicit nonnegative weights that reflect relative importance and sum to a common total."), s("normalize", "Normalize scores", "Transform criterion values to a comparable benefit scale when units differ, documenting the normalization rule."), s("sum", "Weighted totals", "Multiply each normalized score by its criterion weight and sum across criteria for each alternative."), s("sensitivity", "Ranking sensitivity", "Inspect criterion contributions and test whether reasonable weight or normalization changes reverse the ranking.")),
  "Weighted Product Model": w(s("matrix", "Decision matrix", "Define positive criterion values, alternatives, preference direction, and criteria requiring transformation before multiplication."), s("weights", "Criterion exponents", "Assign normalized importance weights and confirm that the multiplicative interpretation is appropriate."), s("ratios", "Normalize or ratio-scale", "Express performances on compatible positive ratio scales so multiplicative comparisons are meaningful."), s("product", "Weighted products", "Raise each criterion score to its weight, multiply across criteria, and derive relative preference values."), s("sensitivity", "Interpret and test", "Check dominance, zero or negative-value problems, scale sensitivity, and whether plausible weights alter the preferred alternative.")),
  "ELECTRE": w(s("matrix", "Alternatives and criteria", "Define alternatives, criteria, weights, preference direction, and any indifference, preference, or veto thresholds."), s("relations", "Pairwise concordance", "For each pair of alternatives, assess the weighted evidence that one is at least as good as the other."), s("discordance", "Discordance and veto", "Identify criteria where poor performance strongly opposes or vetoes an outranking relation."), s("outrank", "Outranking relation", "Apply the selected ELECTRE variant's concordance and discordance rules to construct the outranking graph or ranking."), s("robust", "Robustness", "Test sensitivity to thresholds, weights, incomparability, and the chosen ELECTRE variant before interpreting the result.")),
  "PROMETHEE": w(s("matrix", "Decision matrix", "Define alternatives, criteria, weights, preference direction, and criterion-specific preference functions."), s("preferences", "Pairwise preferences", "Convert pairwise performance differences into preference degrees using the selected functions and thresholds."), s("flows", "Preference flows", "Calculate positive and negative outranking flows for each alternative and derive net flows where appropriate."), s("rank", "PROMETHEE ranking", "Use partial or complete ranking consistent with the chosen PROMETHEE variant and identify incomparabilities if retained."), s("sensitivity", "Sensitivity", "Test how preference functions, thresholds, and weights affect flows and the final ranking.")),
  "VIKOR": w(s("matrix", "Decision matrix", "Define alternatives, criteria, weights, and benefit or cost direction for each criterion."), s("ideals", "Best and worst values", "Identify criterion-wise ideal and anti-ideal values and normalize regret from the ideal."), s("measures", "Utility and regret", "Calculate each alternative's aggregate group utility measure and maximum individual-regret measure."), s("compromise", "Compromise index", "Combine utility and regret using the declared strategy weight and rank alternatives by the VIKOR index."), s("conditions", "Compromise conditions", "Check acceptable advantage and stability conditions and report a compromise set when a unique solution is not justified.")),
  "SMART Decision Analysis": w(s("objectives", "Objectives and attributes", "Define a value tree of decision objectives and measurable attributes, avoiding double counting."), s("scores", "Value scores", "Construct defensible single-attribute value scales and score each alternative's performance."), s("weights", "Swing weights", "Weight attributes by the value of moving from their worst to best relevant levels, not by vague importance alone."), s("aggregate", "Aggregate value", "Combine value scores and weights under the additive-independence assumptions of SMART."), s("sensitivity", "Sensitivity", "Test uncertain scores and weights, identify tradeoffs, and report where the additive model's assumptions are questionable.")),
  "SMARTER": w(s("objectives", "Objectives and attributes", "Define a nonredundant value tree and measurable attributes for comparing the alternatives."), s("scores", "Value scores", "Convert performances to common value scales with explicit best, worst, and intermediate anchors."), s("rank", "Rank importance", "Rank criteria by swing importance rather than eliciting precise numerical weights directly."), s("roc", "Rank-order centroid weights", "Convert the criterion ranking into rank-order centroid weights and calculate aggregate alternative values."), s("sensitivity", "Robustness", "Test alternative plausible criterion orders and value scores to see whether the recommended option is stable.")),
  "Multi-Attribute Value Theory": w(s("objectives", "Objectives", "Define the decision objectives, value-relevant attributes, feasible alternatives, and stakeholder perspective."), s("functions", "Value functions", "Construct single-attribute value functions that map each attribute's performance to relative value."), s("tradeoffs", "Scaling constants", "Elicit tradeoff or swing weights consistent with the chosen additive or multiplicative value model."), s("evaluate", "Aggregate values", "Calculate overall value for each alternative using the declared preference-independence assumptions."), s("sensitivity", "Preference sensitivity", "Test weights, value functions, omitted objectives, and independence assumptions before recommending an alternative.")),
  "Kepner-Tregoe Decision Analysis": w(s("objectives", "Decision statement and objectives", "State the decision, generate alternatives, and separate must-have requirements from weighted wants."), s("musts", "Screen musts", "Reject alternatives that fail mandatory constraints using explicit pass/fail evidence."), s("wants", "Score wants", "Weight desirable objectives and score surviving alternatives consistently against each one."), s("adverse", "Adverse consequences", "Identify material risks or negative consequences for leading alternatives and assess probability and seriousness."), s("choice", "Balanced choice", "Select the alternative with the strongest objective performance after considering adverse consequences and sensitivity.")),
  "QFD House of Quality": w(s("needs", "Customer needs", "Capture and prioritize customer or stakeholder needs in their own terms, including evidence for importance."), s("characteristics", "Technical characteristics", "Translate needs into measurable design or service characteristics under the team's control."), s("relations", "Relationship matrix", "Rate how strongly each technical characteristic affects each need and document ambiguous relationships."), s("roof", "Technical correlations", "Map reinforcing and conflicting relationships among technical characteristics and identify design tradeoffs."), s("targets", "Priorities and targets", "Combine need importance, relationships, competitive benchmarks, and technical difficulty into prioritized engineering targets.")),
  "MoSCoW Prioritization": w(s("scope", "Scope and timebox", "Define the delivery scope, deadline, resource constraint, and minimum viable outcome before prioritizing requirements."), s("criteria", "Category rules", "Define operational rules for Must, Should, Could, and Won't-this-time so categories are not just synonyms for priority levels."), s("classify", "Classify requirements", "Assign each requirement using consequence-of-omission and dependency reasoning, recording why it belongs in that category."), s("capacity", "Capacity check", "Verify that Must items fit the available capacity and demote items if everything has been labeled mandatory."), s("review", "Review dependencies", "Check cross-item dependencies, deferred items, and trigger conditions for reprioritization during the timebox.")),
  "RICE Scoring": w(s("items", "Candidate initiatives", "Define comparable initiatives and the horizon over which their impact and effort will be estimated."), s("reach", "Reach", "Estimate how many users, cases, or units each initiative will affect within the chosen period and document the basis."), s("impact", "Impact and confidence", "Assign impact using a consistent scale and confidence reflecting evidence quality for reach, impact, and effort estimates."), s("effort", "Effort", "Estimate total person-time or another consistent resource measure including major hidden dependencies."), s("rank", "RICE ranking", "Calculate reach × impact × confidence / effort, then review strategic dependencies and sensitivity rather than treating the score as automatic truth.")),
  "WSJF Prioritization": w(s("items", "Work items", "Define items at comparable granularity and the delivery system in which delay and job size matter."), s("cod", "Cost of delay", "Estimate user or business value, time criticality, and risk reduction or opportunity enablement using a consistent relative scale."), s("size", "Job size", "Estimate relative duration or effort with the same reference scale across items."), s("wsjf", "WSJF score", "Divide relative cost of delay by relative job size and rank the work items."), s("review", "Flow and dependency review", "Check dependencies, capacity, sequencing constraints, stale estimates, and whether score differences are meaningful enough to drive order.")),
  "Pairwise Comparison Matrix": w(s("items", "Items and criterion", "Define the alternatives or criteria and the single dimension on which each pair will be compared."), s("judgments", "Pairwise judgments", "Compare every required pair using a consistent ordinal or ratio scale and record the basis for each judgment."), s("matrix", "Reciprocal matrix", "Construct the comparison matrix, including reciprocal entries where the scale requires them."), s("priorities", "Derive priorities", "Calculate relative priorities using the declared method, such as normalized columns, eigenvector, or geometric mean."), s("consistency", "Consistency and sensitivity", "Check logical consistency or consistency ratio where applicable and test whether uncertain judgments affect the ordering.")),
};

export const MCDA_SPECIFIC_CATALOG_WORKFLOW_COUNT = Object.keys(MCDA_SPECIFIC_WORKFLOWS).length;
export const hasMCDASpecificCatalogWorkflow = (name: string): boolean => Boolean(MCDA_SPECIFIC_WORKFLOWS[name]);
export const mcdaSpecificCatalogWorkflow = (name: string): TechniqueStepDefinition[] | undefined => MCDA_SPECIFIC_WORKFLOWS[name]?.map((item) => ({ ...item }));
