import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";
const s=(id:string,title:string,prompt:string,responseKind:TechniqueResponseKind="long-text"):TechniqueStepDefinition=>({id,title,prompt,responseKind}); const w=(...steps:TechniqueStepDefinition[])=>steps;
export const DESIGN_SPECIFIC_WORKFLOWS:Record<string,TechniqueStepDefinition[]>={
  "Persona Analysis":w(s("evidence","Evidence base","Define the research sources and population used to construct personas."),s("patterns","Behavioral patterns","Identify recurring goals, behaviors, constraints, contexts, and motivations."),s("persona","Persona","Construct an evidence-grounded archetype without inventing unsupported demographics."),s("needs","Needs and tensions","Map jobs, pain points, workarounds, and decision criteria."),s("use","Design implications","Translate persona evidence into testable design requirements and flag uncertainty.")),
  "Contextual Inquiry":w(s("work","Work context","Define the activity, participants, environment, and research question."),s("observe","Observe in context","Watch real work while preserving sequence, tools, interruptions, and environmental constraints."),s("probe","Contextual probing","Ask participants to explain choices and tacit practices during or immediately after action."),s("model","Work model","Capture flows, artifacts, breakdowns, roles, and workarounds."),s("insight","Design insight","Separate observed behavior from interpretation and derive opportunities grounded in context.")),
  "Diary Study Analysis":w(s("study","Diary study","Define participants, period, prompts, event triggers, and expected reporting burden."),s("entries","Entry preparation","Normalize timestamps, context, missingness, and participant-specific baselines."),s("patterns","Within-person patterns","Identify recurring behaviors, emotions, events, and temporal sequences."),s("compare","Across-person comparison","Compare patterns while preserving meaningful differences and reporting bias."),s("insight","Design implications","Translate longitudinal evidence into needs, moments, and hypotheses for further testing.")),
  "Critical Incident Technique":w(s("activity","Activity and outcome","Define the behavior domain and what counts as unusually effective or ineffective performance."),s("incidents","Critical incidents","Collect concrete episodes with context, actions, consequences, and participant perspective."),s("code","Behavioral coding","Code incident features and actions rather than vague attitudes."),s("patterns","Critical patterns","Identify behaviors or conditions repeatedly associated with success or failure."),s("apply","Application","Translate patterns into requirements, training, controls, or design hypotheses.")),
  "Customer Journey Mapping":w(s("journey","Journey scope","Define user, goal, start/end points, channels, and scenario."),s("stages","Stages and actions","Map stages, actions, touchpoints, actors, and artifacts."),s("experience","Experience layer","Record expectations, emotions, effort, pain points, and unmet needs with evidence."),s("breaks","Breakdowns and transitions","Identify handoff failures, delays, duplication, and moments of truth."),s("opportunity","Opportunities","Prioritize changes by user value, operational feasibility, and evidence strength.")),
  "Experience Mapping":w(s("experience","Experience domain","Define the broad experience across products, services, or contexts."),s("phases","Phases","Map major phases, goals, behaviors, environments, and actors."),s("forces","Experience forces","Capture motivations, emotions, constraints, social influences, and information needs."),s("patterns","Cross-channel patterns","Identify persistent problems and opportunities that exceed any single touchpoint."),s("strategy","Strategic implications","Define experience principles and opportunity areas that can guide multiple solutions.")),
  "Story Mapping":w(s("goal","User goal","Define the user outcome or end-to-end activity being mapped."),s("backbone","Activity backbone","Arrange major user activities in narrative sequence."),s("tasks","Tasks and stories","Break activities into user tasks and candidate stories at useful granularity."),s("slices","Release slices","Create horizontal slices that deliver coherent outcomes, not arbitrary feature batches."),s("gaps","Gap review","Identify missing steps, dependencies, risks, and learning needed before sequencing work.")),
  "Opportunity Solution Tree":w(s("outcome","Desired outcome","Define a measurable product, mission, or user outcome."),s("opportunities","Opportunity space","Derive user needs, problems, and desires from evidence and structure them without jumping to solutions."),s("solutions","Solution branches","Generate multiple solution approaches for promising opportunities."),s("tests","Assumption tests","Identify critical assumptions and small experiments for each solution branch."),s("learn","Update tree","Use evidence to prune, split, reprioritize, or add opportunities and solutions.")),
  "How-Might-We Framing":w(s("evidence","Observed need","Start from a specific evidence-backed user problem, tension, or opportunity."),s("frame","HMW question","Write an open but bounded how-might-we question that avoids embedding a preferred solution."),s("range","Range check","Test whether the frame is neither so narrow it predetermines an answer nor so broad it loses the user need."),s("variants","Alternative frames","Generate frames that shift actor, context, constraint, or desired effect."),s("select","Select frame","Choose frames likely to produce diverse, relevant concepts and record assumptions.")),
  "SCAMPER":w(s("object","Object or process","Define what is being redesigned and the outcome to improve."),s("prompts","SCAMPER prompts","Apply substitute, combine, adapt, modify, put-to-another-use, eliminate, and reverse/rearrange prompts systematically."),s("ideas","Idea capture","Generate concrete variants without evaluating too early."),s("screen","Screen ideas","Assess novelty, user value, feasibility, side effects, and compatibility with constraints."),s("test","Test candidates","Select concepts for prototyping or evidence gathering.")),
  "Six Thinking Hats":w(s("question","Decision or problem","Define the focal question and participants."),s("facts","White hat","Separate known information, missing data, and disputed facts."),s("perspectives","Red/black/yellow hats","Capture intuition, risks/cautions, and benefits/value without forcing them into one argument."),s("ideas","Green hat","Generate alternatives, provocations, and modifications."),s("control","Blue hat synthesis","Summarize the process, unresolved tensions, next evidence, and decision without treating hats as evidence quality.")),
  "Design Studio":w(s("challenge","Design challenge","Define users, scenario, constraints, and success criteria."),s("sketch","Independent sketching","Have participants generate multiple concrete concepts before discussion."),s("share","Share and critique","Present concepts, ask clarifying questions, and critique against evidence and criteria rather than status."),s("converge","Converge","Combine promising elements into stronger concepts while preserving materially different alternatives."),s("next","Prototype plan","Select concepts and assumptions for prototyping and user testing.")),
  "Crazy Eights":w(s("focus","Focus question","Define a specific user problem or design opportunity."),s("constraints","Constraints","Set the eight-frame format, short timebox, and evidence or requirements that must be respected."),s("sketches","Eight variations","Generate eight visibly different concepts or variations rather than polishing one idea."),s("review","Review","Identify distinct mechanisms, repeated assumptions, and surprising directions."),s("advance","Advance concepts","Choose several candidates for elaboration or testing, not simply the prettiest sketch.")),
  "Concept Screening":w(s("concepts","Concept set","Define comparable concepts and minimum requirements."),s("criteria","Screening criteria","Choose a small set of critical criteria and a reference concept or threshold."),s("rate","Coarse rating","Rate each concept consistently as better, same, worse, pass/fail, or another simple scheme."),s("review","Review eliminations","Check whether weak evidence, correlated criteria, or premature constraints caused rejection."),s("select","Screen result","Advance, combine, or discard concepts with reasons and learning needs.")),
  "Concept Scoring":w(s("concepts","Concepts","Define the surviving concepts at comparable maturity."),s("criteria","Weighted criteria","Define measurable criteria, scales, and weights tied to user and system requirements."),s("score","Score concepts","Score each concept with evidence and record uncertainty rather than false precision."),s("sensitivity","Sensitivity","Test plausible weight and score changes for ranking reversals."),s("decision","Decision","Select, combine, or retest concepts based on robust performance and evidence gaps.")),
  "Kano Analysis":w(s("features","Attributes","Define candidate product/service attributes in user-understandable terms."),s("survey","Functional/dysfunctional responses","Collect paired reactions to presence and absence of each attribute."),s("classify","Kano classification","Classify must-be, performance, attractive, indifferent, reverse, or questionable responses."),s("segments","Segment and uncertainty","Inspect differences across user segments, sample size, and time because categories can migrate."),s("prioritize","Prioritize","Combine Kano class with strategic value, cost, and evidence to guide—not dictate—roadmap choices.")),
};
export const DESIGN_SPECIFIC_CATALOG_WORKFLOW_COUNT=Object.keys(DESIGN_SPECIFIC_WORKFLOWS).length;
export const hasDesignSpecificCatalogWorkflow=(name:string)=>Boolean(DESIGN_SPECIFIC_WORKFLOWS[name]);
export const designSpecificCatalogWorkflow=(name:string)=>DESIGN_SPECIFIC_WORKFLOWS[name]?.map(x=>({...x}));