import type { TechniqueResponseKind, TechniqueStepDefinition } from "./types";
const s=(id:string,title:string,prompt:string,responseKind:TechniqueResponseKind="long-text"):TechniqueStepDefinition=>({id,title,prompt,responseKind}); const w=(...steps:TechniqueStepDefinition[])=>steps;
export const ECONOMICS_SPECIFIC_WORKFLOWS:Record<string,TechniqueStepDefinition[]>={
  "Elasticity Analysis":w(s("variables","Variables and market","Define the quantity, price or driver, population, period, and market boundary."),s("estimate","Estimate elasticity","Estimate percentage responsiveness using an appropriate arc, point, or model-based method."),s("conditions","Conditions","Check range, time horizon, substitutes, income effects, and structural breaks."),s("interpret","Interpretation","Classify responsiveness and explain what behavior the estimate implies."),s("decision","Decision use","Assess pricing, demand, tax, or policy implications with uncertainty.")),
  "Marginal Analysis":w(s("decision","Incremental decision","Define the unit of additional action, output, input, or investment being considered."),s("benefit","Marginal benefit","Estimate the additional benefit from one more unit at the relevant scale."),s("cost","Marginal cost","Estimate additional opportunity, resource, and external costs."),s("compare","Compare at the margin","Identify where marginal benefit and cost cross or where constraints bind."),s("act","Decision","State the efficient stopping or adjustment rule and sensitivity.")),
  "Opportunity Cost Analysis":w(s("choice","Choice","Define the scarce resource and decision that excludes alternatives."),s("alternatives","Foregone alternatives","Identify realistic next-best uses rather than every conceivable option."),s("value","Foregone value","Estimate the value of the best displaced alternative, including timing and risk."),s("hidden","Hidden costs","Identify non-cash, capacity, delay, lock-in, and option-value losses."),s("decision","Net choice","Compare the chosen use against its opportunity cost and record uncertainty.")),
  "Welfare Analysis":w(s("policy","Change and baseline","Define the intervention, market, affected groups, and counterfactual."),s("surplus","Surplus changes","Estimate consumer, producer, government, and other relevant surplus changes."),s("external","Externalities and distortions","Include external costs/benefits, taxes, market power, and non-market effects."),s("distribution","Distribution","Identify who gains, loses, and whether transfers are being double-counted as net welfare."),s("judgment","Welfare judgment","State efficiency and distributional implications with assumptions and limits.")),
  "Market Structure Analysis":w(s("market","Relevant market","Define products, geography, customers, substitutes, and time horizon."),s("structure","Structure","Assess concentration, entry barriers, differentiation, vertical relationships, and buyer power."),s("conduct","Conduct","Examine pricing, capacity, innovation, coordination, and strategic behavior."),s("performance","Performance","Assess margins, quality, output, innovation, and consumer outcomes without inferring causality from concentration alone."),s("outlook","Competitive outlook","Identify likely structural changes and indicators of competitive harm or improvement.")),
  "Game-Theoretic Payoff Matrix":w(s("players","Players and strategies","Define players, feasible strategies, timing, and information."),s("payoffs","Payoffs","Specify ordinal or cardinal payoffs including strategic and non-monetary objectives."),s("equilibria","Best responses and equilibria","Identify dominant strategies, best responses, and candidate equilibria."),s("assumptions","Assumptions and dynamics","Test sensitivity to repeated play, commitment, incomplete information, and coalition possibilities."),s("implications","Strategic implications","Identify leverage, deterrence, bargaining, and signaling implications.")),
  "Input-Output Analysis":w(s("economy","System boundary","Define sectors, geography, year, price basis, and transaction table."),s("coefficients","Technical coefficients","Derive input requirements and check fixed-coefficient assumptions."),s("shock","Demand or supply shock","Specify the exogenous change and affected sectors."),s("multipliers","Direct and indirect effects","Estimate output, value-added, labor, or other multiplier effects while avoiding unsupported induced effects."),s("limits","Interpretation limits","Assess imports, capacity constraints, substitution, prices, and temporal limits.")),
  "Comparative Statics":w(s("model","Equilibrium model","Define endogenous variables, exogenous parameters, constraints, and baseline equilibrium."),s("change","Parameter change","Specify the exogenous change to analyze."),s("direction","Directional effects","Derive how equilibrium variables change and identify ambiguous signs."),s("conditions","Conditions","State assumptions needed for the result and thresholds where it may reverse."),s("interpret","Economic interpretation","Translate the comparative result into behavior, welfare, or policy implications.")),
  "Economic Scenario Analysis":w(s("baseline","Economic baseline","Define horizon, key variables, institutions, and baseline trajectory."),s("shocks","Scenario shocks","Specify coherent macro, market, policy, technology, or geopolitical shocks."),s("transmission","Transmission channels","Trace effects through demand, supply, prices, finance, trade, labor, and expectations."),s("paths","Scenario paths","Develop internally consistent paths for key indicators and sectoral effects."),s("implications","Implications","Compare vulnerabilities, opportunities, leading indicators, and robust actions across scenarios.")),
};
export const ECONOMICS_SPECIFIC_CATALOG_WORKFLOW_COUNT=Object.keys(ECONOMICS_SPECIFIC_WORKFLOWS).length;
export const hasEconomicsSpecificCatalogWorkflow=(name:string)=>Boolean(ECONOMICS_SPECIFIC_WORKFLOWS[name]);
export const economicsSpecificCatalogWorkflow=(name:string)=>ECONOMICS_SPECIFIC_WORKFLOWS[name]?.map(x=>({...x}));