import fs from "node:fs";
const pages=await fetch("http://127.0.0.1:9229/json").then(r=>r.json());
const page=pages.find(p=>p.type==="page"); if(!page) throw new Error("No CDP page");
const ws=new WebSocket(page.webSocketDebuggerUrl); let id=1; const pending=new Map();
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id)}};
await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
const call=(method,params={})=>new Promise(r=>{const n=id++;pending.set(n,r);ws.send(JSON.stringify({id:n,method,params}))});
const value=async expression=>(await call("Runtime.evaluate",{expression,returnByValue:true,awaitPromise:true})).result.result.value;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
await call("Emulation.setDeviceMetricsOverride",{width:1440,height:900,deviceScaleFactor:1,mobile:false});
const evidenceCount=await value(`(()=>{const b=[...document.querySelectorAll('[role=tab]')].find(e=>e.textContent.trim().startsWith('Evidence'));b?.click();return b?.textContent||''})()`);
await sleep(650);
const palette=await value(`(()=>{const p=document.querySelector('.context-pane');const c=document.querySelector('.evidence-row');const s=getComputedStyle(p);return {mode:p?.dataset.contextMode,evidenceCount,paneBackground:s.backgroundColor,paneColor:s.color,cardBackground:c?getComputedStyle(c).backgroundColor:null,divider:getComputedStyle(p).borderLeftColor}})()`);
const shot=await call("Page.captureScreenshot",{format:"png",captureBeyondViewport:false});
const path="C:/Users/iris/Downloads/Catalyst/tools/research-probes/2026-09-13/evidence-contrast-live.png";
fs.writeFileSync(path,Buffer.from(shot.result.data,"base64"));
console.log(JSON.stringify({...palette,screenshotPath:path},null,2));
await value(`([...document.querySelectorAll('[role=tab]')].find(e=>e.textContent.trim().startsWith('Analysis')||e.textContent.trim().startsWith('Working picture')))?.click();true`);
ws.close();
