const pages=await fetch('http://127.0.0.1:9229/json').then(r=>r.json());
const page=pages.find(p=>p.type==='page'&&p.url.includes('127.0.0.1:5173'));if(!page)throw new Error('No Catalyst page');
const ws=new WebSocket(page.webSocketDebuggerUrl);let id=1;const pending=new Map();
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id);}};
await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
const call=(method,params={})=>new Promise(r=>{const n=id++;pending.set(n,r);ws.send(JSON.stringify({id:n,method,params}));});
const val=async expression=>{const m=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(m.result?.exceptionDetails)throw new Error(m.result.exceptionDetails.exception?.description||m.result.exceptionDetails.text);return m.result?.result?.value;};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
await call('Page.navigate',{url:'http://127.0.0.1:5173/'});await sleep(1800);
const initial=await val(`(()=>({library:[...document.querySelectorAll('button')].some(b=>b.textContent?.trim()==='Library'),commands:[...document.querySelectorAll('button')].some(b=>b.textContent?.includes('Commands')),xml:!!localStorage.getItem('catalyst.xml.workspace.v1')}))()`);
await val(`[...document.querySelectorAll('button')].find(b=>b.textContent?.trim()==='Library')?.click();true`);await sleep(300);
const library=await val(`(()=>({open:!!document.querySelector('[role="dialog"]'),text:document.body.innerText.includes('Library'),alerts:[...document.querySelectorAll('[role="alert"]')].map(x=>x.textContent).filter(Boolean)}))()`);
await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape'});await sleep(250);
await call('Input.dispatchKeyEvent',{type:'keyDown',key:'k',code:'KeyK',modifiers:2});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'k',code:'KeyK',modifiers:2});await sleep(300);
const commands=await val(`(()=>({open:!!document.querySelector('.command-palette,[role="dialog"]'),search:!!document.querySelector('input[placeholder="Type a command…"]'),text:document.body.innerText.includes('Commands')}))()`);
await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape'});await sleep(200);
const storage=await val(`(()=>({xml:localStorage.getItem('catalyst.xml.workspace.v1')||'',legacy:localStorage.getItem('catalyst.browser.workspace.v1'),recovery:localStorage.getItem('catalyst.recovery.v1')}))()`);
const xmlLooksValid=storage.xml.startsWith('<?xml')&&storage.xml.includes('<catalyst-workspace');
await call('Page.reload',{});await sleep(1800);
const reloaded=await val(`(()=>({title:document.title,xml:!!localStorage.getItem('catalyst.xml.workspace.v1'),alerts:[...document.querySelectorAll('[role="alert"]')].map(x=>x.textContent).filter(Boolean)}))()`);
console.log(JSON.stringify({initial,library,commands,xmlLooksValid,reloaded,pass:initial.library&&library.text&&commands.search&&xmlLooksValid&&reloaded.xml&&reloaded.alerts.length===0},null,2));
ws.close();
