const pages = await fetch('http://127.0.0.1:9229/json').then(r => r.json());
const page = pages.find(p => p.type === 'page' && p.url.includes('127.0.0.1:5173')); if (!page) throw new Error('No Catalyst CDP page');
const ws = new WebSocket(page.webSocketDebuggerUrl); let id = 1; const pending = new Map();
ws.onmessage = e => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } };
await new Promise((resolve, reject) => { ws.onopen = resolve; ws.onerror = reject; });
const call = (method, params = {}) => new Promise(resolve => { const n = id++; pending.set(n, resolve); ws.send(JSON.stringify({ id:n, method, params })); });
const val = async expression => { const m = await call('Runtime.evaluate', { expression, returnByValue:true, awaitPromise:true }); if (m.result?.exceptionDetails) throw new Error(m.result.exceptionDetails.exception?.description || m.result.exceptionDetails.text); return m.result?.result?.value; };
const sleep = ms => new Promise(r => setTimeout(r, ms));
const setField = async (selector, value) => val(`(()=>{const e=[...document.querySelectorAll(${JSON.stringify(selector)})].find(x=>x.offsetParent!==null);if(!e)return false;const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(p,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));return true})()`);
await val(`localStorage.removeItem('catalyst.xml.workspace.v1');localStorage.removeItem('catalyst.browser.workspace.v1');localStorage.removeItem('catalyst.recovery.v1');true`);
await call('Page.navigate', { url:'http://127.0.0.1:5173/' }); await sleep(2200);
await val(`[...document.querySelectorAll('button')].find(b=>b.textContent?.trim()==='Create first thought')?.click();true`); await sleep(500);
await setField('[aria-label="Thought title"]','Convergence root'); await setField('[aria-label="Thought details"]','Root issue created by convergence smoke test.'); await sleep(700);
await val(`document.querySelector('.picture-occurrence')?.click();true`); await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab'}); await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab'}); await sleep(700);
await setField('[aria-label="Thought title"]','Convergence child'); await sleep(500);
await val(`document.activeElement?.blur();document.querySelector('.picture-occurrence.is-active,.picture-occurrence[aria-current="true"],.picture-occurrence:last-of-type')?.click();true`);
await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',modifiers:8}); await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',modifiers:8}); await sleep(700);
await setField('[aria-label="Thought title"]','Convergence sibling'); await sleep(1200);
const before = await val(`(()=>({occurrences:document.querySelectorAll('.picture-occurrence').length,titles:[...document.querySelectorAll('.picture-occurrence')].map(x=>x.textContent?.trim()).filter(Boolean),xml:!!localStorage.getItem('catalyst.xml.workspace.v1'),analysis:[...document.querySelectorAll('[role=tab]')].find(x=>x.textContent?.includes('Analysis'))?.textContent}))()`);
await call('Page.reload',{}); await sleep(2400);
const after = await val(`(()=>({occurrences:document.querySelectorAll('.picture-occurrence').length,titles:[...document.querySelectorAll('.picture-occurrence')].map(x=>x.textContent?.trim()).filter(Boolean),xml:!!localStorage.getItem('catalyst.xml.workspace.v1'),analysis:[...document.querySelectorAll('[role=tab]')].find(x=>x.textContent?.includes('Analysis'))?.textContent,errors:[...document.querySelectorAll('[role=alert]')].map(x=>x.textContent).filter(Boolean)}))()`);
console.log(JSON.stringify({before,after,pass:before.occurrences>=2&&after.occurrences===before.occurrences&&after.xml},null,2)); ws.close();