import fs from 'node:fs';
const pages=await fetch('http://127.0.0.1:9229/json').then(r=>r.json());
const page=pages.find(x=>x.type==='page'&&x.url.includes('127.0.0.1:5173')); if(!page) throw new Error('No Catalyst CDP page');
const ws=new WebSocket(page.webSocketDebuggerUrl); let id=1; const pending=new Map();
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id)}};
await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
const call=(method,params={})=>new Promise(r=>{const n=id++;pending.set(n,r);ws.send(JSON.stringify({id:n,method,params}))});
const val=async expression=>(await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.result.value;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)); await call('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
const raw=await val(`localStorage.getItem('catalyst.browser.workspace.v1')||''`); const state=JSON.parse(raw);
const annotationId=Object.keys(state.annotations)[0]; const sourceId=Object.keys(state.notes).find(id=>state.links.some(l=>l.noteId===id&&l.annotationId===annotationId));
if(!annotationId||!sourceId) throw new Error('Run catalyst_source_region_reuse.mjs first');
const now='2026-09-13T12:10:00.000Z'; const note=(id,title,minute)=>({id,title,body:'',createdAt:`2026-09-13T12:${String(minute).padStart(2,'0')}:00.000Z`,updatedAt:now,deletedAt:null});
state.notes[sourceId].title='Source-backed evidence';
Object.assign(state.notes,{root:note('root','Analytical issue',0),claim:note('claim','Assessed claim',1),assumption:note('assumption','Key assumption',2),hypothesis:note('hypothesis','Competing hypothesis',3),question:note('question','Open intelligence gap',4),entity:note('entity','Relevant actor',5),event:note('event','Material event',6),thought:note('thought','Context note',7)});
state.noteSemantics={...state.noteSemantics,root:{roles:['note'],confidence:null},claim:{roles:['claim'],confidence:'medium'},assumption:{roles:['assumption'],confidence:'low'},hypothesis:{roles:['hypothesis'],confidence:'medium'},question:{roles:['question'],confidence:null},entity:{roles:['entity'],confidence:null},event:{roles:['event'],confidence:null},thought:{roles:['note'],confidence:null},[sourceId]:{roles:['note'],confidence:null}};
const ids=['root',sourceId,'claim','assumption','hypothesis','question','entity','event','thought'];
const occurrences={};
for(const id of ids) occurrences[id]={noteId:id,parentNoteId:id==='root'?null:'root',position:null,collapsed:false,manual:false};
state.relationships={support:{id:'support',fromId:sourceId,toId:'claim',type:'supports',directed:true,label:null,createdAt:now,updatedAt:now},challenge:{id:'challenge',fromId:'assumption',toId:'hypothesis',type:'contradicts',directed:true,label:null,createdAt:now,updatedAt:now}};
state.mapView={activeMapId:'analysis-overview',maps:{'analysis-overview':{id:'analysis-overview',name:'Iconography grammar',focusNoteId:'root',occurrences,camera:{x:0,y:0,zoom:1}}}};
state.activeNoteId=null; state.activeDocumentId=null; state.pendingSelection=null; state.capabilities={profile:'analytical',overrides:{}};
await val(`localStorage.setItem('catalyst.browser.workspace.v1',${JSON.stringify(JSON.stringify(state))});localStorage.removeItem('catalyst.recovery.v1');true`);
await call('Page.navigate',{url:'http://127.0.0.1:5173/?research=unified-workflow&shell=spatial&run=iconography-grammar'}); await sleep(3500);
const snap=async name=>{const shot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false}); const path=`C:/Users/iris/Downloads/Catalyst/tools/research-probes/2026-09-13/${name}.png`; fs.writeFileSync(path,Buffer.from(shot.result.data,'base64')); return path;};
await val(`document.querySelector('[aria-label="Fit picture"]')?.click();true`); await sleep(700); const overview=await snap('iconography-grammar-fit');
const overviewMeasure=await val(`(()=>({zoom:document.querySelector('.picture-controls span')?.textContent,nodes:[...document.querySelectorAll('.picture-occurrence')].map(n=>({class:n.className,label:n.querySelector('.picture-object-label')?.textContent||''})),territories:document.querySelectorAll('.territory-glyph').length}))()`);
for(let i=0;i<3;i++) await val(`document.querySelector('[aria-label="Zoom in"]')?.click();true`); await sleep(600); const working=await snap('iconography-grammar-working');
console.log(JSON.stringify({...overviewMeasure,overview,working},null,2)); ws.close();
