import fs from 'node:fs';
const pages=await fetch('http://127.0.0.1:9229/json').then(r=>r.json());
const page=pages.find(x=>x.type==='page'&&x.url.startsWith('http://127.0.0.1:5173'));
if(!page) throw new Error('No Catalyst Opera/CDP page');
const ws=new WebSocket(page.webSocketDebuggerUrl); let id=1; const pending=new Map();
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id)}};
await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
const c=(method,params={})=>new Promise(r=>{const n=id++;pending.set(n,r);ws.send(JSON.stringify({id:n,method,params}))});
const v=async expression=>(await c('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.result.value;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
await c('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
await c('Page.navigate',{url:'http://127.0.0.1:5173/?research=unified-workflow&shell=spatial&run=icon-landmarks-live'}); await sleep(1800);
const raw=await v(`localStorage.getItem('catalyst.browser.workspace.v1')||''`); const state=raw?JSON.parse(raw):{};
const note=(id,title,day)=>({id,title,body:'',createdAt:'2026-01-'+String(day).padStart(2,'0')+'T00:00:00.000Z',updatedAt:'2026-01-'+String(day).padStart(2,'0')+'T00:00:00.000Z',deletedAt:null});
state.documents={};state.annotations={};state.viewerMarkups={};state.links=[];state.noteLinks=[];state.customTechniqueDefinitions={};state.techniqueRuns={};state.pendingSelection=null;state.activeDocumentId=null;
state.notes={root:note('root','Iconography issue',1),beta:note('beta','Assumption branch',2),gamma:note('gamma','Assessed claim',4),alpha:note('alpha','Open question',3)};state.activeNoteId='gamma';
state.noteSemantics={root:{roles:['note'],confidence:null},beta:{roles:['assumption'],confidence:'medium'},gamma:{roles:['claim'],confidence:'high'},alpha:{roles:['question'],confidence:null}};
state.relationships={rel:{id:'rel',fromId:'gamma',toId:'alpha',type:'supports',directed:true,label:null,createdAt:'2026-01-05T00:00:00.000Z',updatedAt:'2026-01-05T00:00:00.000Z'}};
state.evidenceTags={};state.annotationTags=[];state.annotationRoles={};state.graphView={positions:{},camera:{x:0,y:0,zoom:1}};state.capabilities={profile:'analytical',overrides:{}};
state.mapView={activeMapId:'analysis-overview',maps:{'analysis-overview':{id:'analysis-overview',name:'Iconography probe',focusNoteId:'root',occurrences:{root:{noteId:'root',parentNoteId:null,siblingOrder:0,position:null,collapsed:false,manual:false},beta:{noteId:'beta',parentNoteId:'root',siblingOrder:0,position:null,collapsed:false,manual:false},gamma:{noteId:'gamma',parentNoteId:'root',siblingOrder:1,position:null,collapsed:false,manual:false},alpha:{noteId:'alpha',parentNoteId:'root',siblingOrder:2,position:null,collapsed:false,manual:false}},camera:{x:0,y:0,zoom:1}}}};
await v(`localStorage.setItem('catalyst.browser.workspace.v1',${JSON.stringify(JSON.stringify(state))});true`);await c('Page.reload');
for(let i=0;i<30;i+=1){await sleep(200);if(await v(`document.querySelectorAll('.picture-occurrence').length===4`))break;}
await v(`document.querySelector('[aria-label="Fit picture"]')?.click();true`); await sleep(450);
await v(`(()=>{const el=[...document.querySelectorAll('.picture-occurrence')].find(x=>x.textContent?.includes('Assessed claim'));el?.querySelector('.picture-object')?.click();return true})()`); await sleep(250);
const landmarks=await v(`(()=>{
  const active=[...document.querySelectorAll('.picture-occurrence')].find(x=>x.textContent?.includes('Assessed claim'));
  const before=document.querySelector('[aria-label="Move branch earlier"]');
  const after=document.querySelector('[aria-label="Move branch later"]');
  const mapGlyph=active?.querySelector('.analytical-glyph')?.className?.baseVal||'';
  const inspectorGlyph=document.querySelector('.inspector-identity .analytical-glyph')?.className?.baseVal||'';
  const paths=b=>b?[...b.querySelectorAll('path')].map(p=>p.getAttribute('d')):[];
  return {mapGlyph,inspectorGlyph,beforePaths:paths(before),afterPaths:paths(after),beforeVisible:!!before&&getComputedStyle(before.parentElement).display!=='none',zoom:document.querySelector('.picture-controls > span')?.textContent?.trim()};
})()`);
await v(`(()=>{const el=[...document.querySelectorAll('.picture-occurrence')].find(x=>x.textContent?.includes('Assessed claim'));el?.dispatchEvent(new MouseEvent('mouseover',{bubbles:true}));return true})()`); await sleep(250);
const hover=await v(`(()=>Object.fromEntries([...document.querySelectorAll('.picture-occurrence')].map(el=>[el.textContent?.trim(),{dimmed:el.classList.contains('is-dimmed'),opacity:getComputedStyle(el).opacity}])))()`);
const shot=await c('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
const screenshotPath='C:/Users/iris/Downloads/Catalyst/tools/research-probes/2026-09-13/icon-landmarks-hover.png';
fs.writeFileSync(screenshotPath,Buffer.from(shot.result.data,'base64'));
const pass=landmarks.mapGlyph.includes('analytical-glyph-claim')&&landmarks.inspectorGlyph.includes('analytical-glyph-claim')&&landmarks.beforeVisible&&landmarks.beforePaths.join('|')!==landmarks.afterPaths.join('|');
console.log(JSON.stringify({landmarks,hover,screenshotPath,pass},null,2));
ws.close();