import fs from 'node:fs';
const pages=await fetch('http://127.0.0.1:9229/json').then(r=>r.json());
const page=pages.find(x=>x.type==='page' && x.url.startsWith('http://127.0.0.1:5173'));
if(!page) throw new Error('No Catalyst CDP page');
const ws=new WebSocket(page.webSocketDebuggerUrl); let id=1; const pending=new Map();
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id)}};
await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
const c=(method,params={})=>new Promise(r=>{const n=id++;pending.set(n,r);ws.send(JSON.stringify({id:n,method,params}))});
const v=async expression=>(await c('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.result.value;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
await c('Page.enable'); await c('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
const raw=await v(`localStorage.getItem('catalyst.browser.workspace.v1')||''`); const state=raw?JSON.parse(raw):{};
const note=(id,title,createdAt)=>({id,title,body:'',createdAt,updatedAt:createdAt,deletedAt:null});
state.documents={}; state.annotations={}; state.viewerMarkups={}; state.links=[]; state.noteLinks=[];
state.customTechniqueDefinitions={}; state.techniqueRuns={}; state.pendingSelection=null; state.activeDocumentId=null;
state.notes={root:note('root','Sibling order root','2026-01-01T00:00:00.000Z'),alpha:note('alpha','Alpha — created first','2026-01-02T00:00:00.000Z'),beta:note('beta','Beta — authored first','2026-01-04T00:00:00.000Z'),gamma:note('gamma','Gamma — authored second','2026-01-03T00:00:00.000Z')};
state.activeNoteId='gamma'; state.relationships={}; state.evidenceTags={}; state.annotationTags=[]; state.annotationRoles={};
state.noteSemantics={root:{roles:['note'],confidence:null},alpha:{roles:['note'],confidence:null},beta:{roles:['note'],confidence:null},gamma:{roles:['note'],confidence:null}};
state.graphView={positions:{},camera:{x:0,y:0,zoom:1}}; state.capabilities={profile:'analytical',overrides:{}};
state.mapView={activeMapId:'analysis-overview',maps:{'analysis-overview':{id:'analysis-overview',name:'Sibling order probe',focusNoteId:'root',occurrences:{root:{noteId:'root',parentNoteId:null,siblingOrder:0,position:null,collapsed:false,manual:false},alpha:{noteId:'alpha',parentNoteId:'root',siblingOrder:2,position:null,collapsed:false,manual:false},beta:{noteId:'beta',parentNoteId:'root',siblingOrder:0,position:null,collapsed:false,manual:false},gamma:{noteId:'gamma',parentNoteId:'root',siblingOrder:1,position:null,collapsed:false,manual:false}},camera:{x:0,y:0,zoom:1}}}};
const url='http://127.0.0.1:5173/?research=unified-workflow&shell=spatial&run=sibling-reorder-live';
await c('Page.navigate',{url}); await sleep(1800);
await v(`localStorage.setItem('catalyst.browser.workspace.v1',${JSON.stringify(JSON.stringify(state))});localStorage.removeItem('catalyst.recovery.v1');true`);
await c('Page.reload',{ignoreCache:true});for(let n=0;n<30;n+=1){if(await v(`document.querySelectorAll('.picture-occurrence').length`)===4)break;await sleep(250);}
await v(`(()=>{const el=[...document.querySelectorAll('.picture-occurrence')].find(x=>x.querySelector('.picture-object-label')?.textContent?.includes('Gamma'));el?.querySelector('.picture-object')?.click();return true})()`); await sleep(350);
await v(`document.querySelector('[aria-label="Fit picture"]')?.click();true`); await sleep(500);
const measure=()=>v(`(()=>({order:Object.values(JSON.parse(localStorage.getItem('catalyst.browser.workspace.v1')).mapView.maps['analysis-overview'].occurrences).filter(o=>o.parentNoteId==='root').sort((a,b)=>(a.siblingOrder??999)-(b.siblingOrder??999)).map(o=>o.noteId),nodes:[...document.querySelectorAll('.picture-occurrence')].map(el=>({id:el.querySelector('.picture-object-label')?.textContent?.trim(),x:Math.round(el.getBoundingClientRect().x),y:Math.round(el.getBoundingClientRect().y)})),earlier:!!document.querySelector('[aria-label="Move branch earlier"]'),later:!!document.querySelector('[aria-label="Move branch later"]'),active:document.querySelector('.picture-occurrence.is-active .picture-object-label')?.textContent?.trim(),zoom:document.querySelector('.picture-controls > span')?.textContent?.trim()}))()`);
const snap=async name=>{const shot=await c('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});const path=`C:/Users/iris/Downloads/Catalyst/tools/research-probes/2026-09-13/${name}.png`;fs.writeFileSync(path,Buffer.from(shot.result.data,'base64'));return path;};
const before=await measure(); const beforePath=await snap('sibling-reorder-before');
const clicked=await v(`(()=>{const b=document.querySelector('[aria-label="Move branch earlier"]');if(!b)return false;b.click();return true})()`); await sleep(1200);
const after=await measure(); const afterPath=await snap('sibling-reorder-after');
await v(`(()=>{const el=[...document.querySelectorAll('.picture-occurrence')].find(x=>x.querySelector('.picture-object-label')?.textContent?.includes('Sibling order root'));el?.querySelector('.picture-object')?.click();return true})()`); await sleep(300);
const rootControls=await v(`(()=>({earlier:!!document.querySelector('[aria-label="Move branch earlier"]'),later:!!document.querySelector('[aria-label="Move branch later"]')}))()`);
console.log(JSON.stringify({clicked,before,after,rootControls,beforePath,afterPath,pass:clicked&&before.order.join(',')==='beta,gamma,alpha'&&after.order.join(',')==='gamma,beta,alpha'&&before.active?.startsWith('Gamma')&&!rootControls.earlier&&!rootControls.later},null,2));
ws.close();