import fs from 'node:fs';
const pages=await fetch('http://127.0.0.1:9229/json').then(r=>r.json());
const page=pages.find(p=>p.type==='page'); if(!page) throw new Error('No CDP page');
const ws=new WebSocket(page.webSocketDebuggerUrl);let id=1;const pending=new Map();
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id)}};
await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
const c=(method,params={})=>new Promise(r=>{const n=id++;pending.set(n,r);ws.send(JSON.stringify({id:n,method,params}))});
const v=async e=>{const m=await c('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true});if(m.result?.exceptionDetails)throw new Error(m.result.exceptionDetails.exception?.description||m.result.exceptionDetails.text||'Runtime.evaluate failed');return m.result?.result?.value;};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const snap=async n=>{const s=await c('Page.captureScreenshot',{format:'png'});const p=`C:/Users/iris/Downloads/Catalyst/tools/research-probes/2026-09-13/${n}.png`;fs.writeFileSync(p,Buffer.from(s.result.data,'base64'));return p};
await c('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
await v(`localStorage.removeItem('catalyst.xml.workspace.v1');localStorage.removeItem('catalyst.browser.workspace.v1');localStorage.removeItem('catalyst.recovery.v1');true`);
await c('Page.navigate',{url:'http://127.0.0.1:5173/?research=unified-workflow&fixture=tradecraft&shell=reader&run=source-first-visual'}); await sleep(4500);
const initial=await snap('source-first-01-reader');
const r=await v(`(()=>{const root=document.querySelector('embedpdf-container')?.shadowRoot;const q=[...(root?.querySelectorAll('img')||[])].map(e=>e.getBoundingClientRect()).find(r=>r.width>500&&r.height>700&&r.y<900);return q&&({x:q.x,y:q.y,w:q.width,h:q.height})})()`); if(!r) throw new Error('PDF page not found');
const sx=r.x+(150/612)*r.w,sy=r.y+((792-515)/792)*r.h,ex=r.x+(410/612)*r.w,ey=r.y+((792-465)/792)*r.h;
await c('Input.dispatchMouseEvent',{type:'mousePressed',x:sx,y:sy,button:'left',clickCount:1});for(let i=1;i<=18;i++){await c('Input.dispatchMouseEvent',{type:'mouseMoved',x:sx+(ex-sx)*i/18,y:sy+(ey-sy)*i/18,button:'left',buttons:1});await sleep(20)}await c('Input.dispatchMouseEvent',{type:'mouseReleased',x:ex,y:ey,button:'left'});await sleep(900);
const selected=await snap('source-first-02-selection');
await v(`[...document.querySelectorAll('button')].find(b=>b.textContent?.trim()==='Save evidence')?.click();true`); await sleep(800); const evidence=await snap('source-first-03-evidence-saved');
console.log(JSON.stringify({initial,selected,evidence,selection:!!await v(`document.querySelector('.selection-card')`),evidenceCount:await v(`(()=>{const raw=localStorage.getItem('catalyst.xml.workspace.v1');if(!raw)return 0;const doc=new DOMParser().parseFromString(raw,'application/xml');return doc.querySelectorAll('entry[key="annotations"] > object > entry').length})()`),xmlPersisted:!!await v(`localStorage.getItem('catalyst.xml.workspace.v1')`)},null,2));ws.close();